### ISSUE TITLE
Ability to change the sweep time.

### ISSUE THREAD

**Issue by Rappoman** [ESPresense/ESPresense#101]
First off a really good job on the implementation, you have made it easy to set-up and use.  

Would it be possible to add an option to set (reduce) the time between sweeps.  This would allow for the base stations to identify room changes quicker.  This in turn would help with automations in HA.

Thanks in advance.

**Comment by DTTerastar** [comment]
I'm not sure which value you mean.  We use a continuous scan.

**Comment by DTTerastar** [comment]
Some devices don't broadcast very often.  Tiles are like every 4 seconds, so they're slow.  Apple Watches are 10x a second so they move quick.  What kind of device are you tracking?

**Comment by Rappoman** [comment]
I am using several at the moment, Samsung S10 (HA Android app), Fitbit Ionic, Fitbit Charge 3 and another cheap sports watch.

**Comment by DTTerastar** [comment]
All of those take 10 seconds to be found in the new room?
