### ISSUE TITLE
Bad JSON in MQTT

### ISSUE THREAD

**Issue by jpettitt** [ESPresense/ESPresense#1038]
### Describe the bug

Under some circumstances (I'm not sure what triggered it) the ESP's set values of `inf` and/or `nan` in some fields in there MQTT message.   ESPresense Companion then throws an error trying to interpret the invalid JSON.  I ended up resetting everything and clearing down all the MQTT messages to get it working again - no idea how I got into that state.

### Version

3.3.0b8

### Active scan enabled

no

### Include filter

n/a

### Exclude filter

n/a

### Query filter

n/a

### Firmware flavor

standard

### Device (be specific)

AITRIP D1 Mini NodeMCU ESP32 ESP-WROOM-32

**Comment by DTTerastar** [comment]
I'm seeing mac be empty which causes a string of issues... Looking into it
