### ISSUE TITLE
RSSI shows 0 for POE devices

### ISSUE THREAD

**Issue by julianrinaldi** [ESPresense/ESPresense#1055]
### Describe the bug

Not sure if this is a bug, or purposeful, but my devices that are POE show the RSSI as 0 in Home Assistant. Inspecting the mqtt data, the RSSI does show up there. I think because of this, auto optimization doesn't work in the companion app, and the calibration page won't even load. 

### Version

v3.3.0b8

### Device (be specific)

Olimex ESP32-POE

### Screenshots

![](https://i.imgur.com/f5yVDrX.png)

![](https://i.imgur.com/g612kSo.png)

**Comment by DTTerastar** [comment]
That rssi is the wifi rssi and isn't used in optimization.  Only bluetooth rssi is used.
