### ISSUE TITLE
Allow the setting page to have authentication for changes.

### ISSUE THREAD

**Issue by asucrews** [ESPresense/ESPresense#106]
**Is your feature request related to a problem? Please describe.**
Allow the ability to enable a user and password to allow setting changes.

**Describe the solution you'd like**
Yes, this admin page is clear text, however, it is nice to be able to do this to lower the odds of someone making changes that could break the automation base on this.

**Describe alternatives you've considered**
does not need to be username and password could just be a password or something else

**Comment by phk-r** [comment]
This would be awesome. Feels a bit dodgy not to have any form of login to the ESP.

**Comment by cpainchaud** [comment]
+1

**Comment by pstreef** [comment]
I think basic auth for the portal would be great and should not be hard to add.

**Comment by asucrews** [comment]
What needs to be done to get this added?

**Comment by gith-account** [comment]
#647
