### ISSUE TITLE
/ui Devices Enroll Name and Button missing

### ISSUE THREAD

**Issue by Tokn59** [ESPresense/ESPresense#1060]
### Describe the bug

When going to my Esppresence device http://esppresence-livingroom I see Devices and Fingerprints.
Clicking on Devices does not result in being able to enter name and press Enroll button. Nothing is shown.

<img width="1270" alt="image" src="https://github.com/ESPresense/ESPresense/assets/9215231/8074af85-7e58-4de4-9c68-35a20d15b5bd">

### Version

V3.2.4

### Device (be specific)

ESP32-C3 Super Mini

### Logs

```text
Nothing specific in the logs
```

### Screenshots

<img width="1270" alt="image" src="https://github.com/ESPresense/ESPresense/assets/9215231/bf338d75-8064-464e-b703-171c12a9fd27">

**Comment by DTTerastar** [comment]
Fixed in [v3.3.0b10](https://github.com/ESPresense/ESPresense/releases/tag/v3.3.0b10)
