### ISSUE TITLE
ESPresense on HA server

### ISSUE THREAD

**Issue by LukaszP2** [ESPresense/ESPresense#1067]
### Is your feature request related to a problem? Please describe.

I've server for HA with bluetoth. Can it works as Base Stations?

### Describe the solution you'd like

Do same addon for HA.

### Describe alternatives you've considered

Use other soft  (like room assistant and integrating with ESPresense.

**Comment by DTTerastar** [comment]
Not at the moment, and probably not a lot of demand since the esp32s are very cheap and easy to use.
