### ISSUE TITLE
HA 2023.11.0b0 sensor dont work

### ISSUE THREAD

**Issue by LukaszP2** [ESPresense/ESPresense#1068]
### Describe the bug

After upgrade HA to 2023.11.0b0  sensor for beacons is missing

**Comment by pdanny421** [comment]
I had the same problem. Updating to 2023.11.0b1 resolved the issue for me.

**Comment by LukaszP2** [comment]
Yes upgrade help

**Comment by LukaszP2** [comment]
Yes, it helped
