### ISSUE TITLE
Strange distance readings

### ISSUE THREAD

**Issue by buhralex** [ESPresense/ESPresense#107]
**Describe the bug**
I'm on v2.0.6

On 1m distance between my phone and my Kitchen ESPresense Sensor I get a distance reading of 0,37.
rssi@1m: -74
rssi: -60
raw: 0,4

You can also see the distance to the Livingroom sensor in the screenshot. The distance should be somewhere around 8-9 meters.

One thing to mention: The kitchen sensor and the office sensor are currently located in the same room because of debugging reasons. But they are 2m apart from each other. The distance between my office sensor and my phone should be much bigger than seen in the screenshot.

**Expected behavior**
The distance should read 1.

**Logs**
```
Hostname:     espresense-kitchen
Room:         kitchen
Max Distance: 16.00
Telemetry:    enabled
Rooms:        enabled
Devices:      enabled
Discovery:    enabled
PIR Sensor:   disabled
Radar Sensor: disabled
DHT11 Sensor: disabled
DHT22 Sensor: disabled
BH1750_I2c Sensor: 
Connecting to MQTT 192.168.1.104 1883
0 New   | MAC: df88ae238b56, ID: df88ae238b56                                                 
0 Close | MAC: df88ae238b56, ID: df88ae238b56                                                 (0.11m) -37dBm
0 New   | MAC: c048e6a9730f, ID: samsung:c048e6a9730f                                         
0 New   | MAC: 619f88879785, ID: exp:20                                                       
0 New   | MAC: 5354d7dda7db, ID: sid:0xfe9f                                                   
0 New   | MAC: de8ff3cd6334, ID: sid:0xfe0f                                                   
0 New   | MAC: cdf2c8551ebe, ID: sid:0xfe0f                                                   
0 New   | MAC: 733877169db4, ID: iBeacon:76e1f0fe-c50b-4519-a2d3-114f544b1d49-100-1           
0 Left  | MAC: df88ae238b56, ID: df88ae238b56                                                 (0.13m) -87dBm
0 Close | MAC: df88ae238b56, ID: df88ae238b56                                                 (0.13m) -36dBm
0 Left  | MAC: df88ae238b56, ID: df88ae238b56                                                 (0.13m) -81dBm
0 Close | MAC: df88ae238b56, ID: df88ae238b56                                                 (0.13m) -37dBm
0 Left  | MAC: df88ae238b56, ID: df88ae238b56                                                 (0.14m) -63dBm
0 Close | MAC: df88ae238b56, ID: df88ae238b56                                                 (0.14m) -39dBm
0 Left  | MAC: df88ae238b56, ID: df88ae238b56                                                 (0.14m) -87dBm
0 Close | MAC: df88ae238b56, ID: df88ae238b56                                                 (0.14m) -38dBm
0 Left  | MAC: df88ae238b56, ID: df88ae238b56                                                 (0.15m) -53dBm
0 New   | MAC: 449e9f311389, ID: 449e9f311389                                                 
0 New   | MAC: 5ed22efcde02, ID: exp:20                          
```

**Hardware Details**
My phone is a Huawei P30Pro. I'm using the Home Assistant BLE-Transmitter implementation.
Sensor is a ESP32 DevKitC V4

**Screenshots**
![image](https://user-images.githubusercontent.com/6676113/139399155-92951a2f-0fba-4cd7-a466-6ce3a04ff46e.png)

**Comment by cephos** [comment]
I have the same problem with my ulefone armor 7e android phone (homeassistant-app) and a esp32-cam-module. Would be glad to provide some more debugging information, when there is a chance the problem can then be resolved.

**Comment by DTTerastar** [comment]
Rss@1m of -74 is the issue.  If you have an rss less than -74 the calculation will make the distance < 1m. -61 is a pretty powerful signal at 1m.  Hass is adding the capability of putting in a calibrated rss@1m into the beacon so once that is in you should be able to fix this.  ATM you can set the transmit power lower and see if that fixes things.

Beacon simulator let's you change that rss@1m value already, so you could use that and put in -61 and you should be perfect.  I could add an option to "ignore" the Rss@1m power then you could change the generic txPower value. (-65)

**Comment by buhralex** [comment]
> Rss@1m of -74 is the issue. If you have an rss less than -74 the calculation will make the distance < 1m. -61 is a pretty powerful signal at 1m. Hass is adding the capability of putting in a calibrated rss@1m into the beacon so once that is in you should be able to fix this. ATM you can set the transmit power lower and see if that fixes things.
> 
> Beacon simulator let's you change that rss@1m value already, so you could use that and put in -61 and you should be perfect. I could add an option to "ignore" the Rss@1m power then you could change the generic txPower value. (-65)

I already tried to set the transmit power to ultra low setting in HA Android App but nothing changed. I might just wait until that feature is built into the App. Else I will try Beacon simulator! Thank you

**Comment by DTTerastar** [comment]
Have you been able to get this all working?

**Comment by bachoo786** [comment]
> > Rss@1m of -74 is the issue. If you have an rss less than -74 the calculation will make the distance < 1m. -61 is a pretty powerful signal at 1m. Hass is adding the capability of putting in a calibrated rss@1m into the beacon so once that is in you should be able to fix this. ATM you can set the transmit power lower and see if that fixes things.
> > Beacon simulator let's you change that rss@1m value already, so you could use that and put in -61 and you should be perfect. I could add an option to "ignore" the Rss@1m power then you could change the generic txPower value. (-65)
> 
> I already tried to set the transmit power to ultra low setting in HA Android App but nothing changed. I might just wait until that feature is built into the App. Else I will try Beacon simulator! Thank you

I am keen to know if you got it working?  As u am facing similar issues.
