### ISSUE TITLE
Flashing via web browser not working

### ISSUE THREAD

**Issue by ragenhe** [ESPresense/ESPresense#11]
The process does finish and says successful, however, it doesn't appear to be successful.

No AP is created and the ESP32, using a serial monitor, reports nothing present to load.

**Comment by April-ha** [comment]
the web flash does not transmit personal settings.
you have to use Atom.

**Comment by DTTerastar** [comment]
What device are you using?

**Comment by ragenhe** [comment]
ESP32 dev board.

**Comment by DTTerastar** [comment]
I think I found the issue.  Deploying a fix now.  Once I test it good I'll let you know.

**Comment by DTTerastar** [comment]
Ok it worked for me now.  I added the bootloader flashing this morning and hadn't fully tested it.  I needed to use the bootloader that looks for the partition table at 0x8000.  The files have a 5 minute cache so it might take that long for you to get the right one.

**Comment by ragenhe** [comment]
Amazing work and turn around. Thank you!!  I will let you know what the results are as soon as I know.

**Comment by ragenhe** [comment]
It is working!!!

**Comment by DTTerastar** [comment]
Awesome!
