### ISSUE TITLE
Fingerprints should show all IDs, not just included ones

### ISSUE THREAD

**Issue by rwjack** [ESPresense/ESPresense#1113]
### Is your feature request related to a problem? Please describe.

https://github.com/ESPresense/ESPresense/pull/1088

Referenced above, if fingerprints are for debugging purposes, wouldn't it be clear to show all IDs there, instead of just the included ones?

**Comment by DTTerastar** [comment]
[v3.3.1](https://github.com/ESPresense/ESPresense/releases/tag/v3.3.1) just added just this!

**Comment by rwjack** [comment]
@DTTerastar I am running v3.3.1. 

When I go to fingerprints all I see is the single beacon that is included on the Settings>Filtering page.

**Comment by DTTerastar** [comment]
![image](https://github.com/ESPresense/ESPresense/assets/1491145/9c09689c-ce7c-4c92-a3e5-c5ea35ebb815)

is the default, change it to blank (no filter)

![image](https://github.com/ESPresense/ESPresense/assets/1491145/d2a10f9d-3da7-47e7-a6ce-08a2507699df)

**Comment by rwjack** [comment]
Ohh, I see now. That seemed invisible to me.

I'm not an UX expert, but perhaps those tabs should be rotated?

Show the table headers first, then the data?

**Comment by DTTerastar** [comment]
Svelte table works like that... I do agree it's not the most intuitive....
