### ISSUE TITLE
 WebSocket connection to 'ws://<ip>/ws' failed using M5STACK Stamp S3

### ISSUE THREAD

**Issue by ee02217** [ESPresense/ESPresense#1140]
### Describe the bug

When enrolling an apple device, as soon as I connect from the iPhone or Apple Watch the following error is raised in the console:

`index.js:1 WebSocket connection to 'ws://192.168.1.232/ws' failed: Close received after close`

### Version

v3.3.2b3

### Logs

```text
index.js:1 WebSocket connection to 'ws://192.168.1.232/ws' failed: Close received after close
(anonymous) @ index.js:1
```

**Comment by DTTerastar** [comment]
That's an s3, it looks like you need the Cdc build to get serial output.

**Comment by DTTerastar** [comment]
C3 is different from S3.  You've got to be using an s3 based on your serial output: 

> ESP-ROM:esp32s3-20210327 

![image](https://github.com/ESPresense/ESPresense/assets/1491145/2c0f7194-784e-4c12-90ab-d274002030b8)
Cdc is for the ones that say cdc in this chart:

![image](https://github.com/ESPresense/ESPresense/assets/1491145/694948b6-5a4f-4564-9dce-ac01840bd7f1)

**Comment by ee02217** [comment]
This is the log when enrolling with the new build:

```
Connected to: 4f:d5:8f:d4:b1:13
MTU updated: 23 for connection ID: 2
0x2a29: onRead(), value: ESPresense
0x2a24: onRead(), value: office
Client ID: 2 Address: 4f:d5:8f:d4:b1:13 Subscribed to notfications for 0x2a37
```

**Comment by DTTerastar** [comment]
That looks like success.  So the mcu doesn't crash, but the UI seems to give up early?

**Comment by asdasd-dev** [comment]
@ee02217 have you managed to resolve an issue?
