### ISSUE TITLE
Cant Pair iPad Pro (3rd Gen)

### ISSUE THREAD

**Issue by mikeaumiller** [ESPresense/ESPresense#1143]
### Describe the bug

I have successfully installed my first ESP32-S3 flashed to the latest firmware 3.3.1 and have registered my Android S22 Ultra. 

When attempting to do the same for my iPad Pro 3rd Gen (IOS 17.1.2) I cant seem to Enroll sucessfully. After I give it a name "iPad" the countdown timer begins as normal, and then on my iPad I can see and connect to the ESPresense bluetooth device but nothing else happens,  it just stays connected.. over on the ESPresense device the timer just eventually expires.

Then I attempt to look for a IRK within MQTT Explorer and see nothing.

Please advise...

### Version

3.3.1

### Device (be specific)

AtomS3 - Lite

**Comment by brunnoperes** [comment]
I'm having the same issue, I had an iPhone 13 Pro and I'm able to pair on the iPhone Bluetooth settings but on the ESPresense Device nothing happens and the time expires. It seems that it is not enrolling the phone.

I've use the manual lookup method to get my Watch IRK but can't seem to be able to enroll my phone.

Board: ESP32-S3
ESPresense Version: 3.1.1

**Comment by spiralfive** [comment]
I am seeing identical behavior to this - on my iPhone 14. I am on iOS 17.2 - my Apple Watch is doing the same thing despite me also using the bluetooth terminal application to pair. It is on WatchOS 10.0.1. I am using ESPresense 3.3.1. 

This is my first time using ESPresense - I was able to pair my laptop this way and it instantly worked as it should (the popup went away and the device appeared in the list). I did notice in the documentation it is supposed to ask to "securely pair" - I am not getting a prompt to do that. It just asks to pair, "secure" is not in the message. I don't know if Apple changed the verbiage or if that is an indication of the problem.

**Comment by wcarman1** [comment]
I have the same problem right now. I was able to work around it by just adding the device in HA via the device ID but I know I've seen two devices with the same ID so I don't know how long the work-around will actually work. I also tried the lookup method via Mac and none of GUIDs seem to correspond to my iPhone 13 Pro (I'm on 17.2) which is odd because I do have them both on the same iCloud account and sync is enabled. So I'm not sure what is up with that either.

**Comment by brunnoperes** [comment]
@wcarman1 I think that the iCloud/Mac method is only for the Apple Watch. I was able to use it to add my Apple Watch but couldn't find my phone. I was using the device ID as well that I got from (MTQQ Explorer) but sometimes it shows 2 identical ones with different distances, I don't think is very reliable.

**Comment by spiralfive** [comment]
After updating to iOS 17.3 - the behavior has changed. When I try to enroll the device, ESPresense acknowledge the device paired and shows the name on the screen. And the popup closes. However, the device does not appear on my devices list after the pairing process completes.
