### ISSUE TITLE
GL-iNET GL-S10 v2.1 Severe Packet Loss

### ISSUE THREAD

**Issue by Coder84619** [ESPresense/ESPresense#1182]
### Describe the bug

With ESPresence 3.3.1, the GL-iNET GL-S10 v2.1 Ethernet port has severe packet loss (roughly 50%). The solution, as found by the ESPHome team, is to change clk_mode to GPIO0_IN. 

Reference: https://github.com/esphome/bluetooth-proxies/commit/655ebf74775e6b7bb3abe7c22ce31c3dfcfc0ffe

### Version

3.3.1

### Device (be specific)

GL-iNET GL-S10 v2.1

**Comment by Matsuo3rd** [comment]
Weird. Fix I provided to address this specific issue was already available in for 3.3.1 (version you indicated you are using).
See https://github.com/ESPresense/ESPresense/blob/v3.3.1/lib/network/Network.h (line 151)

**Comment by Coder84619** [comment]
Ping tests via ethernet cable range from 12% to 50% packet loss for v3.3.1.

![2024-01-18_12-47-21](https://github.com/ESPresense/ESPresense/assets/30213019/3c142e1b-ef3b-4463-9b10-09c97fd0854f)
