### ISSUE TITLE
Settings page disappears once setting an included ID in the filtering section

### ISSUE THREAD

**Issue by ph15h** [ESPresense/ESPresense#1192]
### Describe the bug

Adding anything in this field 
`Include only sending these ids to mqtt (eg. apple:iphone10-6 apple:iphone13-2):`
removes the entire settings page located on `deviceIP/ui/#/settings` and makes the page blank. The HTML shows that it's
![firefox - 2024-01-09 18-23-04](https://github.com/ESPresense/ESPresense/assets/50638066/d7be0aa8-61b0-4a77-a2bc-b145d4a9d766)

Other ESPresense devices settings pages are still fine. Sending an empty MQTT payload to `espresense/rooms/bedroom/include` to remove the IRK does not remove the setting. Restarting the device does not solve the issue and it shows up again. Reinstalling ESPresense entirely is the only 

Screenshot showing what's shown throught MQTT explorer
![MQTT_Explorer - 2024-01-09 18-04-38](https://github.com/ESPresense/ESPresense/assets/50638066/431193b3-ca2c-4f0b-844a-54649a35a337)

Affected ESPresense Device 

Happens on Chrome, Firefox and Edge.
![firefox - 2024-01-09 17-59-07](https://github.com/ESPresense/ESPresense/assets/50638066/886f8baa-a101-4b97-833c-23be8356053d)

Unaffected Device with that field empty
![firefox - 2024-01-09 18-02-14](https://github.com/ESPresense/ESPresense/assets/50638066/5942a122-22f2-46bf-9e4f-1f73f8fe529c)

### Version

ESPresense Version: v3.3.1

**Comment by Psythian** [comment]
In my testing when I put .5 instead of 0.5 and I changed to any other page from settings and went back it would immediately show the grey square. As long as I put the 0 in the front of the point it would work. So far after erasing and reloading several times that is my fix. Now to wipe and reload 4 more...
![image](https://github.com/ESPresense/ESPresense/assets/24928860/24104c76-1040-4394-b397-d274f657e0d8)

**Comment by DTTerastar** [comment]
It doesn't happen for me.  I've always had stuff in include:

![image](https://github.com/ESPresense/ESPresense/assets/1491145/502c519e-bc21-4720-9810-6da5c45719e8)

**Comment by DTTerastar** [comment]
I can confirm that .5 causes issues:

SyntaxError: Unexpected token '.', ..."kip_dist":.5,"skip_m"... is not valid JSON

**Comment by DTTerastar** [comment]
I released this in 3.3.2, please test!
