### ISSUE TITLE
[Question/Bug] No way to remove a device in UI?

### ISSUE THREAD

**Issue by PalmTamino** [ESPresense/ESPresense#1196]
### Describe the bug

I added a device here I don't have anymore a long while ago, how to remove it?

### Version

v3.3.2b4

### Screenshots

![grafik](https://github.com/ESPresense/ESPresense/assets/36358673/3ca561a9-8002-4553-af9d-3ab5725eaf97)

**Comment by adolfonovo** [comment]
Hi. Just use MQTT-EXPLORER and delete the node under espresense/settings
