### ISSUE TITLE
Status LED 

### ISSUE THREAD

**Issue by sEdsKi** [ESPresense/ESPresense#1237]
### Describe the bug

Documentation references a checkbox to disable the status LED. This option is not present ;-)

<img width="141" alt="image" src="https://github.com/ESPresense/ESPresense/assets/98076159/22f2c4fa-1519-4410-aacb-4358d9d3dc67">

### Version

ESPresense Version: v3.3.1

### Device (be specific)

ESP32 WROOM 32

**Comment by CoMPaTech** [comment]
I think I came across this before but if it's a LED like the blue one on mine it can't be disabled programmatically if I recall correctly.

**Comment by ginkel** [comment]
I think you can disable the blue LED by setting the LED 1 pin to `-1`.

**Comment by Oli-BY** [comment]
There isnt any possiblity to switch the red ESP32 LED off. That would be very helpful

**Comment by ginkel** [comment]
The red LED is always on, afaik. You can unsolder it if it annoys you.
