### ISSUE TITLE
iBeacon loses WiFi after a few hours

### ISSUE THREAD

**Issue by superpower10** [ESPresense/ESPresense#1285]
The iBeacons seems to have a WiFi problem because it looses the connection after a few hours. 

After unplugging from power, wait a few seconds and reboot. The iBeacon is back online.

The distance between the iBeacon and the Access Point is less than three meters. With no walls or anything between. It’s in the same room. So it can‘t be a WiFi Coverage-Problem.

Anybody could help me with that?

**Comment by MeierAlex** [comment]
Maybe related to this topic ?
https://github.com/ESPresense/ESPresense/issues/1272
