### ISSUE TITLE
Web portal should load after wifi connection details established

### ISSUE THREAD

**Issue by vanstinator** [ESPresense/ESPresense#13]
I used the website to flash an esp32 dev board. After connecting to wifi I was hoping to change additional settings from my desktop but the captive portal doesn't seem to be available. I would love to be able to hit the board at it's IP and be able to mess with additional settings.

**Comment by DTTerastar** [comment]
Totally agree.  WifiSettings lib doesn't do that out of the box.  Looking for lib that supports that.

**Comment by ragenhe** [comment]
It might just be a tiny web server that is needed?

**Comment by DTTerastar** [comment]
PRs accepted!

**Comment by czendler** [comment]
This might be useful
https://github.com/rjwats/esp8266-react

**Comment by DTTerastar** [comment]
That is VERY cool.  The issue is it uses SPIFFS to store the web server contents, but we use SPIFFS to store the settings atm:

https://github.com/Juerd/ESP-WiFiSettings/blob/master/WiFiSettings.cpp#L3
https://github.com/Juerd/ESP-WiFiSettings/blob/master/WiFiSettings.cpp#L43

If we added that everyones ESPs would forget what Wifi to connect to every new firmware.

**Comment by RichieFrame** [comment]
Is that a huge problem though? I have no issue reconnecting a few devices back to wifi if it means I can easily change a setting later. Later down the line could it be possible to use versioning? Can you store the web server contents AND the settings, but not have either of them be overwritten during the upgrade? That way, you could have major upgrades that overwrite SPIFFS, and minor upgrades that do not, or is that not possible?

**Comment by DTTerastar** [comment]
Not unsurmountable for sure.

**Comment by vanstinator** [comment]
Personally a firmware update resetting wifi settings would ensure I rarely
to never update. That's a huge hassle.

**Comment by DTTerastar** [comment]
v1.5.5 allows you to change the maxDistance via mqtt.

**Comment by DTTerastar** [comment]
This has been implemented in master.  Any kind souls want to test it before I roll it out?

**Comment by RichieFrame** [comment]
downloading

**Comment by DTTerastar** [comment]
Released!
