### ISSUE TITLE
Web site documentation

### ISSUE THREAD

**Issue by steveothesane** [ESPresense/ESPresense#1301]
I couldn't find this issue so if I missed the issue request I do appologize for being redundant.  

The documentation for the latest firmware for ESPresense is out of date and doesn't explain some of the features of the new version which for newbies can make configuring and troubleshooting a bit confusing and frustrating.  Is there any chance that the documentation might be updated here in the future?

I do like what you have done with ESPresense.  Thank you.

Sincerely,

Steveo-The-Sane

**Comment by dalto12593** [comment]
I honestly feel the same. I've been working on getting espresense and the companion setup for over a month. Trying to piece together details from other posts and trial and error. It's been the most frustrating aspect of my home assistant project by far. 

The documentation around calibration, bounds, floors, manually inputting known BLE macs, distance measures, sensor template and options in the HA configuration file, etc. 

My biggest struggle has been my devices not being in the correct spot, or relatively stationary. I've tried less base stations, more base stations, etc. 

More documentation is greatly appreciated.
