### ISSUE TITLE
Support for multi-sensor

### ISSUE THREAD

**Issue by circa1741** [ESPresense/ESPresense#139]
**Is your feature request related to a problem? Please describe.**
Please see https://www.reddit.com/r/homeassistant/comments/r78ufv/weve_built_multisensor_hardware_specifically_for/. It would be nice for ESPresense to be able to support the different sensors.

**Describe the solution you'd like**
For ESPresense to be able to support the different sensors in the above link.

**Describe alternatives you've considered**
For those of us not into soldering individual components, it would be nice to simply upload the ESPresense in the product above.

**Comment by DTTerastar** [comment]
Very cool!  I'd love one of those.  I didn't see any pricing/where to order it.

**Comment by circa1741** [comment]
They are still working on the product. However, ESPresense was mentioned in the thread.

**Comment by corgan2222** [comment]
#shutupandtakemymoney :)
I would buy a bunch of those too.
