### ISSUE TITLE
Flashing device a second time from web doesn't wipe settings

### ISSUE THREAD

**Issue by vanstinator** [ESPresense/ESPresense#14]
When flashing from the web (and possibly compiling from source, untested) the process does not reset any settings (such as wifi). I was attempting to get back to an out-of-box state so I could use the captive portal to change additional settings. But I can't seem to get to that state even when flashing.

**Comment by DTTerastar** [comment]
If you short D15 to ground w/ 1.1.2 it'll do it.  (That's the button of a DevKit)  I'm also going to add an erase to the web flasher as well.

**Comment by DTTerastar** [comment]
Ok, there is now an option to do this:  [  ] Clean install (allows you to change settings). See if it works for you.

**Comment by vanstinator** [comment]
That worked! Thank you!
