### ISSUE TITLE
Allow manual entry of WiFi credentials from webserver (ESP32 configuration)

### ISSUE THREAD

**Issue by yang3535** [ESPresense/ESPresense#142]
**Is your feature request related to a problem? Please describe.**
Related to issue #141, but should done for hidden WiFi networks regardless

**Describe the solution you'd like**
Allow manual entry of WiFi credentials from webserver page (192.168.4.1)

**Describe alternatives you've considered**
Add option to add WiFi credentials manually independently of scanning for networks.  

**Additional context**

**Comment by FizzedInMyPantz** [comment]
Agreed, this would be helpful when connecting to networks with a hidden SSID.

**Comment by corgan2222** [comment]
Fixed in my fork
https://github.com/corgan2222/ESPresense
