### ISSUE TITLE
Interference with Bluetooth headset 

### ISSUE THREAD

**Issue by ee02217** [ESPresense/ESPresense#146]
Not really a bug or feature request, but every time I’m closer to one of my esp32s running this, my headset has a “clicking” sound every few seconds. 

The headset is Jabra Evolve2 65. 
Similar to what is reported here: https://www.reddit.com/r/Jabra/comments/gm6sth/65t_tickingclick_noise/

Do you guys think there is anyway to exclude a device?

**Comment by corgan2222** [comment]
There was a [discussion ](https://github.com/ESPresense/ESPresense/issues/58) about this topic. I still think that a filter can be useful.

**Comment by DTTerastar** [comment]
With Active off, Query off, does it still do it?

**Comment by ee02217** [comment]
Hi,
Just tested with both off, and issue still occurs. :(
