### ISSUE TITLE
802.1x support

### ISSUE THREAD

**Issue by stevemann4** [ESPresense/ESPresense#147]
I need to connect to 802.1x WIFI with SSID, username and password. (no certificate). 

I'd like the option in the configuration to select an enterprise WIFI network and ask for username and optionally identity.

I have hacked this support into WIFISettings class and it tests okay. Is there any reason why this should be avoided? The current code says this is not supported.

Is there any interest in this enhancement?

**Comment by corgan2222** [comment]
The WiFi Settings are [based ](https://github.com/Juerd/ESP-WiFiSettings) on a library which stopped active development on somewhere in March. @DTTerastar [forked ](https://github.com/ESPresense/ESP-WiFiSettings/commits/master) the lib and made some changes. 
So I don't see a reason not to develop the lib even more and add more functions. 
If you made a PR, others can look into it.
