### ISSUE TITLE
Hidden SSID

### ISSUE THREAD

**Issue by bfranke1973** [ESPresense/ESPresense#153]
I am operating my IoT WiFi network with a hidden SSID. The current firmware lets me select the WiFi network to connect to from a list of networks found while scanning for WiFi networks. Networks with a hidden SSID don't show up on this list.

It would be great if there was a way of entering the name of a network if it doesn't show up in the list.

I could certainly make my IoT WiFi network visible, but I'd prefer not to.

**Comment by bfranke1973** [comment]
Thanks, I've just tried it out and it appears to work - perfect! Thanks.

**Comment by corgan2222** [comment]
Great! Thanks for testing. I will make the PR to get this into the next Release Version.
