### ISSUE TITLE
Implement Home Assistant Autodiscovery for mqqt_room

### ISSUE THREAD

**Issue by bluesheep** [ESPresense/ESPresense#154]
**Is your feature request related to a problem? Please describe.**
I would like devices that I'm tracking to be automatically discovered and configured within home assistant.

**Describe the solution you'd like**
Newly discovered BLE devices should be able to publish their MQTT information in a format that allows home assistant to automatically discover them as new devices. 

**Describe alternatives you've considered**
The existing process of manually editing sensors is functional but suboptimal.

**Additional context**
In high traffic areas this is likely to result in a lot of devices being discovered within home assistant. Consideration should be made for whether a whitelist/blacklist solution is required. c.f. #152

**Comment by corgan2222** [comment]
I will look into this.

**Comment by bluesheep** [comment]
@corgan2222 let me know if I can do anything to help. I've got the code compiling and uploading locally. I'm OK at writing code but I have no experience with GitHub, and only hobby hacking with c++.

**Comment by corgan2222** [comment]
Thanks. ATM im working on support for more input/output pins, like LED, switches, aso.
After that, I will look into this.

**Comment by DTTerastar** [comment]
With v3 we now have the beginning of a ui (see /ui/) that I intend to use to make this happen.  Stay tuned!

**Comment by bluesheep** [comment]
Woohoo!

**Comment by DTTerastar** [comment]
next!

**Comment by bluesheep** [comment]
Still keen. Only replying to distract the stalebot
