### ISSUE TITLE
Add support for sht31 sensor

### ISSUE THREAD

**Issue by Maaaciek1** [ESPresense/ESPresense#155]
Please add support for sht31 sensor as it is much more reliable than already supported dht11 and dht22.

Also... any chance on integration with wled? (I doubt it but I have to ask)

**Comment by corgan2222** [comment]
WLED runs as [firmware ](https://kno.wled.ge/basics/install-binary/) on the esp. I don't see a change to get this running.

I would love to integrate the sht31 sensor, but I don't have one.
[Just send me one](https://www.amazon.de/hz/wishlist/ls/30QURXYJ6P1FM?ref_=wl_share), to get the sensor integrated.
