### ISSUE TITLE
To be able to disable the onboard LEDs

### ISSUE THREAD

**Issue by circa1741** [ESPresense/ESPresense#156]
**Is your feature request related to a problem? Please describe.**
Some onboard LEDs are too bright especially in the bedroom during sleeping time.

**Describe the solution you'd like**
It would be nice to be able to disable the onboard LEDs. For boards with multiple LEDs, maybe a comma-separated GPIO values to disable.

**Describe alternatives you've considered**
Black nail polish, black electrical tape, removing the LEDs, etc.

**Additional context**
N/A

**Comment by FizzedInMyPantz** [comment]
Agreed. I've resorted to covering with a sock lol would love to be able to turn off LEDs via software.

**Comment by mjcumming** [comment]
Please!

**Comment by nmajin** [comment]
I agree, luckily the way I have it plugged in the LEDs are facing the wall but they are still lighting up the rooms.

**Comment by DTTerastar** [comment]
I can't control the power leds on the devkits.  So no matter what you've got one led to cover up :(
