### ISSUE TITLE
IOS App to help with tracking

### ISSUE THREAD

**Issue by B-Hartley** [ESPresense/ESPresense#160]
Just looking at ESPresence for the first time.
I've previously played with room-assistant with mixed success.
One thing room-assistant has that you don't at the moment is an ios app.
They released it through test-flight for simplicity but it allowed the iphones to be tracked reliably although they normally rotate their IDs.
Is this something you've looked at, or could look at?

Thanks

**Comment by linglingpin** [comment]
The current version of ESPresense supports the room-assistant companion app for identifying devices.

**Comment by B-Hartley** [comment]
That's great.
