### ISSUE TITLE
Support for ESP32 cam

### ISSUE THREAD

**Issue by craigjmidwinter** [ESPresense/ESPresense#163]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for the ESP32 Camera module in order to avoid needing to deploy multiple ESP32 units in a single room

**Describe alternatives you've considered**
Deploying multiple ESP32

**Additional context**
[Example of ESP32 cam project](https://github.com/easytarget/esp32-cam-webserver)

**Comment by DTTerastar** [comment]
There is an attempt at this in a PR, but the poor CPU of the ESP starts to get bogged down when trying to also support images.

**Comment by duceduc** [comment]
Would it be ok to use the ESP32 cam strictly for BLE tracking? Meaning flashing the esp32 cam with espresense firmware.
