### ISSUE TITLE
Document Fitbit Inspire 2 tracking sensor

### ISSUE THREAD

**Issue by jimbojd72** [ESPresense/ESPresense#167]
https://www.fitbit.com/global/us/products/trackers/inspire2

I just want to document on https://espresense.com/beacons was able to track Inspire 2 from Fitbit with ESPresense. I was able to do by using the Tile tracking functionality in the Inspire 2.

Anything else I need to add?

**Comment by DTTerastar** [comment]
Hit edit on https://github.com/ESPresense/ESPresense.github.io/blob/master/beacons.md
