### ISSUE TITLE
How to find/track iPhone?

### ISSUE THREAD

**Issue by jannnfe** [ESPresense/ESPresense#170]
Hello,

i have two ESPresense Devices. After a long search, I was able to identify my iPhone's ID in the list of many other Apple devices. Everything worked out too. But the ID changes after restarting Home Assistant or after restarting my iPhone. How can I always reliably assign the same ID to my iPhone? Or am I doing something wrong? Is there an easy way to identify my iPhone?

Many thanks in advance. I really like the project :)

**Comment by DTTerastar** [comment]
Which id are you using?  Have you tried turning on the Query option?  Or have you tried installing the room assistant iOs App?
