### ISSUE TITLE
Samsung Galaxy Fit 2

### ISSUE THREAD

**Issue by maprolim** [ESPresense/ESPresense#171]
A request to enable the project to use [Samsung Galaxy Fit 2](https://www.amazon.com/dp/B08LQSGJRJ/ref=mp_s_a_1_4?crid=114R7SPL5DGYB&keywords=galaxy+fit+2&qid=1641798720&sprefix=galaxy+fit+2%2Caps%2C255&sr=8-4) as a beacon, as today is possible with Mi Band 5.

PS. Thanks: Amazing project!!!

**Comment by DTTerastar** [comment]
Do you see a md or sd fingerprint at all when you bring it close?  If not it might not be broadcasting anything...

**Comment by maprolim** [comment]
Actualy it have the ID samsung:XXXXXXXXXXXX (XX... stando for the device MAC). I can see that in 1 day, my beacons just receive 33 messages.
