### ISSUE TITLE
Not a bug... Just a newbie question

### ISSUE THREAD

**Issue by hvddrift** [ESPresense/ESPresense#174]
I have some of these: ATOM Lite from M5 

Which install selection do I pick?

The M5Atom-Matrix-Led Matrix? 

![chrome_2022-01-11_13-42-56](https://user-images.githubusercontent.com/972926/148877665-d39dad3e-5cf9-49ad-9019-d1c988997bcd.png)
g

Thanks

**Comment by mjcumming** [comment]
This only works on an ESP32

**Comment by hvddrift** [comment]
This is a ESP32 device. It's the top one listed on this page

https://espresense.com/hardware

**Comment by Arganox** [comment]
@hvddrift have you tried flashing it with the generic ESP32 image? I'm using this on a M5Stamp Pico.

**Comment by StarFleetCPTN** [comment]
I used m5atom-matrix on my M5Atom lites without any changes.

**Comment by begunfx** [comment]
I have the Atom lite and I just used the generic esp32.

**Comment by hvddrift** [comment]
Thank you. Works great.

**Comment by Arganox** [comment]
> Thank you. Works great.

Good to hear! 👍 
Don't forget to mark the issue as solved.

**Comment by DTTerastar** [comment]
Yes, The M5Atom-Matrix-Led works great on all m5atoms.
