### ISSUE TITLE
documentation update: Home Assistant autodiscovery for sensor nodes

### ISSUE THREAD

**Issue by wivaku** [ESPresense/ESPresense#180]
The [ESPresense documentation](https://espresense.com/home_assistant) still mentions I should add a `binary_sensor` for each **sensor node**.  
I believe, since v1.5 of ESPresense, Home Assistant MQTT autodiscovery is available for **sensor nodes**.
For me (v2.0.13 of ESPresense) it works fine without specifying the `binary_sensor`.

Other requests / questions for the documentation:

- **beacon** `sensor` name: use `"Darrell Watch"` so it is in line with the screenshot (instead of current value `"ESPresense Presence"` which is very generic). Similar for the **node sensor** (`"Dining"` instead of `"Living"`), but that one will be removed from the documentation altogether because of autodiscovery.
- should the `state_topic` for a **beacon** indeed be `espresense/rooms` (as used in the [ESPresense documentation](https://espresense.com/home_assistant)) or should it be the full topic path of the beacon, e.g. [based on Darrell Watch example] `espresense/devices/apple:1007:11-12` (which is how it is used in the [This Smart House video](https://youtu.be/7bfW_6130To?t=996)). The [mqtt_room documentation](https://www.home-assistant.io/integrations/mqtt_room/) says: "The topic that contains all subtopics for the rooms", so I assume the ESPresense documentation is correct (but wanted to double check).

**Comment by DTTerastar** [comment]
The documentation is open source: https://github.com/ESPresense/ESPresense.github.io

Can you hit the edit button and suggest these fixes?
