### ISSUE TITLE
MiBand 6 is a known working trackable beacons???

### ISSUE THREAD

**Issue by maprolim** [ESPresense/ESPresense#184]
MiBand 6 is a known working trackable beacons???

**Comment by DTTerastar** [comment]
I do not own one, but I believe others have seen the MiBand's work.

**Comment by DeekB1983** [comment]
I'm using a Mi Band 6, seems pretty reliable compared to some other devices I have tried

**Comment by yuri-vashchenko** [comment]
I have multiple Mi Band models within my family, from Mi Band 4 to Mi Band 6. None of them showing up.
When I run a BLE scnner app on my phone I can see them all.
Please help

**Comment by gadric** [comment]
You need to active in the MiFit app, that the band should be discoverable. Then it works perfectly for me (MiBand 6)
