### ISSUE TITLE
Clarify how to configure

### ISSUE THREAD

**Issue by Ulrar** [ESPresense/ESPresense#19]
Hi,

This might be silly but I just sat there a bit confused for a minute after flashing my esp32 from my browser, with no idea what the next step is.
Figured it out eventually but it might be worth mentioning on the install page that after flashing it'll create an open network with a config page.

**Comment by DTTerastar** [comment]
Yeah, i totally agree, my documentation needs work :)

**Comment by DTTerastar** [comment]
https://espresense.com/install#2-wifimqtt-setup-on-base-station has some info, does it make sense now?

**Comment by Ulrar** [comment]
Yep, looks good to me ! Thanks
