### ISSUE TITLE
Question on idType: is there information/documentation on ID_TYPE_xx?

### ISSUE THREAD

**Issue by binderth** [ESPresense/ESPresense#193]
Regarding my issue #192 I stumpled across the "`idType`"-attribute, and perhaps I can filter smartPhones on that attribute?

My daughters Apple iPad uses "`ID_TYPE_APPLE_NEARBY`" aka "`idType = 35`" and the Samsungs use "`idType = 11`".
Or is it just coincidence, that the smart phones by chance use `ID_TYPE_MISC` just as all "others"? 

Is there a "human readable" list of idTypes in a documentation of sorts?

Thank you!

**Comment by DTTerastar** [comment]
The reason for that is a single mac can get a few different fingerprints, but some are "better" than others.  ID_TYPE_APPLE_NEARBY is what we get for an iPhone until the Query comes back with the model number, but we could also get a uuid from room assistant app.  So we basically upgrade from one fingerprint type to another as long as the type is greater than the previous type.  It's point would be for the usecase of having a bunch of nodes all getting locations in your house, if one node was using a lower type, it's id should be ignored, and instead use the id from the node that has the higher idType.

**Comment by binderth** [comment]
Thank you!
