### ISSUE TITLE
Encrypted Captive Portal transmissions

### ISSUE THREAD

**Issue by ooktown** [ESPresense/ESPresense#197]
First: GREAT work. I got this running after watching the video and following the steps on the website. It's working with my iPhone, which I was surprised I could get reliably (at least so far) to report my presence on Home Assistant. Nice!

**A request:** When setting up the device using the captive portal, I'd like the transmissions over WiFi to be encrypted, especially if UIDs and Passwords are being transmitted. The portal indicates that these will be sent without encryption, so I'm assuming that means it can be captured as clear-text if someone is snooping. Not that this is likely, but it would make me feel better that it's being encrypted.

**Comment by lolorc** [comment]
wont fix ?
that's a really important feature.
