### ISSUE TITLE
Update documentation and Readme 

### ISSUE THREAD

**Issue by the-mentor** [ESPresense/ESPresense#2]
We need to bring the documentation up to date.

**Comment by DTTerastar** [comment]
I did some work on the Readme.

**Comment by michaeldvinci** [comment]
Hey guys, this is some great work! I've got it all up and running cross 5 esp32 dev kits in my apartment. Is there an easy way to determine which device id goes to which physical device? i.e. 'apple:0c0e:18-9'. I tried comparing wifi / bt macs to the 4 alphanumeric in the middle, but didn't see anything that matched up

**Comment by DTTerastar** [comment]
Done: https://espresense.com
