### ISSUE TITLE
Fingerbot integration

### ISSUE THREAD

**Issue by maprolim** [ESPresense/ESPresense#207]
Integration with [Fingerbot](https://kelbin.medium.com/fingerbot-by-adaprox-review-54e945fcceb0), that is a very useful device with a limitation: Works only with Bluetooth.

The idea is to permit that the user can connect and operate his/her fingerbots through ESPresense Base Station, controlling using Home Assistant.

**Comment by DTTerastar** [comment]
I'm going to close this because keeping a ble connection active to a device while also trying to scan and query other ble devices would be way too much. Tasmota has a version that can do this I believe as well.
