### ISSUE TITLE
100% QryErr immediately after enabling query

### ISSUE THREAD

**Issue by Zipties** [ESPresense/ESPresense#214]
**Describe the bug**
When Query is enabled the log immediately reports every device with an error, and stops responding to "close" and "left". The issue does not go away with power cycles. 

**Expected behavior**
occasional errors

**Hardware Details**
I have ESPresense running on 5 ESP32. One is a HiLetgo model the others are Atom M5s. I get the exact same behavior on all of them.

The household has 2 iPhones, 2 apple watches, a macbook, an apple tv, ipad, and airpods

The 

**Config**

- [x ] Active Scan enabled (tried on and off)
- [x ] Query enabled
- Max Distance 5.0

**Logs**
https://pastebin.com/VtjLnnFx

**Comment by DTTerastar** [comment]
Turning off this logging has been requested but denied: https://github.com/h2zero/NimBLE-Arduino/issues/299#issuecomment-934597330

**Comment by Zipties** [comment]
> Turning off this logging has been requested but denied: [h2zero/NimBLE-Arduino#299 (comment)](https://github.com/h2zero/NimBLE-Arduino/issues/299#issuecomment-934597330)

The feature does not work at all for me though, once it is enabled all devices will time out and report not_home. Is it recommended to not use the query feature at this time?

**Comment by DTTerastar** [comment]
The id changes when it's turned on.  Instead of seeing a generic id, turning on query makes it use an id that has the model number in it and/or room assistant.  In the log I see MAC: 65137ef92a16 never got a response most likely because it's too far away from the node.  But I DO see MAC: 5de06e2f3532 got a response and switched to a different id.

**Comment by DTTerastar** [comment]
What is needed is a hive mind mode where all the nodes intelligently issue query commands from closer nodes, and all nodes use the new id.  Know any c++?

**Comment by Zipties** [comment]
> Know any c++?

Sorry, I am just an end-user im afraid. It does not seem to be a distance issue though, pressing a device against the ESP32 will no longer trigger the "close" message after the errors start rolling in in Qrry mode...until it is rebooted and it will work for a few more minutes. The above log is shortly after turning it on and stops as it becomes unresponsive I can provide a longer one if needed.

> What is needed is a hive mind mode where all the nodes intelligently issue query commands from closer nodes

Is that how Room-Assistant works?

**Comment by DTTerastar** [comment]
Room assistant doesn't query for model number, but it does have an app that we can also use to assign a guid to a device.

**Comment by Zipties** [comment]
> Room assistant doesn't query for model number, but it does have an app that we can also use to assign a guid to a device.

Yeah I have been playing with the app. It seems to randomly stop broadcasting, and I don't think it has an apple watch component that I can tell.

**Comment by DTTerastar** [comment]
It definitely doesn't stay running 100%...  And yes, no apple watch.

**Comment by Zipties** [comment]
Is there a way to detect any watch or phone in a room with less overhead, without caring which device it is specifically?

**Comment by DTTerastar** [comment]
If you turn on the covid contact tracer apps you can get exp:20 ids and count them.

**Comment by Zipties** [comment]
> If you turn on the covid contact tracer apps you can get exp:20 ids and count them.

but again, no watch right?

What if anything would need to change if multiple devices were reporting the exp:20 ID to home assistant? Wouldn't that cause flip flopping issues?

**Comment by DTTerastar** [comment]
Yes, mqtt_room would be unhappy with that, but we could make something that counts the same id with different macs.  It could count up all the "kinds" of things, watches, phones, laptops, and a total count.

**Comment by Zipties** [comment]
I have also noticed that even with query off, thumbprints will start randomly working for some devices, even days later. I set up my girlfriends, and my apple watches a couple of days back but they stopped working shortly after disabling query. But, they pop back up and work great for a couple of hours every day still using the apple:1005:9-24 / 9-26 thumbprints
