### ISSUE TITLE
Known issues with Apple Watch?

### ISSUE THREAD

**Issue by oskarax** [ESPresense/ESPresense#215]
Hi, 

Im having issues with my apple watch not becoming "not_home" it goes from 4-8 meters in the distance even though the Apple Watch is turned off.

Using the default settings.

**Config**

- [ ] Active Scan enabled
- [ ] Query enabled

**Comment by DTTerastar** [comment]
You may have multiple apple watches all using the same id?  Check the mac addresses and see if they keep switching back and forth.  That means you're seeing 2 or 3 devices under the same id.

**Comment by PDekker** [comment]
> You may have multiple apple watches all using the same id? Check the mac addresses and see if they keep switching back and forth. That means you're seeing 2 or 3 devices under the same id.

Is there a solution to this? My wife and I both have the same Apple Watch model. Her's is smaller though.
