### ISSUE TITLE
Putty serial not displayed correctly

### ISSUE THREAD

**Issue by Papi77** [ESPresense/ESPresense#230]
**Describe the bug**
When connected through putty the lines in terminal are displayed shifted.

**Expected behavior**
Text in putty terminal should be formatted correctly

**Hardware Details**
ESP32-WROOM, Windows 10 PC.

**Config**

Putty configured with:
- Baud speed: 115200
- Data bits: 8
- Stop bits: 1
- Parity: none
- Flow control: XON/XOFF

**Logs**
If possible, copy and paste any logs from the serial monitor from the time that you see the bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/26800136/153266523-8e04680b-2744-41fb-90b1-5572f161c8ab.png)

**Comment by wabit** [comment]
Try setting implicit CR in putty's settings their documentation explains it well
[puttydocs](https://documentation.help/PuTTY/config-crlf.html#:~:text=3%20'Implicit%20CR%20in%20every%20LF'&text=The%20CR%20character%20makes%20the,might%20make%20the%20screen%20scroll).)

**Comment by Papi77** [comment]
Thanks, yes that seems to fix the issue with putty!
