### ISSUE TITLE
Version: v2.0.17 Temperature sensors gone

### ISSUE THREAD

**Issue by rene-bayer** [ESPresense/ESPresense#242]
**Describe the bug**
Since the latest update it's not possible to configure temperature sensors anymore

**Expected behavior**
configure temperature sensors (DHT11, DHT22)

**Hardware Details**
Lolin32 & DHT22

**Config**

- [x] Active Scan enabled
- [x] Query enabled

**Logs**
NaN

**Screenshots**
![image](https://user-images.githubusercontent.com/11734245/153546318-cf6c5fee-81e7-41ac-95b4-2643c7edd23e.png)
![image](https://user-images.githubusercontent.com/11734245/153546334-dd004174-3dbf-437c-a45e-0111205bf935.png)

**Comment by Novocaine85** [comment]
Same for me. Got 3 around my house and none is working anymore.

**Comment by rene-bayer** [comment]
@Novocaine85 Don't know why, but there's a separate version to use with sensors now: [https://github.com/ESPresense/ESPresense/releases](https://github.com/ESPresense/ESPresense/releases)
