### ISSUE TITLE
HiLetGo ESP-32S Configuration Portal Not Working

### ISSUE THREAD

**Issue by ZeddicPrime** [ESPresense/ESPresense#243]
**Describe the bug**
I purchased 3 ESP-32S devices. When I first power them on and use the web tool to flash them with 2.0.17, they seem to boot up. I can configure Wifi and mqtt settings, but I don't see any data reaching the mqtt broker. In troubleshooting mqtt, I re-flashed the firmware (using the website with the Clear option checked). As soon as I flash the device a second time, the default portal at 192.168.4.1 times out in the web browser. This happened with all three ESP32s I have to test with.

**Expected behavior**
ESP32 boots consistently after multiple flashes.

**Hardware Details**
Product: HiLetgo ESP-WROOM-32 ESP32 ESP-32S Development Board 2.4GHz Dual-Mode WiFi + Bluetooth Dual Cores Microcontroller Processor Integrated with Antenna RF AMP Filter AP STA for Arduino IDE

**Logs**
Here's the terminal output after re-flashing the firmware.

> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0018,len:4
> load:0x3fff001c,len:1044
> load:0x40078000,len:8896
> load:0x40080400,len:5828
> entry 0x400806ac
> Connecting to WiFi (30:C6:F7:0B:56:08)...
> First contact!
> 
> Starting access point for confi�uration portal.
> SSID: 'espresense-08560b'
> I

Several minutes later when I disconnected and reconnected the terminal I see the last line loaded more, but no change in behavior:
> IP: 192.168.4.1

About 20 minutes later I see the following additional log entries immediately following:

> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> ets Jun  8 2016 00:22:57
> 
> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0018,len:4
> load:0x3fff001c,len:1044
> load:0x40078000,len:8896
> load:0x40080400,len:5828
> entry 0x400806ac
> Connecting to WiFi (30:C6:F7:0B:56:08)...
> First contact!
> 
> Starting access point for confi�uration portal.
> SSID: 'espresense-08560b'
> I

Additional flashes, switching to a different browser or device to connect to the configuration portal do not seem to help

Edit: I forgot to mention that the wifi SSID seems to become unstable after experiencing this bug. My computer and phone lose their connection after a few minutes of connecting to the espresense-08560b SSID

**Comment by ZeddicPrime** [comment]
I've done more testing with 2.0.19 and am generally seeing the same thing. Sometimes the log output shows a little more detail, but the config portal won't fully load and the ssid disconnects after about 10-30 seconds. On every 3rd attempt or so I can get the config page to load the first few lines: The "Restart device" button shows, the word Configuration, and the text "WiFi network name (SSID):
Scanning for WiFi networks..."
but nothing else on the page loads and about the time I press the refresh button is usually when the wifi connection drops.

> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0xee
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0018,len:4
> load:0x3fff001c,len:1044
> load:0x40078000,len:8896
> load:0x40080400,len:5828
> entry 0x400806ac
> Connecting to WiFi (30:C6:F7:0B:56:08)...
> First contact!
> 
> Starting access point for configuration portal.
> SSID: 'espresense-08560b'
> IP: 192.168.4.1
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> [E][WebServer.cpp:633] _handleRequest(): request handler not found
> 7 WiFi networks found.
> ets Jun  8 2016 00:22:57

**Comment by DTTerastar** [comment]
Can you try flashing ESPHome or WLED on this board and see if it also has oddities?  I do have 1 device which has a 41mhz crystal instead of a 40 and it has wifi/stability issues, especially after running for a couple minutes.

**Comment by ZeddicPrime** [comment]
I haven't had a chance to follow up testing with regular ESPHome.

I still feel like there's something else going on besides the crystal frequency because on the first flash the HiLetGos were working - it was only after flashing a second time that they quit being able to load the config portal. I don't have more of them to further investigate though.

I did get 3 other ESP32s and so far they seem to be much more reliable with regards to this specific issue. But also I haven't needed to flash these more than once. New ones:
Teyleten Robot ESP32S ESP32 ESP-WROOM-32 Development Board 2.4GHz Dual-Core WiFi +Bluetooth 2 Function Microcontroller for Arduino (ESP32 30P, 3PCS)

**Comment by DTTerastar** [comment]
This seems like flaky hardware.  Closing.
