### ISSUE TITLE
Home Assistant companion app iBeacon isn't detected

### ISSUE THREAD

**Issue by erbmur** [ESPresense/ESPresense#251]
I have a couple esp32's set up around the house.  They are picked up a while bunch of apple devices (which I don't own), but it doesn't appear to be detecting either mine or my wifes android phone.  I have the HA companion app installed and the iBeacon from there isn't being detected either.
I installed beacon simulator and set up an ibeacon on that which is being picked up by the esp's.
Is there something specific I have to do to have the beacon from the HA companion app detected?  I know it's working with a separate app, but I would rather not have extra apps installed on the phones if I can help it.

**Comment by DeekB1983** [comment]
Have you set the power to high?

**Comment by erbmur** [comment]
I was unable to find any options within the companion app to turn BLE on/off or anything to do with power levels.
I found something on the home assistant website that allows turning it on and off via a notify command.
Is there somewhere in the HA companion app settings you can point me to that would allow me to make the adjustments?

**Comment by erbmur** [comment]
LIFESAVER!

**Comment by bachoo786** [comment]
> Go into the companion app, go to manage sensors, then Bluetooth sensors, then into Bluetooth transmitter, enable the setting and then scroll to sensor settings at the bottom.
> 
> You will find 2 settings, advertise mode and transmitter power.
> 
> Set transmitter power to high Set advertise mode to 10Hz low latency
> 
> These settings are working well for me on my Samsung galaxy z fold 3
> 
> ![SmartSelect_20220212-205027_Home Assistant](https://user-images.githubusercontent.com/64811870/153728157-cb23d58a-0e41-4e5c-97b3-3dadf3a4e804.jpg)

oh I wish this worked for me I have been struggling with my HA companion app on my Samsung Galaxy S20+ and my entity in HA says unavailable. 

I tried your setting and I still have the same issue.

**Comment by DTTerastar** [comment]
The only other thing is sometimes HA companion broadcasts with such a low power max distance kicks in and hides it.  Set max distance to 0 to be sure it's not being excluded.

**Comment by bachoo786** [comment]
> I'd bet you have them under iBeacon:*
> 
> Can you show what MQTT explorer sees?

sorry how do I show what the MQTT explorer sees?

**Comment by bachoo786** [comment]
> Contributor

ok 

> I'd bet you have them under iBeacon:*
> 
> Can you show what MQTT explorer sees?

ok just checked my MQTT explorer app and you are correct it is seen there, please see screenshot below:

![image](https://user-images.githubusercontent.com/6251030/161277551-de346fff-e7c7-4a90-b5ef-8cc6acf53eef.png)

**Comment by DTTerastar** [comment]
So you just need to configure the id as the full iBeacon:exxxx100-1 in home assistant and it'll work.  The documentation is a little out of date on this.  It shows it without the type: prefix.  You gotta use the whole id.

**Comment by bachoo786** [comment]
> 

OMG Thank you ever so much it bloody works !!!

Amazing Thank you !!!

I have another question how can I make the system to detect my phone quickly? currently there is a delay of 5 to 10 seconds.

**Comment by DTTerastar** [comment]
On your screenshot there is one more value to the right.  Interval.  What is it?  That's how often we're seeing beacons in ms.

**Comment by bachoo786** [comment]
> On your screenshot there is one more value to the right. Interval. What is it? That's how often we're seeing beacons in ms.

its the interval value and it ranges from 4800 to 5100

**Comment by bachoo786** [comment]
Is there a way to increase from 5 seconds to 1 second?

Also I have set up 4 espresense and the issue I am facing is that when I am in a room say office which has 1 espresense installed, it sometimes says I am in the kitchen where there is another espresense installed. 

How can I resolve this and make it accurate?

Thanks again :)

**Comment by DTTerastar** [comment]
The update interval is a setting in home assistant companion app.

**Comment by bachoo786** [comment]
> The update interval is a setting in home assistant companion app.

Ok thanks for that. How about the distance? 

Basically I have my base station in my office and the rooms next door do not have a base station. Whenever I walk into the rooms next to the office, the signal is picked up as I am in the office but clearly I am not. Is there a way where I could make sure it detects me when I am in the office only and not near the office?

**Comment by DTTerastar** [comment]
You can tweak the maxDistance to decrease the radius in which the base station will report.  You can reposition the base station to be further away from the area you don't want to report in.  Ultimately I want to run all the distances through some machine learning to make it more precise but baby steps first...

**Comment by bachoo786** [comment]
> You can tweak the maxDistance to decrease the radius in which the base station will report. You can reposition the base station to be further away from the area you don't want to report in. Ultimately I want to run all the distances through some machine learning to make it more precise but baby steps first...

That would be amazing 👏 
I remember you mentioned to keep the maxDistance as 0 when the power is set to high as the HA app doesn't transmit it correctly ?

**Comment by DTTerastar** [comment]
Sure if you're NOT seeing devices set it to 0.  But here you're see too many devices, so set it to a value that works for your house.

**Comment by bachoo786** [comment]
> Sure if you're NOT seeing devices set it to 0. But here you're see too many devices, so set it to a value that works for your house.

Ok great makes sense. How about the factor for absorption? Default is 3.5. I have seen when I play with the value and decrease it my results change drastically.

**Comment by DTTerastar** [comment]
https://espresense.com/configuration/settings#calibration

> Factor used to account for absorption, reflection, or diffraction - An average value that accounts for the amount of “stuff” in between rooms in your house. Use a higher number for dense materials, lower for assuming no walls.

**Comment by bachoo786** [comment]
> https://espresense.com/configuration/settings#calibration
> 
> > Factor used to account for absorption, reflection, or diffraction - An average value that accounts for the amount of “stuff” in between rooms in your house. Use a higher number for dense materials, lower for assuming no walls.

Well ESPresense is amazing but to be very honest with you it's very difficult to get the distances correct for each base station I tried it many times with different settings using the ble transmitter from the HA Companion app.

I wish there was a simpler way to make the distances defined on the settings page to just work and not show I am in the room on the floor below whilst in reality I am on the 1st floor or 2nd floor.
