### ISSUE TITLE
DHT22 Not working after update

### ISSUE THREAD

**Issue by Novocaine85** [ESPresense/ESPresense#258]
**Describe the bug**
DHT22 Is not working after 2.0.19 update (showing NaN as result instead)

**Expected behavior**
Expected to work as previous version.

**Hardware Details**
Unrelated
**Config**

See attachments

**Logs**
Can't do it right now as I'm not home. I'll do it asap.

**Screenshots**
![Screenshot_2022-02-13-18-30-14-307_com android chrome](https://user-images.githubusercontent.com/7164237/153767119-a5bad23e-2424-4ec3-9578-bbab4fd2689e.jpg)
![Screenshot_2022-02-13-18-30-18-610_com android chrome](https://user-images.githubusercontent.com/7164237/153767120-49e4ee17-d80b-4403-ab2c-1812fa7880c9.jpg)
![Screenshot_2022-02-13-18-30-39-715_com android chrome](https://user-images.githubusercontent.com/7164237/153767121-4125978a-7f59-4d81-a8f5-0834e3759964.jpg)
![Screenshot_2022-02-13-18-33-27-626_io homeassistant companion android](https://user-images.githubusercontent.com/7164237/153767174-ef0b4ac8-6f98-4e1c-a7f4-724ea792abb9.jpg)

**Comment by Novocaine85** [comment]
Apparently power cycling the devices did the trick. However on serial logs i can see "invalid i2c address" even if is disabled.

**Comment by DTTerastar** [comment]
@ShonP40 Can you help?

**Comment by ShonP40** [comment]
I'll get on my PC in about 30 min and check it

**Comment by DTTerastar** [comment]
@Novocaine85 can this be closed?
