### ISSUE TITLE
Id gets generated new on every addition of esp32 devices

### ISSUE THREAD

**Issue by skycryer** [ESPresense/ESPresense#27]
**Describe the bug**
Not sure if that is a bug or expected behaviour or if I understand it wrong but it looks like the ID for the devices are getting new generated every time I add a esp32 with ESPresesense to my network.

**Expected behavior**
ID should stay the same after first install. Maybe devices can share the IDs they have generated so a new added device is not generating new IDs.

**Extra Info**
Maybe you can add a forum Post on Home assistant forum or somewhere else for easier clarification of functionality so we can easy share knowledge. Asking things like this in a forum could make it easier to keep the bug/enhancement section clean.

**Comment by DTTerastar** [comment]
Good idea: https://github.com/ESPresense/ESPresense/discussions/categories/help-with-fingerprinting
