### ISSUE TITLE
Samsung Galaxy S10 keeps getting a new ID

### ISSUE THREAD

**Issue by GaWr26** [ESPresense/ESPresense#280]
![Screenshot 2022-02-15 at 11 55 57](https://user-images.githubusercontent.com/1381617/154048971-81fba08e-e2a2-4ba7-8847-213ee7ece291.png)

As you can see in the Screenshot my Galaxy S10 keeps getting a new ID. 
Any Idea on how to fix this? Is this an issue with my phone or am I missing something?

Cheers

**Comment by GaWr26** [comment]
Figured this out. It's an obvious security feature and I need an App:
_Both Android and iPhone use a strategy of Bluetooth MAC address randomization for privacy. While this may not be a perfect solution, it means that the publicly-available bluetooth MAC address of your phone won’t be consistent to devices with which it has not been paired. As we’re using Bluetooth Low Energy to scan, we don’t want to pair the device. Thus, the need for an app to allow us to track, except for the 2 options below._

**Comment by matigda123** [comment]
Is there any new solution for that issue ?

**Comment by DTTerastar** [comment]
<https://espresense.com/beacons/apps> has all the info.  You do need an app on android.
