### ISSUE TITLE
espresense not automatically updating 

### ISSUE THREAD

**Issue by jimmyeao** [ESPresense/ESPresense#291]
**Describe the bug**

espresense not automatically updating - have tried restarting the device several times (including cold boot)
**Config**
![image](https://user-images.githubusercontent.com/5197831/154279162-7f33f154-ad5a-4761-91c2-e46c02daad0d.png)

- Version:ESPResense Version: v2.0.26
- Active scan enabled: No
- Include filter: None
- Exclude filter: None
- Query filter: None

**Hardware**

- Firmware flavor:
- Device (be specific): ESP32

**Logs**

No logs, device hard to reach

**Comment by cbhiii** [comment]
Same - v2.0.26 kept them all in a reboot so they aren't checking for the latest version.

**Comment by hellcry37** [comment]
this is solved in later versions you can close the issue
