### ISSUE TITLE
Add RGB light support

### ISSUE THREAD

**Issue by chrisron95** [ESPresense/ESPresense#297]
**Is your feature request related to a problem? Please describe.**
Considering I have one of these in each room, I'd love if I could add an RGB LED to my esp32 so that I could control it through Home Assistant for things such as notifications.

**Describe the solution you'd like**
Since several sensors have been added recently, I'm wondering if it would be possible to include support for an RGB LED such as WS2812B. Personally, I only want a single pixel so I don't need support for multiple pixels. ESPHome offers FastLED Clockless that looks like it would accomplish everything if it's possible to implement here: https://esphome.io/components/light/fastled.html

**Describe alternatives you've considered**
Alternatives would be either to have no status light in each room, or to add an additional esp device to each room for a status light.

**Additional context**

**Comment by laemen** [comment]
Please also add support for the SK6812 RGB led on the [M5 Pico Stamp](https://docs.m5stack.com/en/core/stamp_pico)

**Comment by DTTerastar** [comment]
Yes, we should also support multiple led strips since this has 2: https://t.co/9kLrbhq0RI

**Comment by strid3r21** [comment]
This is something I'm very interested in as well. It would be a really handy feature to have to be able to flash different colors to an RGB LED on the ESP32 for various notifications.
