### ISSUE TITLE
v 2.0.28 Reboot Loop on Query

### ISSUE THREAD

**Issue by Zipties** [ESPresense/ESPresense#301]
If I try and query specific apple devices on the new build it crashes with. It also seems that it is trying to query everything again if anything is in the query field 

```
1 Query | MAC: c869cd15bcbd, ID: apple:1005:9-12                                              rssi -77
lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
1 QryErr| MAC: c869cd15bcbd, ID: apple:1005:9-12                                              rssi -77, try 3, retry after 5000ms
[E][main.cpp:252] onMqttDisconnect(): Disconnected from MQTT; reason 0

[E][main.cpp:14] sendTelemetry(): Error sending status=online
CORRUPT HEAP: Bad tail at 0x3ffdd094. Expected 0xbaad5678 got 0x3ffdd0b0
abort() was called at PC 0x40086cdd on core 1

ELF file SHA256: 0000000000000000

Backtrace: 0x4008f658:0x3ffde110 0x4008f8d5:0x3ffde130 0x40086cdd:0x3ffde150 0x40086e09:0x3ffde180 0x40126533:0x3ffde1a0 0x4011ffd9:0x3ffde460 0x4011ff45:0x3ffde4b0 0x400943ed:0x3ffde4e0 0x40081e6e:0x3ffde500 0x40086bd5:0x3ffde520 0x4000bec7:0x3ffde540 0x401a9cfd:0x3ffde560 0x400d301d:0x3ffde580 0x400d7099:0x3ffde5a0 0x400908e6:0x3ffde620

Rebooting...
ets Jun  8 2016 00:22:57
```

**Comment by duceduc** [comment]
I do notice if I try to query the friendly names (apple:iphone10-3), it crashes/reboots quite a bit. But if I leave those query boxes empties, hardly any crashes. Just random mqtt disconnects.

    [E][main.cpp:252] onMqttDisconnect(): Disconnected from MQTT; reason 0

    [E][main.cpp:14] sendTelemetry(): Error sending status=online
    0 Reconnect timer
    0 Reconnecting to WiFi...
    Connecting to WiFi SSID 'prune_dwarf'...............................192.168.1.164
    0 Reconnecting to MQTT...
    0 Reconnect timer
    0 Reconnecting to MQTT...

The distance seems more stable. It doesn't jump around as much like previous versions. 
![2022-02-17_9-38-17](https://user-images.githubusercontent.com/20457723/154381721-4cb14796-57eb-4660-8de0-a016fdab5cc9.jpg)
