### ISSUE TITLE
.28 rock solid but less devices

### ISSUE THREAD

**Issue by casaerreti** [ESPresense/ESPresense#303]
Hi guys,

fresh install to .28 on a ESP32 Wroom32. Been rock solid since then but I see (in MQTT Explore) way less devices than .26 and .27.

All the miband (3) are one. All the ble Filo Tag (3) are gone. All my neighbours devices are gone. The only trusty is ibeacon from HA app companion that is quite fast and reliable. 

**Config**

- Version: ESPResense Version: v2.0.28
- Active scan enabled: yes
- Include filter: - 
- Exclude filter: -
- Query filter: -

**Hardware**

- Firmware flavor: esp32
- Device (be specific): azdelivery wroom32

**Comment by DTTerastar** [comment]
.29 is out and I think it may fix this  Can you test it?
