### ISSUE TITLE
tile not recognized

### ISSUE THREAD

**Issue by sv3n5** [ESPresense/ESPresense#304]
my tile is no longer recognized, is this normal? or am I doing something wrong?

**Comment by casaerreti** [comment]
If you are on .28 is a known issue. see other posts

**Comment by DTTerastar** [comment]
Has .29 made this better for you?

**Comment by sv3n5** [comment]
> Has .29 made this better for you?

still not recognizing my tiles. running another ESP on .15 and there it works great.

**Comment by xwox** [comment]
Autoupdate to 2.0.29 on 7 ESP32 devices:
No, it still does not work. Only Apple devices are recognized.
MiBand and Samsung watch are not visible in MQTT.
Everything worked well prior to 2.0.26

**Comment by FlingersDH7** [comment]
same with gigaset G-tag beacon. Only Apple devices are recognized. 2.0.29 did not solve it

**Comment by FlingersDH7** [comment]
Issue solved with 2.0.31. Thanks
