### ISSUE TITLE
Disabling unused sensors

### ISSUE THREAD

**Issue by simonyel** [ESPresense/ESPresense#310]
Is there a way to disable TSL2561 and BME280 integrations when not used?

**Config**
- Version: 2.28
- Active scan enabled: YES
- Include filter:
- Exclude filter:
- Query filter:

**Hardware**
- Firmware flavor: esp32-sensors
- Device (be specific): ESP-WROOM-32

**Logs**
Logs are flooded with about 10 per second
[TSL2561] Invalid (or not configured) I2C address - Disabling integration
[BME280] Invalid (or not configured) I2C address - Disabling integration

**Screenshots**
![image](https://user-images.githubusercontent.com/30694967/154740243-a3482b38-2229-4979-afd7-95a3c59e03b5.png)

**Comment by ShonP40** [comment]
It doesn’t start those integrations if you don’t have the correct I2C addresses set

I’ll open a PR to remove those log messages though
