### ISSUE TITLE
Request MQTT password hidden - (password:******)

### ISSUE THREAD

**Issue by gmanc2019** [ESPresense/ESPresense#313]
As a User of ESPresence, I [want to] have improved security associated with the MQTT password within the ESPresence web UI, [so that] the password is not left in plain text.

This prevents other having access to passwords/accounts being directly exposed to other users of the network.
Feels more secure. I know the password for wifi is hashed/blanked/starred out after submission.

![hidden_mqtt_password](https://user-images.githubusercontent.com/58784626/154774539-ebd8e177-d9b0-4e85-bc41-88184af21332.png)

**Comment by ChirpyTurnip** [comment]
I concur.....+ sharing config is best done with a screenshot....which is not cool if there's a password there...  :-(

**Comment by skotl** [comment]
Agreed, although I'd go further and suggest that there is no reason for the config page to expose the password at all. I'd suggest it just has static "******" content that, when overwritten, updates the password.

This wouldn't be as much of an issue if access to the espresence page was encrypted / authenticated, but having it just out there is a pretty easy hack for anyone getting onto the wifi.

**Comment by cryptedx** [comment]
Please please hide the password from the WebUI! Thank you so much! :-)

**Comment by DTTerastar** [comment]
Please test v2.2.1b5

**Comment by DTTerastar** [comment]
This has been released.
