### ISSUE TITLE
Option to invert PIR signal

### ISSUE THREAD

**Issue by ahWorkShop** [ESPresense/ESPresense#326]
I have Bosch PIR (model isc-bpr2-w12). In the Bosch environment when the circuit is opened, that signals movement was detected. Which seems to be the opposite of other PIR sensors. With the Bosch connected to ESPresense, when there is no movement the entity shows as movement detected and when there's movement its displayed as clear.

An option to configure how the PIR signal works in ESPresense or to change the MQTT payload would be helpful for these and other types of PIRs.

**Comment by DTTerastar** [comment]
I was thinking we could allow for negative number input and when it's negative invert it.

**Comment by rcmurphy** [comment]
Would love to see this implemented!

> I was thinking we could allow for negative number input and when it's negative invert it.

@DTTerastar as long as pin 0 isn't supported!
