### ISSUE TITLE
How to configure automation

### ISSUE THREAD

**Issue by nijez** [ESPresense/ESPresense#339]
I have now successfully added to HomeAssistant, how should the automation be configured?

**Comment by ChillingSilence** [comment]
There's literally two guides on the front page of the website in the form of videos, the EverythingSmartHome one (2nd currently) shows how you should expect to use them

**Comment by DTTerastar** [comment]
This is how one person used it: https://blog.briancmoses.com/2022/03/espresense-easy-room-detection-for-home-assistant.html
