### ISSUE TITLE
Automatically query for Room Assistant iOS beacon id using manufacturer data

### ISSUE THREAD

**Issue by ronaldheft** [ESPresense/ESPresense#354]
**Is your feature request related to a problem? Please describe.**
Tracking iPhones has been a struggle, and even with querying for the Room Assistant beacon id by placing Apple identifiers in the query box, that doesn't seem to always work (Room Assistant will see my phone but ESPresense will not). I'm not sure if my Apple identifier is moving constantly, or it's due to the large number of iPhones in my area with colliding device ids (I live in an apartment).

**Describe the solution you'd like**
Thankfully, there appears to be a solution. When the Room Assistant Companion is running on an iPhone, there is extra manufacturer data in the BLE advertisement that can be used to identifier if the device has a Room Assistant identifier. You can see an example in the Room Assistant source code here: https://github.com/mKeRix/room-assistant/blob/main/src/integrations/bluetooth-low-energy/bluetooth-low-energy.service.ts#L482

Room Assistant is looking for Apple manufacturer ids that have the extra bits before deciding to query for the extra service characteristics. It looks like the [4th bit of the 3rd byte of the manufacturer data should be a 1](https://github.com/mKeRix/room-assistant/blob/1a7f579cddee3bddb74cc8c0ac73e05ba0969879/src/integrations/bluetooth-low-energy/bluetooth-low-energy.service.ts#L596) on devices with the Room Assistant companion. [There is also a function that is used to extract the extra manufacturer data](https://github.com/mKeRix/room-assistant/blob/1a7f579cddee3bddb74cc8c0ac73e05ba0969879/src/integrations/bluetooth-low-energy/bluetooth-low-energy.service.ts#L578). (More info on how this works: http://www.davidgyoungtech.com/2020/05/07/hacking-the-overflow-area)

My thinking is instead of placing a device id in the query box to have ESPresense scan for the Room Assistant identifier, it could automatically do it if it sees this special bit in the BLE advertisement. This would cut down on the number of devices queried when there are lots of iPhones with colliding identifiers and it can be determined with the passive BLE advertisement.

**Describe alternatives you've considered**
Not everyone may want ESPresense automatically querying iPhones if this identifier is present, so maybe it's put behind a configuration option. Another option could be placing the identifier "roomassistant" in the query box to allow ESPresense to query devices with this extra manufacturer data.

**Comment by DTTerastar** [comment]
I know it's not documented well but we actually already do this.  If you install the app you should see the ID change to something that starts with roomAssistant:

**Comment by ronaldheft** [comment]
@DTTerastar Without placing anything in the "Query device ids for characteristics" field? I have not observed that behavior. I've had to track down the device id and add it to that list for the `roomAssistant` identifier to appear.

**Comment by ronaldheft** [comment]
Hmm, actually scratch that. It seemed the Room Assistant app had stopped broadcasting the identifier. I restarted it and I think it may have worked without adding anything in query field. I'll report back in an hour or so to confirm it's held stable.

**Comment by DTTerastar** [comment]
> Hmm, actually scratch that. It seemed the Room Assistant app had stopped broadcasting the identifier. I restarted it and I think it may have worked without adding anything in query field. I'll report back in an hour or so to confirm it's held stable.

Yeah I believe that iOS when it backgrounds the app it stops broadcasting the meta-data as often. I do honored if I see it. In my own config I've added it to query so that it works 100% of the time.

**Comment by ronaldheft** [comment]
So it seemed to work for a bit without anything in the query box, but as soon as my phone's mac address changed, it stopped. Room Assistant is still chugging along just fine. I tried restarting my ESPs (I have three) and none of them have picked up the `roomAssistant` identifier yet. One of my ESP is right next to one of my Pis and I am currently 5 feet from it.

Here's the last three hours:
<img width="381" alt="Screen Shot 2022-03-01 at 3 14 22 PM" src="https://user-images.githubusercontent.com/1143112/156242152-e04504ce-9c27-40cd-9427-decccefd0bac.png">

If I look at my MQTT server, I can see my phone with a generic identifier, but nothing is coming back with roomAssistant. I also tried playing with turning active scanning on and off.

Any ideas on things to try?

**Comment by DTTerastar** [comment]
Can you tell via a BLE scanner if room assistant is still advertising?

**Comment by ronaldheft** [comment]
Yes, here is the Room Assistant service characteristic on my phone (using Bluetility).
<img width="593" alt="Screen Shot 2022-03-01 at 3 22 25 PM" src="https://user-images.githubusercontent.com/1143112/156243260-16415229-0d0b-4f9d-a1e0-aa7b8805f39f.png">

Here is the manufacturer id:
<img width="261" alt="Screen Shot 2022-03-01 at 3 23 18 PM" src="https://user-images.githubusercontent.com/1143112/156243316-a531e757-1560-412d-b0e8-43785fe25a70.png">

**Comment by DTTerastar** [comment]
Very weird, I have ble device that can hook to wireshark, i'll try that and see if it stops or if it's my code that's broke.

**Comment by ronaldheft** [comment]
Thanks for taking a looking. I'm reading over the source code, and it looks like roomAssistant [may only be recognized if the iPhone is advertising its services](https://github.com/ESPresense/ESPresense/blob/fdd38947e656dd4081d6e7ca04cf5868e79b334d/lib/BleFingerprint/BleFingerprint.cpp#L95). I don't think the iPhone is always advertising services on a passive advertisement and only does so when queried, hence why Room Assistant is using the manufacturer string workaround.

**Comment by DTTerastar** [comment]
Oh have you tried Active?  That might be the difference.

**Comment by DTTerastar** [comment]
We could make active more dynamic and only turn on for a bit after seeing a new device advertise.

**Comment by ronaldheft** [comment]
> Oh have you tried Active?  That might be the difference.

Turned on active. No difference. It is occasionally finding my phone again, but Room Assistant has remained stable on finding my phone the whole time.

Maybe it's getting hung up on a previous MAC and is struggling to switch?

![image](https://user-images.githubusercontent.com/1143112/156273574-32764abb-b972-4d4d-a3e5-9d1840daa83c.png)

**Comment by DTTerastar** [comment]
Room assistant you need to provide the hardware mac, right?  Doesn't it just query that every time?  That mac doesn't change as well.  That's cool, but it goes against the passive listening... But query does go against it as well, so maybe that's a better way.  At least that way doesn't have to requery every 20 minutes.

**Comment by ronaldheft** [comment]
Just loaded up the pre-release. No luck in finding the roomAssistant id without placing the device id in the query list.

I added my iPhone to the query list and I saw this message a few times, and then it eventually found the roomAssistant id.
```
[10:42:08]1 Query | MAC: 5e65e73f20cc, ID: apple:1007:11-7                                              rssi -61
[10:42:09]lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
[10:42:09]E NimBLEClient: "Connection failed; status=574 "
```

I will report back a little later the stability of putting the device id in the query box.

**Comment by ronaldheft** [comment]
Looks like I'm also getting some crashes with the prerelease:
```
[10:47:16]abort() was called at PC 0x401aa6eb on core 1
[10:47:16]
[10:47:16]ELF file SHA256: 0000000000000000
[10:47:16]
[10:47:16]Backtrace: 0x4008f670:0x3ffe6590 0x4008f8ed:0x3ffe65b0 0x401aa6eb:0x3ffe65d0 0x401aa732:0x3ffe65f0 0x401a9e0b:0x3ffe6610 0x401aa142:0x3ffe6630 0x401af33d:0x3ffe6650 0x401af4b2:0x3ffe6670 0x401af5dd:0x3ffe66b0 0x400f7999:0x3ffe66d0 0x400fa13b:0x3ffe66f0 0x400f5c7e:0x3ffe6730 0x400f5e63:0x3ffe67c0 0x400d2476:0x3ffe67e0 0x400e0d11:0x3ffe6800 0x400e41ca:0x3ffe6840 0x400e90a5:0x3ffe68b0 0x400e9151:0x3ffe68f0 0x400e939d:0x3ffe6910 0x400e7c55:0x3ffe6930 0x400eedc6:0x3ffe6950 0x400e024b:0x3ffe6970 0x400908fe:0x3ffe6990
[10:47:16]
[10:47:16]Rebooting...
[10:47:16]ets Jun  8 2016 00:22:57
[10:47:16]
[10:47:16]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[10:47:16]configsip: 0, SPIWP:0xee
```

**Comment by ronaldheft** [comment]
Besides the crashing every 5-15 minutes, the new beta has done well tracking me throughout the day.

I currently have:
* Active scanning disabled
* My device id entered into the query box (roomAssistant was not showing up otherwise)

<img width="460" alt="Screen Shot 2022-03-02 at 4 46 01 PM" src="https://user-images.githubusercontent.com/1143112/156455014-945c9efe-0806-4fc1-ac86-74d69524eb0b.png">

**Comment by ronaldheft** [comment]
So last 12 hours have been less reliable. Same configuration as above, but every time the MAC rotates the ESPresense instances lose the Room Assistant beacon for a while.

<img width="461" alt="Screen Shot 2022-03-03 at 11 19 12 AM" src="https://user-images.githubusercontent.com/1143112/156606717-ba9bd994-cbcb-4f7a-855d-bfce0c6b3928.png">

Looking at the logs, the instances are now running for about 60-90 minutes before crashing, so I suspect the constant crashing before was actually contributing to finding the Room Assistant beacon more often.

**Comment by DTTerastar** [comment]
I think I may have found in the ble specification the thing we're not doing, you can make a "scan request" to get more uuids if they don't fit in the main advertisement.  I bet the iphone sorts them such that they make it on the main advertisment if the app is up but fall back to the scan request/response if not.

**Comment by hvorragend** [comment]
Now I have a problem, 

I have several Gigaset G-Tags and now the device name doesn't not contains the mac address. 
The topic looks like this: `espresense/devices/name:gigaset-g-tag/floor`

And inside this topic I have:

```
{
  "id": "name:gigaset-g-tag",
  "name": "Gigaset G-tag",
  "idType": 35,
  "rssi@1m": -71,
  "rssi": -83,
  "raw": 2.2,
  "distance": 2.23,
  "speed": 0,
  "mac": "7cxx80xx91xx"
}
```

Sadly now I cannot use the mqtt_room integration in Home Assistant, because there are many devices inside the same topic.

**Comment by DTTerastar** [comment]
Ok, i have a feature in mind for that use case

**Comment by mww012** [comment]
I'm seeing some of the same behavior with the Room Assistant app on my iPhone.  Happy to be another tester if that would be helpful.

**Comment by DTTerastar** [comment]
Try turning on active scan.  That should automatically ask the iPhone for more info that may include roomAssistant info.

**Comment by mww012** [comment]
I do have active scan enabled.  Since I'm not running on battery I just enable it by default.  Also, I'm running v2.0.36 and my filter is empty in case that matters.

One interesting thing I noticed is that when ESPresense boots I see the Room Assistant beacon and then the query.  The phone responds with the proper beacon and everything works as expected.  After a while I stop seeing room assistant beacon (with the app in the background).  In order to see the beacon again I have to pull the app back to the foreground AND restart my ESP32.  As soon as it restarts I see the beacons again.

**Comment by gadric** [comment]
@mww012: I have the same issue, with and without active scan enabled.

**Comment by DTTerastar** [comment]
I don't think this is an issue I can do something about in the code.  If I open the room assistant app the code instantly finds the advertisement and works great.  But after some amount of idle it stops advertising.  This is actually a GOOD thing because on something like my iPad i leave it in a room and the id is more of an "actively using" tracker.  But for something like my phone which I always want to track, I just add the apple:100x:x id to query and it works 100% of the time now (in the pre-lease).

**Comment by gadric** [comment]
@DTTerastar I would like to test the pre-lease to provide feedback. I guess I can install the pre-release marking the install pre-lease right? 

How can I down-grade if it does not work?

**Comment by DTTerastar** [comment]
Correct.  Uncheck the box :)

**Comment by gadric** [comment]
@DTTerastar: Great work! Installed the pre-release 2 hours ago. Since then, the tracking of my iPhone works really good. I can report tomorrow if this worked over the night.

**Comment by gadric** [comment]
Update: I am seeing 13 minutes intervals were my iPhone is recognized as not_home.

**Comment by gadric** [comment]
It seems that iOS still has hick ups. This is the the situation from the last 12 hours. As you can see, it reports often as `not_home`. My phone was not moving in the night. 

iPhone 12: 
![2022-03-14 10_14_43-Window](https://user-images.githubusercontent.com/19403905/158141385-72c5b4e9-b1e3-44ed-8485-ac54cdf13779.png)

In comparison to MiFit over ESP32 
![2022-03-14 10_15_54-Window](https://user-images.githubusercontent.com/19403905/158141597-8aaa2e4c-434a-4c85-8dcb-625555ade686.png)

**Comment by gadric** [comment]
I think I figured out the issue. 

first of all, I have brought more ESP32 and place them in all rooms. And since 20 hours, it works without any issue as long as I deactivate room assistant on my iPhone. It seems that it causes problems if both are running at the same time.

**Comment by mww012** [comment]
Awesome!  I'll give that a try as well. I hadn't considered Room Assistant causing a conflict. I'll let you guys know what the results are. 

Also, I enabled pre-release version and all my esp32s are running 2.1.0 but I believe that's the general release version. Is that what I should be seeing?

**Comment by gadric** [comment]
Hmm, after days of testing, it does not to work for me ... 

I tried many combinations: with active scanning, with query, with only room-assistant, without only apple id. 

it seems that it goes offline after a couple of minutes. I dont know, may it related to that I have an iPad and AppleTV around here? Too many collisions?

**Comment by bachoo786** [comment]
hi guys I am struggling to find my ID for my iphone 12. Can anyone help please?

**Comment by DTTerastar** [comment]
Are you using the serial monitor and putting them on top of each other?

**Comment by bachoo786** [comment]
> Are you using the serial monitor and putting them on top of each other?

I have 4 base stations and under devices in my mqtt explorer I have lots of apple devices showing and other various devices. I can't really tell which one is which.

**Comment by DTTerastar** [comment]
The serial output shows CLOSE when the device is touching the esp32.  It's very easy that way to get the id.
