### ISSUE TITLE
Google Pixel 6 Pro Support

### ISSUE THREAD

**Issue by gdreelin** [ESPresense/ESPresense#355]
Ok not sure if this is just a Google Pixel itself but it will not allow the beacon to be seen on ESPresense for some unknown reason. I know most times Google Pixels require a pairing pin number of sorts but not sure why it will not show up trying to talk to the ESPresense. I have checked it on the terminal and using MQTT Explorer to try and find it but no joy either way. I thought maybe it fell under a different MAC than the one it says it is on the phone so I played around with some devices that were showing up but turns out most were Roku, Govee Devices, and printers trying to talk. Apple products connect just fine, got my wife's hooked up with no issues. I got a Garmin Smart Watch to connect but dang if the Google Pixels will not and I have two people that have them in my house. I put this under feature request because I do not think it is the fault of the ESPresense but more on support for the Google Pixels.

**Comment by DTTerastar** [comment]
You need to add an app to get Android to work.  HA Companion has a "Bluetooth sensor" that you can enable that outputs an iBeaon.  https://espresense.com/beacons/apps -> Android beacon broadcasting apps

**Comment by gdreelin** [comment]
Thanks
