### ISSUE TITLE
Include Filter isn't working

### ISSUE THREAD

**Issue by begunfx** [ESPresense/ESPresense#365]
**Describe the bug**

Adding devices to the filter list seems to just prevent all traffic from being received by the sensors.  The Query filter doesn't seem to pick up the devices listed in the filter.

**Config**

- Version: 2.0.34
- Active scan enabled:
- Include filter: iBeacon.1fb27f22-e037-4d7a-8644-ed01b4b99ab8-19-73 iBeacon.5e8fbd77-f32d-460b-8ee1-9be5497a1e26-19-81 apple.iphone13-2
- Exclude filter:
- Query filter:

**Hardware**
Atom LITE

- Firmware flavor: Release version
- Device (be specific): Atom LITE

**Logs**

If possible, copy and paste any logs from the serial monitor from the time that you see the bug.

**Screenshots**

**Comment by DTTerastar** [comment]
Replace the dots with colons (:) :)

**Comment by begunfx** [comment]
Awesome!  Thanks!  It was driving me crazy that it didn't seem to work.  Can you maybe tweak the usage so it's a little clearer that you need to follow that format?  The ids listed in the beacons use periods, so logically it seemed that we just copy and paste them.

**Comment by DTTerastar** [comment]
The ids are always colon separated.  Not sure where you've seen dots.

**Comment by begunfx** [comment]
Weird.  I had copied the IDs from MQTT Explorer a while back and they were using dots.  I guess I hadn't noticed that the format changed?  I was just re-pasting the values that were there before (me being lazy).

**Comment by begunfx** [comment]
Either way.  I guess I can close this then.  The filter queries were a big deal for me to move forward using this, since I was getting way too much traffic to my MQTT broker.

**Comment by simonyel** [comment]
And what if one of the devices listed in the include filter is a MAC address? Without the : in the ID?

**Comment by DTTerastar** [comment]
The logic is, take all the values find the spaces and make a list of prefixes.  If any of the prefixes match the id then include it.  So an id without a colon should work fine.

**Comment by simonyel** [comment]
I can't copy/paste my filter currently, but I have a filter with two (hass app) iBeacon entries and Mac from a watch. The watch is never located. Without filter, the watch is reported along with 30 other devices. Might be worth double checking if column also plays part in parsing the filter.

**Comment by DTTerastar** [comment]
What kind of watch?

**Comment by simonyel** [comment]
Garmin Vivo active, I believe.

- Simon Yelfimov
________________________________
