### ISSUE TITLE
[Support:] Send raw BLE-Advertisment and Apple Nearby as raw UUID/MQTT

### ISSUE THREAD

**Issue by ozett** [ESPresense/ESPresense#367]
**Is your feature request related to a problem? Please describe.**
i want to clearly identify all seen BT devices in my environment.
seems that the UUID is a fixed advertisment, but not send over MQTT

i want to identify most of the seen BT devices clearly.
fingerprinting is good, [but still changes above devices](https://github.com/ESPresense/ESPresense/issues/260)
UUID could be solution for BT5 (BT4?) https://github.com/ESPresense/ESPresense/issues/82

**Describe the solution you'd like**
send the UUID with MQTT

**Describe alternatives you've considered**
looked through issues but did not find solution https://github.com/ESPresense/ESPresense/issues?q=UUID
maybe i dont have all BT details for creating UUIDs and they change also?
ID-Type is made by espresence and no BT standard https://github.com/ESPresense/ESPresense/issues/193
maybe already working, but not over MQTT? https://github.com/ESPresense/ESPresense/issues/41

**Additional context**
Check/Deocde UUID to verify some BT.specs?
https://www.uuidtools.com/decode

https://www.argenox.com/library/bluetooth-low-energy/ble-advertising-primer/#a-quick-look-into-uuids

![image](https://user-images.githubusercontent.com/5937811/156876166-310c7001-2643-4fbc-9b20-6a1c4e3649dd.png)

UUID seems good alternative for randomized MAC - besides (!) fingerprinting  https://esphome.io/components/binary_sensor/ble_presence.html#esp32-ble-tracker-setting-up-devices

![image](https://user-images.githubusercontent.com/5937811/156878937-678eb54f-28c5-48cb-babe-0cc21bf036aa.png)

actual espresence JSON without UUID:

![image](https://user-images.githubusercontent.com/5937811/156876405-0552887d-dce3-47f7-a11e-66b96470d90c.png)

**Comment by ozett** [comment]
some suggestion about the UUID format
https://github.com/shmuelzon/esp32-ble2mqtt/issues/12#issuecomment-456804828

**Comment by ozett** [comment]
Please consider sending the alway preset apple nearby information in RAW format, too.

https://github.com/furiousMAC/continuity/blob/master/messages/nearby_info.md

**Comment by DTTerastar** [comment]
It's in the disc field already

**Comment by ozett** [comment]
> It's in the disc field already

what is the disc-field?
is not only pure apples nearby information. why not?
is always something else per device/manufacturer?  is it a mixed-type field?

https://github.com/ESPresense/ESPresense/blob/3a28f8c869f525437a3b3d9596c9b0fbecfd9d52/lib/BleFingerprint/BleFingerprint.cpp#L292

https://github.com/ESPresense/ESPresense/blob/3a28f8c869f525437a3b3d9596c9b0fbecfd9d52/lib/BleFingerprint/BleFingerprint.cpp#L322

still looks to me promising for seondary fingerprinting to send the pure UUID via MQTT

**Comment by ozett** [comment]
while observing the disc-values, it seems to me, that its not always starts with the apple-nearby identifyer.
could this be the case?

![image](https://user-images.githubusercontent.com/5937811/159303557-e81f6fdc-52da-4b84-a409-30cf70b625b4.png)

**Comment by DTTerastar** [comment]
The first 2 bytes are not in it, because those are the last 2 bytes of id.

**Comment by DTTerastar** [comment]
> > It's in the disc field already
> 
> what is the disc-field? is not only pure apples nearby information. why not? is always something else per device/manufacturer? is it a mixed-type field?

It's discriminator.  It's basically the portion of the advertisement that we excluded from the id.  My thought was it would be useful at a higher level app to detect mac rollovers.  If the mac changed but the disc didn't we'd know it was still the same device.  It is currently unused.
