### ISSUE TITLE
Being able to script device setup and maintenance 

### ISSUE THREAD

**Issue by gmathur** [ESPresense/ESPresense#375]
Pulling the following fields from mqtt would be great from a maintenance perspective -- right now I have to run around and update the configuration on all the devices one on one when I want to track a new device or remove a very chatty BT device.

Field name:
- Exclude sending these ids to mqtt 
- If set will only send matching to mqtt (eg. apple:iphone10-6 apple:iphone13-2):

**Comment by markmghali** [comment]
Are you looking for like setting up one espresense and then having the others copy the settings? that would be nice to have it propagate the configuration across all ESPresense

**Comment by gmathur** [comment]
Yes exactly - most people would be tracking the same set of devices across their entire home. 
Being able to provide a topic to subscribe to for what to track and what not to track will allow central evolution of those settings. By the way - I would argue the same could apply for some of the other settings too like: Forget beacon if not seen for... and Skip reporting if message age is less that this (in milliseconds) settings also. 

I have been trying to tweak both the update flood coming from each device as well as tracking time outs happening within Home assistant and found myself going to all the beacons to tweak the above 4 settings (quite painful)

**Comment by DTTerastar** [comment]
You can do this already:

Send to espresense/rooms/*/include/set

Need to get the list of settings documented, but they're the basically just the config value you can see at startup with /set

**Comment by gmathur** [comment]
That’s awesome. Is it basically what the mqtt topics show in JSON with just the /set endpoint?

In that case workflow wise would be great to be able to configure 
- Wi-Fi ssid, password and mqtt information via URL parameters to the hotspot
- Then be able to pass in all other config via mqtt - sounds like this already works
- Maybe also force an ota via mqtt to a specific firmware version?

That way we can automate setup of a number of devices and being able to play with different betas and give you feedback :)

**Comment by DTTerastar** [comment]
Yeah, an update to a particular version would be a useful mqtt command
