### ISSUE TITLE
Use release proxy to pick version to install, don't include incomplete releases

### ISSUE THREAD

**Issue by askthomas** [ESPresense/ESPresense#378]
**Describe the bug**

A clear and concise description of what the bug is.  If it relates to fingerprinting or presense please include the id you expect/monitor.

**Config**

- Version:
- Active scan enabled:
- Include filter:
- Exclude filter:
- Query filter:

**Hardware**

- Firmware flavor:
- Device (be specific):

**Logs**

If possible, copy and paste any logs from the serial monitor from the time that you see the bug.

**Screenshots**

![espressens-404](https://user-images.githubusercontent.com/35760597/157449340-06a1c41e-870a-4f59-84aa-0177ca6ae839.png)

**Comment by DTTerastar** [comment]
Yes this happens every time I make a release for 20 minutes because github it's still building the releases.

**Comment by askthomas** [comment]
Cant it be compiled first, then repoint latest to it when done. It feels a bot strange to have to point live linke with lates to en empy folder.
