### ISSUE TITLE
Giga-set G -tagID not unique anymore

### ISSUE THREAD

**Issue by FlingersDH7** [ESPresense/ESPresense#380]
After update 20.0.36 and also with 20.0.37, the ID of gigaset g-tag is not unique anymore. All my ESP32's show the same ID's. In earlier versions of ESPresense the ID  always was the MAC address of the tags. This makes tracking of multiple tags impossible.

Home assistant also shows the tags as not_home.
This is my config which worked before.

- platform: mqtt_room
  device_id: "7c2f80c3a1c6"
  name: 'ESPresense Presence tag 1'
  state_topic: 'espresense/rooms'
  timeout: 60
  away_timeout: 120

Screenshot of the ID's running on version 20.0.37

![Schermafbeelding 2022-03-09 215610](https://user-images.githubusercontent.com/10938130/157534520-5e229482-02a5-4f33-8fd0-2bfb674b73e4.png)

**Comment by DTTerastar** [comment]
Can you try the pre-release and see if that fixes it?

**Comment by FlingersDH7** [comment]
It looks like it's working again. Thank You very much.
