### ISSUE TITLE
Atom lite stops detecting devices after some time

### ISSUE THREAD

**Issue by gmathur** [ESPresense/ESPresense#382]
**Describe the bug**

BT scanning stops working after some when using atom lite as beacon. The presence detection works great for some time but after a while each beacon stops reporting any BT devices detected. 

Each beacon seems alive as observed within home assistant - it’s config page is accessible and I verified it’s uploading the heartbeat to Mqtt correctly.

To fix the problem just unplug and plug the atom lite back in and it starts working right away.

**Config**

- Version: 2.0.36
- Active scan enabled: yes - trying to scan for just one iPhone fingerprint
- Include filter: yes tracking one device
- Exclude filter: 
- Query filter: no

**Hardware**

- Firmware flavor: 2.0.36
- Device (be specific): atom lite (m5 stack)

**Comment by DTTerastar** [comment]
I believe this is corrected in the pre-release, can you check?

**Comment by gmathur** [comment]
Ill give it a whirl today.

**Comment by gmathur** [comment]
No dice. Updates still not coming in from the devices.

**Comment by DTTerastar** [comment]
Ok, I figured it out, github did something odd with b2 and compiled master, so no wonder you saw no change. b3 is going out now.

**Comment by gmathur** [comment]
Ok I see b3 now. Ill give it a whirl

**Comment by gmathur** [comment]
B4 is looking so much better. Tracking seems to be working quite reliably. I’ll keep giving it a whirl today and update

**Comment by gmathur** [comment]
Overall this is a BIG upgrade. I think there is still a memory leak issue -- see the free memory graph below
<img width="1513" alt="Screen Shot 2022-03-13 at 5 45 35 PM" src="https://user-images.githubusercontent.com/319480/158087275-0b43fb03-250d-4d6a-a261-16dea6525355.png">

**Comment by DTTerastar** [comment]
I've seen my debug WROVER run for 5 days straight.  So if there is a memory leak it is very small.  Can this be closed?
