### ISSUE TITLE
Charateristic query

### ISSUE THREAD

**Issue by vekexasia** [ESPresense/ESPresense#388]
Hello there, 'm going to install 9x espresense around the house. In my garden i've several miflora sensors which data can be collected by reading bt charateristic of such sensors.

I know this is out of scope of espresense but maybe there is already an almost painless way of doing such task

**Comment by vekexasia** [comment]
this actually would be nice.

**Comment by DTTerastar** [comment]
I did buy one, but haven't quite gotten it into a flower pot :)
