### ISSUE TITLE
UUID beacon

### ISSUE THREAD

**Issue by April-ha** [ESPresense/ESPresense#41]
Hello
with my Ebeacon in version 1.1.2 the UUID was upside down but visible.
the RSSI at 1m was correct and matched the beacon.

In V1.5.0 the UUID are no longer visible and the RSSI at 1m is blocked on -59.

https://ibb.co/jkY7b4s

but i can use the new ID instead of the UUID it doesn't change much, but could you please correct the RSSI@1m.

thanks you

**Comment by DTTerastar** [comment]
Yeah, I need to refactor all that power calc code.

**Comment by DTTerastar** [comment]
Ok, I think it should all work now.  What rss@1m do you see now?

**Comment by April-ha** [comment]
V1.5.2
same
maison = {"id":"dc3056789abc","name":"MH","rssi@1m":-59,"rssi":-75,"mac":"dc3056789abc","raw":2.87,"distance":2.26,"speed":0}

**Comment by DTTerastar** [comment]
That's not the right entry.  Your beacon must be sending some TLM
broadcasts interleaved with iBeacon broadcasts.  Depending on the transmit
interval it might take a few seconds to get BOTH kinds of packets.

The iBeacon broadcast has the ***@***.*** in it, NOT the tlm broadcast.  You
should see a separate entry for the iBeacon once it finds it and that
should have a good ***@***.***

**Comment by April-ha** [comment]
I did a test with "beacon simulator" on android and it works fine ("id": "iBeacon:770cddcb2d3e145784de5874ce581250-1-2").
I don't understand because my beacons worked fine in v1.1.2 and don't work after this version ("id": "dc3056789abc").
v1.1.2 works fine for me, I'll stay with this version.

**Comment by DTTerastar** [comment]
Can you try master and see if it fixes it?

**Comment by DTTerastar** [comment]
I ordered a Dialog based iBeacon from ali and it came today!  And it does exhibit your exact issue, and master does indeed fix it.  Releasing it now as 1.5.4.

**Comment by April-ha** [comment]
Congratulations DTTerastar, everything works fine with version v1.5.4.
Thank you for your work

**Comment by ozett** [comment]
> I ordered a Dialog based iBeacon from ali 

i am still searching for easy identify-able bluetoot devices, 
@DTTerastar : may you have a link which one you ordered?

[there are some options](https://de.aliexpress.com/wholesale?trafficChannel=main&d=y&CatId=0&SearchText=ibeacon&ltype=wholesale&SortType=total_tranpro_desc&groupsort=1&page=1), if i search for "ibeacon",
but i have no clue which to choose.. appreciate a hint .. thx.
