### ISSUE TITLE
Query ids don't stick

### ISSUE THREAD

**Issue by nickelnine** [ESPresense/ESPresense#423]
**Describe the bug**

I have 3 ESP32 nodes of which 1 doesn't honor the device ids I enter in the Query field. When I open the web page for the node, it will show either ON or OFF in the Query box instead of the device ids I had entered. No reboot, no changes just suddenly when an automation for that room stops working it's because the device id vanished and replaced with the above.

**Config**

- Version: 2.1
- Active scan enabled: Yes, Request scan results is enabled
- Include filter: none
- Exclude filter: none
- Query filter: apple:1005:9-12 apple:1005:9-8

**Hardware**

- Firmware flavor: the default OTA flavor
- Device (be specific): MH-ET LIVE D1 mini ESP32

**Logs**

If possible, copy and paste any logs from the serial monitor from the time that you see the bug.

**Screenshots**

![Screenshot_20220323-094702603](https://user-images.githubusercontent.com/28116390/159740447-caa9a783-3ff6-4294-a0eb-ed40bec9ef10.jpg)

**Comment by nickelnine** [comment]
I find it offers more reliability

**Comment by nickelnine** [comment]
Still an issue. Query ids entered into the Query box disappear and replaced by literal string "ON".

**Comment by DTTerastar** [comment]
Hmmm, I think there is something sending mqtt messages on your network that are conflicting.  Can you use mqtt explorer and look for a message that looks like espresense/rooms/*/query/set w/ the payload ON?

**Comment by nickelnine** [comment]
Yes, currently I see a payload of ON in espresense/rooms/bedroom/query. I don't have a /set segment. My livingroom node is chugging along just fine with the query id I set but my bedroom node refuses to stick. I changed it manually yesterday but overnight it went to ON again.

**Comment by nickelnine** [comment]
Not an issue since using IRK
