### ISSUE TITLE
devices show up in logs, but not in home assistant?

### ISSUE THREAD

**Issue by plexkiki** [ESPresense/ESPresense#449]
Hi there! please just get rid of this thread if its bad or already being addressed elsewhere.

So I'm running HA Core on TrueNAS and have MQTT configured etc. Actually I know the set up is working perfectly because I can see my partner's data updating literally multiple times per second righ now. I tried to follow the exact same set up with my own Samsung Galaxy S10 and it just doesn't seem to want to take. (It's also not super with my fitbit, but I've heard there's issues there.)

I've tried every variation of possibilities in the settings for the esp32, HA and the companion app on my phone for this and the only things I've noticed is that the esp32 bluetooth scan is finding the devices then recognising them as "1 New" every time. I also get "query error" when I put the iBeacon ID in the box for that. 

Its frustrating because clearly the esp32 can see the beacon my phone is outputting. it just isn't doing anything with that for some reason and I can't for the life of me figure out why. Hoping I've just overlooked something simple by mistake, thank you in advance I am not very good at this! :)

**Comment by DTTerastar** [comment]
Put the id into hass exactly like it appears in MQTT explorer.  The type prefix and colon must be in the id field of hass.  Most of the documentation just has a single mac address, but ESPresense has more to the id than typical.  Screenshots of your config would help to diagnose as well :)
