### ISSUE TITLE
Restart Device via UI opens non-existent URL

### ISSUE THREAD

**Issue by Doctor-Yof** [ESPresense/ESPresense#455]
**Describe the bug**

Restart via the 'restart device' button at the top of the web UI opens webpage [deviceIP address]/restart. This URL does not exist and therefore returns 404 error.

**Config**

- Version:2.1.0

**Hardware**

- Firmware flavor: ESP32 & ESP32 w/sensors
- Device (be specific): D1 Mini ESP32 NodeMCU & clone ESP-WROOM-32 development board

**Comment by DTTerastar** [comment]
We use https://github.com/Juerd/ESP-WiFiSettings 
I believe POST /restart is what does the restarting, but a GET /restart doesn't exist.  Now entirely sure if it an issue.
