### ISSUE TITLE
Rate limit for slow changing sensor data

### ISSUE THREAD

**Issue by f0rdprefect** [ESPresense/ESPresense#458]
**Is your feature request related to a problem? Please describe.**
Using DHT22 sensors for temperature and humidity shows very frequent updates of sensor values. This is putting a lot of unnecessary data into both HA and influx in my case as both values change rather slowly

**Describe the solution you'd like**
Rate limit the raw sensor value or even better implement an [exponential gliding average](https://en.wikipedia.org/wiki/Moving_average#Exponential_moving_average), which will smooth the sensor value, but still react fast in case of real changes 

**Describe alternatives you've considered**

**Additional context**

**Comment by manfred-mp** [comment]
I noticed the same and created threshold (0.1) check for all sensors before publishing values. This will still be accurate enough and update every minute if needed. See pic around 19:00 how graph changes.

Code example:

> if(fabsf(temperature - BME280_temperature) >= 0.1){
                mqttClient.publish((roomsTopic + "/bme280_temperature").c_str(), 0, 1, String(temperature).c_str());
                BME280_temperature = temperature;
            }
<img width="1093" alt="Screenshot 2022-09-12 at 21 34 12" src="https://user-images.githubusercontent.com/1030705/189875522-9f5cbab7-9178-4cfe-9463-03accd7f7492.png">
