### ISSUE TITLE
Switch to a different WiFi network?

### ISSUE THREAD

**Issue by uspino2** [ESPresense/ESPresense#464]
This has been asked before but I can't find a clear answer. Is there a way to move the ESPresense module to a different WiFi network, other than re-flash and start from scratch at the captive web portal?

Thanks.

**Comment by dwardu89** [comment]
if you need to do that, probably the best is to block that device from the wifi network, or get it out of range  of that wifi AP. it will create it's own wifi network, and connect to that and change the settings like that

**Comment by DTTerastar** [comment]
Yeah, either kill the wifi network you don't want it to use, or erase and reflash.  On certain variants it does support holding down a button to erase (ala a Wifi router).
