### ISSUE TITLE
Auto Update over-written 2.1.1 with 2.1.0.

### ISSUE THREAD

**Issue by JohnTranQUT** [ESPresense/ESPresense#468]
**Describe the bug**

2.1.0 update has over-written 2.1.1 update.

**Config**

- Version: 2.1.1 ESPresense with Sensors:
- ☑ Automatically update (default: ☑)
- ☐ Include pre-released versions in auto-update (default: ☐)

**Hardware**

- Firmware flavor: ESP32 with Sensors
- Device (be specific): ESP32

**Workaround**

 - Allowing autoupdate for pre-release brings in v2.1.1b6.
 - Or manual update to 2.1.1 with Autoupdate disabled.

**Logs**

No logs however I've noticed my HX711 weight sensors weren't working. After rechecking my wiring, nothing was notably wrong. Checked Home-assistant logs, and noted that the weight data frozen about 10:00 AM UTC 9th May in the mqtt.

I've noticed my ESP32 device was on version 2.1.0 and its webpage and had the hx711 sensor settings disappeared.
Distingtively recalled the version that it was on 2.1.1 release because it introduced hx711. Github shows that the latest version is 2.1.0 now. It was 2.1.1 about 26 days ago. This meant that my esp somehow downgraded as the result of that.

Also, there is 2.1.1 here
https://github.com/ESPresense/ESPresense/tags
however, it does not show up when going to
https://github.com/ESPresense/ESPresense/releases

**Screenshots**
Please note that the screenshot is in AEST time.
![image](https://user-images.githubusercontent.com/22422390/167511415-15a1bd10-48b0-4607-b9a1-0eaf038fda2e.png)

**Comment by onlyoneme** [comment]
2.1.1 is back. I think that the switch to disable/enable possible downgrades during auto ota would be nice.

**Comment by JohnTranQUT** [comment]
> 2.1.1 is back. I think that the switch to disable/enable possible downgrades during auto ota would be nice.

Looks like you are right. All of my ESP32 Presence had been updated overnight.
This issue can be closed now.
