### ISSUE TITLE
Add support for BME680

### ISSUE THREAD

**Issue by DorjeDorf** [ESPresense/ESPresense#472]
**Is your feature request related to a problem? Please describe.**
It's awesome that ESPresense has support for BME280. I am hoping support for BME680 can be added to further enhance sensor support and add air quality measuring. 

**Describe the solution you'd like**
Same kind of support as there is for other sensors. The calibration might get a bit tricky, but this could be shifted to the user to remember the tracking and updating once the sensor has had some hours of work time. 

**Describe alternatives you've considered**
The only alternative I see is having yet another device with the BME680, but it'd be great to have a single multi sensor handling the presence, PIR and data given by the BME680. 

**Additional context**
Nothing to add. Just hoping this gets done ;)

**Comment by Wheemer** [comment]
This is not working yet?
