### ISSUE TITLE
Please add support for max6675 temperature sensor

### ISSUE THREAD

**Issue by jloffredo** [ESPresense/ESPresense#473]
**Is your feature request related to a problem? Please describe.**

Seeing as temperature sensors are being added, I have an esp device with only a MAX6675 temperature sensor and I'd love to be able to use it with ESPresense

Thanks!!

**Comment by DTTerastar** [comment]
Are these useful for room temperature? I though they were more for adding to bbq or something.

**Comment by jloffredo** [comment]
I have one ESP in my kitchen with one of these for my oven. I'd like to use that same ESP for presence instead of adding a second one.

**Comment by DTTerastar** [comment]
Cool

**Comment by DTTerastar** [comment]
https://github.com/adafruit/MAX6675-library/blob/master/examples/lcdthermocouple/lcdthermocouple.ino seems trivial to implement
