### ISSUE TITLE
Support sonoff m5

### ISSUE THREAD

**Issue by RaZer0r** [ESPresense/ESPresense#477]
**Is your feature request related to a problem? Please describe.**
I’m about to install my dual button m5 and would love to run espsense as well to further hide anything tech in the house ;). 

**Describe the solution you'd like**
support for buttons like on the sonoff m5

**Describe alternatives you've considered**
I could run esphome, but the BLE integration just isn’t as good.

**Comment by DTTerastar** [comment]
So we need to support relays and buttons?

**Comment by RaZer0r** [comment]
yes, relays, buttons and leds (I'm not sure if the on/off led is controllable separately on each switch/button)

**Comment by RaZer0r** [comment]
Where are you located? If possible, I would definitely consider sending you a unit

**Comment by DTTerastar** [comment]
Pennsylvania, USA

**Comment by Mdleal** [comment]
I really want relay support for general relay use, I could send you money or ship you one from amazon to support the cause.  LMK.

**Comment by Mdleal** [comment]
Can you add the M5 and not the nspanel?

**Comment by DTTerastar** [comment]
Didn't even know there were the non screen ones :)  Done.

**Comment by Mdleal** [comment]
Ordered the 3 gang which is only 1 gang with 3 switches which is weird they call it 3 gang. Should be there tomorrow.

**Comment by DTTerastar** [comment]
Cool

**Comment by bqtran** [comment]
> https://www.amazon.com/hz/wishlist/ls/MTFZJ03S78XY?ref_=wl_share I believe you can just ship it to Your Name’s Gift Registry Address via this.

Do you still need the hardware to get this going? I also don't mind footing the bill for a dev unit or two. :)

**Comment by DTTerastar** [comment]
I have it.  The 3 led support in the new v3 is step 1 of supporting it...

**Comment by RaZer0r** [comment]
Nice ;)

**Comment by DTTerastar** [comment]
Sorry, this keeps getting back burnered.

**Comment by RaZer0r** [comment]
Can this be kept on the schedule?
