### ISSUE TITLE
Not automatically updating firmware

### ISSUE THREAD

**Issue by manbeast76** [ESPresense/ESPresense#478]
Thank you for creating this!  I have found it very helpful.  I have 7 base stations spread over my house.  One of them is on firmware v2.1.1.  The other 6 are on v2.0.26.  I have all 7 configured to automatically update, but the 6 have been stuck on v2.0.26 for some time now.  Is there a way for me to force them to OTA update their firmware?

**Comment by DTTerastar** [comment]
You can turn on the Ardinuno OTA and flash via espota.py.  This is an example on how to do it: https://github.com/ESPresense/ESPresense/blob/master/espotabatch.py
