### ISSUE TITLE
Integration of a simple web server and REST API

### ISSUE THREAD

**Issue by ethanholz** [ESPresense/ESPresense#487]
**Is your feature request related to a problem? Please describe.**
In an effort to match some other ESP projects (such as ESPHome), I would like to have the option to use a web server instead of MQTT to simplify integration with third party services since no other MQTT broker is needed. 

**Describe the solution you'd like**
To solve this, the integration of simple web server and a corresponding set of REST API calls would need to be generated. Additionally, a toggle would need to be set to allow for this to be enabled. 

**Describe alternatives you've considered**
I have considered that the addition of this functionality is outside of the scope of this project. However, I do not feel there are alternatives to my proposal other than what is already submitted.

**Comment by DTTerastar** [comment]
The beta has /json/devices implemented that will get you the same basic info as transmitted to mqtt
