### ISSUE TITLE
ESP32 UWB - (ULTRA WIDE BAND)

### ISSUE THREAD

**Issue by stan69b** [ESPresense/ESPresense#496]
Hey, I recently purchased 3 ESP32 with UWB capability. I am planning on playing with your ESP code to add support for UWB. 
It is going to be my first time working on these kind of devices (micro controllers), if you have any tips or information that can be helpful, please share :) 
I am hoping that UWB can work better with less nodes.

What i hope is going to happen is that I can just load the uwb library and convert data into the same format as you and just hook myself in the right place.

**Comment by DTTerastar** [comment]
UWB needs something to talk to, have you found UWB trackers too?

**Comment by stan69b** [comment]
I'm testing with an esp32 as a tracker for now. I was hoping to use my Apple Watch but Mac randomisation does not help. I believe every major manufacturer is using it.... I need to find a UWB tracker or bracelet but have not found anything good for now. And on a side note, I only detect other esp32 with uwb, no actual devices. I do not know if the library is filtering something.
Still discovering the technology but the accuracy is juste incredible

**Comment by stan69b** [comment]
I need to check out the iOS doc, we might be able to make a beacon app with fixed Mac. Knowing apple though, it will not work in the background if it does at all.
You can enroll the esp32 with apple location tracking api, but I do not see any use for it right now. Except locate the esp with the iPhone but no use here.
We might be able to have an app that runs in the background, talks to the esps, and sends the data for each anchor to home assistant via api call. That would be apple compliment anonymity wise.
I will post updates here when I have some.

**Comment by DTTerastar** [comment]
I'm almost 100% that there is no api for UWB on iOS.  I would love to be wrong tho.

**Comment by DTTerastar** [comment]
https://developer.apple.com/nearby-interaction/specification-preview/

**Comment by stan69b** [comment]
little update, we are having issues with multiple anchors that seem to interference with each other (a friend of mine is helping me). solution to try is synchronizing them so that they send their request on slightly diffrent times OR try to have them on diffrent frequences (which could work if the tracker can listen on all of them... and if existing devices like phone and watches allow tracking, which I doubt 100%, and listen on all frequences...) but perfect for custom trackers.
I will still investigate the app side of it, ios or android app that could fetch distances to each anchor and send the data to home assistant, but background will be impossible for ios if such an app is even possible at all, for android i suppose it has more chances of working but i do not own a UWB android device.

**Comment by DTTerastar** [comment]
I still think signing up for Apple Car Key would be the "supported" way of doing this.  My ESP32 is a car, got it Apple?

**Comment by DTTerastar** [comment]
@stan69b How's this going?

**Comment by Maxakipust** [comment]
I am also interested in this. I picked up one of [these](https://www.makerfabs.com/esp32-uwb-dw3000.html) to see if I can get it to talk with my iphone with nearby interaction. I haven't been able to get it to work yet and I haven't been able to find any example code to get it to work with nearby interaction. If anyone has any leads on how to get this working, I'm all ears.

As for the background nearby interaction sessions. [this video](https://developers.apple.com/videos/play/wwdc2022/10008/?time=1080) says that NI sessions can exist in the background as of ios 16. Tbh most of the technical details went over my head since I'm not super familiar with this kind of stuff. But it should be possible.

**Comment by stan69b** [comment]
Hey, I have been struggling a lot to get to something, anything really. The company I work with plans on using this technology in a near future so I was hoping to hitch a ride along to work on this. For the time being switched on an esp32 E-paper display 10'' for a low energy  home assistant display. I have no eta to when I plan on working on this but it will certainly remain in my pipeline.
I do not know if it is something that appeals to you as well, If it is, I would gladly have one shipped to you as a participation on this project ;)
I can re-open this thread when I get back to this so you can close it if you whish :)

**Comment by stan69b** [comment]
> I am also interested in this. I picked up one of [these](https://www.makerfabs.com/esp32-uwb-dw3000.html) to see if I can get it to talk with my iphone with nearby interaction. I haven't been able to get it to work yet and I haven't been able to find any example code to get it to work with nearby interaction. If anyone has any leads on how to get this working, I'm all ears.
> 
> As for the background nearby interaction sessions. [this video](https://developers.apple.com/videos/play/wwdc2022/10008/?time=1080) says that NI sessions can exist in the background as of ios 16. Tbh most of the technical details went over my head since I'm not super familiar with this kind of stuff. But it should be possible.

Thanks for those information, they are very intresting. Nice device, mine uses the DW1000. Regarding the video, thanks for the timestamped linked :) From what i understand, we should be able to build a swift app that would be able to get its position from UWB devices. If that is the case, we should be able to send this data from the iphone itself to home assistant via an api as raw for calculation in python or pre calculated by the phone but not sure if ios allows it in the background, pretty intencive i guess :/ 

That changes a lot of things and seem to be more in my domain of expertise than tinkering with c++ on microcomputers. I'll try to have a look when my other project is at a point I can use it and update this thread.
