### ISSUE TITLE
M5 StickC Plus - Display timeout Feature Request

### ISSUE THREAD

**Issue by mrizzo123** [ESPresense/ESPresense#506]
Would it be possible to add a feature so you can blank the screen on the M5 Stick after a timeout?

Perhaps waking the screen with a press of A or B button?

I am looking to keep power as low as possible. I know I can disable the LED light currently but a screen timeout would be nice to also reduce power consumption.

Thanks in advance,
Mark

**Comment by DTTerastar** [comment]
Wifi takes up a tremendous amount of the power of the M5 StickC Plus.  I don't think disabling the display will make a huge improvement in run time.  Have you tried just running esp32 flavor (after a hard powerdown) and see how much longer it runs?  That would show you how much longer no screen on would be.
