### ISSUE TITLE
Amazfit GTR 2e shown as not_home in Home Assistant

### ISSUE THREAD

**Issue by vzoltan** [ESPresense/ESPresense#509]
![image](https://user-images.githubusercontent.com/2751780/176482982-7ef401b1-f373-41a0-bdde-047319c81538.png)

Blue is my Amazfit GTR 2e (also not_home) cyan is my MiBand (also not_home) red is my phone with Home assistant app, (in the correct room)

even the distance is correct for the two wearable.

Hi, im using room-assistant on a raspberry pi, which sees and reports that my Amazfit GTR 2e is at home/room
but espresense shows as not_home.

what can be the problem?

(note: i did setup my phone, and that is shown in the given room just right with espresense, so the config is OK for the watch too.)

some lines from esp32 terminal
Band4:
[17:56:41]1 C# +1 | MAC: d0f10eab14e0, ID: known:d0f10eab14e0                                        -34dBm (0.09m) 76ms
Watch:
[17:56:41]1 C# +1 | MAC: e9b5de977bd4, ID: known:e9b5de977bd4                                        -69dBm (1.10m) 778ms
Phone
[18:05:05]1 New   | MAC: 6c14b8a132f1, ID: iBeacon:3f2fe1df-007f-4af7-b945-b1be3871308a-100-1        -92dBm 

![image](https://user-images.githubusercontent.com/2751780/176485311-0fafa277-ae74-4ce5-bd17-6dae24f1623b.png)

configuration.yaml:

```
# One entry for each beacon you want to track
  - platform: mqtt_room
    device_id: "e9b5de977bd4"
    name: "Zoltans Watch"
    state_topic: "espresense/rooms"
    timeout: 10
    away_timeout: 120

  - platform: mqtt_room
    device_id: "d0f10eab14e0"
    name: "Zoltans MiBand"
    state_topic: "espresense/rooms"
    timeout: 10
    away_timeout: 120

  - platform: mqtt_room
    device_id: "iBeacon:3f2fe1df-007f-4af7-b945-b1be3871308a-100-1"
    name: "Zoltans Phone"
    state_topic: "espresense/rooms"
    timeout: 10
    away_timeout: 120
```

![image](https://user-images.githubusercontent.com/2751780/176484211-2137d374-c68e-4e76-95c2-8ce1668e0dfd.png)
![image](https://user-images.githubusercontent.com/2751780/176484399-b444edeb-e8fd-4fe1-9c71-2a04c6c70041.png)

![image](https://user-images.githubusercontent.com/2751780/176484297-30ceb08d-9742-4bc1-b92c-00eb08175609.png)

Any idea on this ?

**Comment by vzoltan** [comment]
mqtt gets this from esp32:

{"id":"known:e9b5de977bd4","idType":185,"rssi@1m":-76,"rssi":-39,"raw":0.09,"distance":0.13,"speed":0,"mac":"e9b5de977bd4","interval":2731}

But home assistant show like not_home

**Comment by vzoltan** [comment]
also from the log of the esp terminal:
[13:51:16]1 New   | MAC: e9b5de977bd4, ID: known:e9b5de977bd4                                        -68dBm 
.
.
[13:56:09]1 C# +1 | MAC: e9b5de977bd4, ID: known:e9b5de977bd4                                        -92dBm (1.75m) 7ms

bu HA reports as:
![image](https://user-images.githubusercontent.com/2751780/176432584-fa6d5b50-5fd1-4790-a290-e4419384f618.png)

while my phones BLE shows up just right.

**Comment by vzoltan** [comment]
thank you, solved it!

**Comment by nonomega** [comment]
Hello,

Sorry to bother you.
I'm using Home Assistant with ESpresence and it works like a charm using Miband 5 or 6.

But I'm not able to receive anything from my Amazfit GTR 2e even using MQTTExplorer.

I looked on device flag and saw that the GeneralDiscorevable is not active on my Amazfit GTR 2e.

 @vzoltan : as you're using the same device, could you please help me by sending me information like firmware version etc from your own device ?

Thanks in advance for your help.

nONo
