### ISSUE TITLE
Xiaomi Mi Band 4 shown as not_home in Home Assistant

### ISSUE THREAD

**Issue by vzoltan** [ESPresense/ESPresense#513]
![image](https://user-images.githubusercontent.com/2751780/176482982-7ef401b1-f373-41a0-bdde-047319c81538.png)

Blue is my watch (also not_home) cyan is my MiBand (also not_home) red is my phone with Home assistant app, (in the correct room)

even the distance is correct for the two wearable.

Hi, im using room-assistant on a raspberry pi, which sees and reports that my Xiaomi Mi Band 4 is at home/room
but espresense shows as not_home.

what can be the problem?

(note: i did setup my phone, and that is shown in the given room just right with espresense, so the config is OK for the watch too.)

some lines from esp32 terminal
Band4:
[17:56:41]1 C# +1 | MAC: d0f10eab14e0, ID: known:d0f10eab14e0                                        -34dBm (0.09m) 76ms
Watch:
[17:56:41]1 C# +1 | MAC: e9b5de977bd4, ID: known:e9b5de977bd4                                        -69dBm (1.10m) 778ms
Phone
[18:05:05]1 New   | MAC: 6c14b8a132f1, ID: iBeacon:3f2fe1df-007f-4af7-b945-b1be3871308a-100-1        -92dBm 

![image](https://user-images.githubusercontent.com/2751780/176485311-0fafa277-ae74-4ce5-bd17-6dae24f1623b.png)

configuration.yaml:

```
# One entry for each beacon you want to track
  - platform: mqtt_room
    device_id: "e9b5de977bd4"
    name: "Zoltans Watch"
    state_topic: "espresense/rooms"
    timeout: 10
    away_timeout: 120

  - platform: mqtt_room
    device_id: "d0f10eab14e0"
    name: "Zoltans MiBand"
    state_topic: "espresense/rooms"
    timeout: 10
    away_timeout: 120

  - platform: mqtt_room
    device_id: "iBeacon:3f2fe1df-007f-4af7-b945-b1be3871308a-100-1"
    name: "Zoltans Phone"
    state_topic: "espresense/rooms"
    timeout: 10
    away_timeout: 120
```

![image](https://user-images.githubusercontent.com/2751780/176484211-2137d374-c68e-4e76-95c2-8ce1668e0dfd.png)
![image](https://user-images.githubusercontent.com/2751780/176484399-b444edeb-e8fd-4fe1-9c71-2a04c6c70041.png)

![image](https://user-images.githubusercontent.com/2751780/176484297-30ceb08d-9742-4bc1-b92c-00eb08175609.png)

Any idea on this ?

**Comment by DTTerastar** [comment]
The id includes the known: portion.  Put into hass the id as "known:d0f10eab14e0"

**Comment by vzoltan** [comment]
Thank you for the quick replay, just before you did answer, i did figure it out :)
and it works.
Thanks again!

**Comment by DTTerastar** [comment]
Please help others by updating the documentation in a way that would have preventing you needing the help!  There is an edit button on every page of https://espresense.com

**Comment by vzoltan** [comment]
ok, Ill do that

however, im at the office now, my amazfit watch is on me, and my miband is at home in the livingroom 
and home assistant shows both at the office.
(office is not in the same building, not even same street ;) )

what could be the issue here, where should i look for logs or clues?

**Comment by vzoltan** [comment]
hm never mind for now, as i see by the change of the distance, its the same device bc it changes for the same value at the same time for both.
ill investigate, and let you know. thanks

**Comment by vzoltan** [comment]
found it, used the same mac/id for both devices, sorry :)

ps: can you give me an exact url to what page you want me to add info to?
thanks

**Comment by michaelmior** [comment]
If your Mi Band 4 is working, it would be great to add it to the [list of known working beacons](https://espresense.com/beacons).

**Comment by vzoltan** [comment]
i just added to the list 
| Xiaomi Mi Band 4     | Yes      |                                             | id format: known:xxxxxxxxxxxx
| Amazfit GTR 2e        | Yes      |                                             | id format: known:xxxxxxxxxxxx

**Comment by michaelmior** [comment]
@vzoltan It appears you did commit to a fork of the website repository on your branch. For changes to be reflected on espresense.com, you also need to [submit a pull request](https://github.com/ESPresense/ESPresense.github.io/compare/master...vzoltan:ESPresense.github.io:patch-2).

**Comment by vzoltan** [comment]
Ok, then someone should add these two lines to that page. sorrry.
