### ISSUE TITLE
Security issue | mqtt Password visible and portal not password protected

### ISSUE THREAD

**Issue by ankycooper** [ESPresense/ESPresense#516]
**Describe the bug**
mqtt password field not masked and it shows the password, also the portal should be password protected enabling anyone on the network to view and tamper the settings.
**Config**

- Version: v2.2.0
- Active scan enabled: yes
- Include filter:
- Exclude filter:
- Query filter:

**Hardware**
ESP32
- Firmware flavor:
- Device (be specific):

**Logs**

If possible, copy and paste any logs from the serial monitor from the time that you see the bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/20620956/176816130-58e9e797-a3cf-432e-856a-7078f1412868.png)

**Comment by vzoltan** [comment]
this is a problem for me too, bc i use one of these devices at work, and if they connect to the esp32s ip, they can see not just the wifi password, but laso my mqtt server address and its password.

**Comment by hellcry37** [comment]
this is not a bug, just not implemented yet

**Comment by ankycooper** [comment]
> this is not a bug, just not implemented yet

Is it planned, if not can it be added as it's a security gap.

**Comment by hellcry37** [comment]
I asked the same some time ago ... , don't even remember where

**Comment by vzoltan** [comment]
ive checked 'Include pre-released versions in auto-update' so lets see.
if no "upgrade" than ill flash it manually later tonight.

**Comment by vzoltan** [comment]
seem ok, i even tried the basic "trick" to see what is the default value (the **********) and its nothjing:)
![image](https://user-images.githubusercontent.com/2751780/177262863-6206696b-483b-476f-8bac-5a4cc90e52a9.png)

**Comment by DTTerastar** [comment]
[v2.2.1b6](https://github.com/ESPresense/ESPresense/releases/tag/v2.2.1b6) fixes the rounding issue.  Thanks for reporting!
