### ISSUE TITLE
HA Auto Detection doesn't work with a space in room name

### ISSUE THREAD

**Issue by davidcoulson** [ESPresense/ESPresense#52]
I have 6 devices that recently upgraded to 1.6.0 - Kitchen, Office and e0378c are all showing in HA, but 'Great Room', 'Dining Room' and 'Master Bedroom' are not. I will try today to remove the space from these other rooms to confirm this is indeed the defect.

**Comment by davidcoulson** [comment]
After changing my device rooms to 'GreatRoom', 'DiningRoom', and 'MasterBedroom' they all appeared in HA, so it seems the space is the issue!

**Comment by DTTerastar** [comment]
Yeah, I need to "slugify" the name when put into MQTT.  I'm afraid it's gonna break people tho.

**Comment by DTTerastar** [comment]
This is fixed in the latest release.
