### ISSUE TITLE
3 devices combined to form 1 device/dashboard and 1 entry for mqtt -BETA

### ISSUE THREAD

**Issue by Anto79-ops** [ESPresense/ESPresense#522]
Hi!

I'm running HAOS Home Assistant 2022.7.0b0 and also, have 4 ESP32 running 2.2.1b3 on 3 of them and 2.2.1 on 1 of them. For whatever reason, the 3 on 2.2.1b3 have combined into 1 device via mqtt and shown here:

![image](https://user-images.githubusercontent.com/79593761/177087353-f0de41d1-1e98-4fac-aec4-6c1226def2c6.png)

not sure how or why this happened. 

MQTT explorer is reporting 4 different devices in homeassisstant/sensors but its all mashed as one device (3 sensors) and 1 in the UI

The MQTT Integration in HA report only 2 ESP32 devices (the 3 and 1), but all are reporting correctly?

this is a strange one to explain be happy to give more informatoin

**Comment by DTTerastar** [comment]
Yes, I just noticed this as well.  I've fixed it in b4.  Coming in 20 minutes...

**Comment by Anto79-ops** [comment]
Awesome, thanks for your efforts here. After it updates, how do I actually fix the combination of entities? Do I need to purge the mqtt entries (using mqtt explorer)?

Cheers

**Comment by DTTerastar** [comment]
Mine are updating, trying a reboot of hass now.  I think that is all that should be needed.

**Comment by Anto79-ops** [comment]
thank you! problem solved. Cheers
