### ISSUE TITLE
Selective HASS MQTT Enrollment

### ISSUE THREAD

**Issue by DTTerastar** [ESPresense/ESPresense#53]
I'm thinking of the following.  Each device will have a "Join" button (just like zigbee).  You press the button to allow joining and the first device brought within 0.5m of that base station will have the device added to Home Assistant via MQTT Discovery.  You then name it in HASS what it really is and repeat to find all your devices.

**Comment by RyanAHolland** [comment]
I love this! Great idea.

**Comment by dcgrove** [comment]
I would be more than willing to do any testing on this you need.

**Comment by corgan2222** [comment]
This is one solution I was thinking above, to make this more usable! I like!

**Comment by czendler** [comment]
Sounds good
Is it possible to add Distance to log also?
