### ISSUE TITLE
Use Watchdog to Avoid Crashes

### ISSUE THREAD

**Issue by rcmurphy** [ESPresense/ESPresense#543]
**Is your feature request related to a problem? Please describe.**
It is frustrating when ESPresense sensors 'freeze' and stop scanning or talking to WiFi.

**Describe the solution you'd like**
Using the [built-in PlatformIO watchdog](https://techoverflow.net/2021/11/09/how-to-enable-watchdog-on-esp8266-esp32-using-platformio/), ensure the system is responsive; otherwise, reboot the ESP.

**Describe alternatives you've considered**
External circuitry to effectively do the same thing, but the functionality is already in the ESP, we just have to use it.

**Additional context**

**Comment by DTTerastar** [comment]
I have looked into this.  The ESP32 Task Watchdog is enabled and will reboot if tasks stop running or checking in.  I've also added an extra watchdog if ble devices currently seen go to zero.  Not sure what else we can do.
