### ISSUE TITLE
EPS32 Disconnecting after a couple of hours

### ISSUE THREAD

**Issue by Bruhildo** [ESPresense/ESPresense#546]
I have been using ESPresence with no issues for some time, but recently (about 4 days ago) each Base Station (I have 2) have disconnected and stop reporting beacons. Base Stations are still connected to WiFi and MQTT but no longer reporting more updates.

MQTT logs do not show anything unusual.

If connected to serial monitor, when issue happens it reports **"scan_evt timeout"** over and over.

Both Base Stations are Generic ESP32 DevBoards and issue is happening with both boards. When issue happens, status light (blue) stops flashing. Red light (power) stills on.

Usually a soft reset (via HA interface) or a hard reset (unplugging or ESP32 Board physical button) solves the issues for another couple of hours.

**Comment by 51av0sh** [comment]
Ditto. This started with 2.2.7.  I've had to restart all my ESPresense base stations four times the last 3 days. Never had this issue with previous versions.

**Comment by Bruhildo** [comment]
I noticed on 2.2.6 but still persists on 2.2.7. I am not sure if it happened before because latest 4 or 5 updates were done in quick succession.

**Comment by maromaro70** [comment]
Yep, 5 nodes, all with terrible reporting within a few hours of restart. Started around 5-6 days ago

**Comment by ASNNetworks** [comment]
Same here, some devices simply don't get listed anymore even after restarts now. Sad after every few updates related bugs like this come back. I think I'm gonna downgrade to a much older version which was rock solid and turn off auto update.

**Comment by uspino2** [comment]
Happening to me too. Solid for months and it just bricks after a few hours.

**Comment by uspino2** [comment]
Turns out it was -in my case- a WiFi issue in my UniFi home network. The ESP32 device insisted on connecting to a far away AP, even though it's literally 2 ft away from another AP. I locked it to that AP and it's been rock solid for the last 48 hours.

**Comment by DTTerastar** [comment]
These last set of updates did update the core Arduino framework, which could cause issues.  If you have a log of scan_evt timeout it would be helpful.  My own testing is actually seeing uptimes in 600,000 seconds which we've never even seen before: 
![image](https://user-images.githubusercontent.com/1491145/179508454-9404d148-6841-4b66-bd0e-14c56638a099.png)

I am wondering if such long uptimes are causing other bugs to surface...

**Comment by Bruhildo** [comment]
Hi @DTTerastar , thanks for the response.

When connected at the terminal via USB, the only info on the logs was "scan_evt timeout" over and over. Before that, logs seems normal, but I could not capture the exact moment when went from normal to "scan evt timeout" as I could not go back on the terminal up to the moment it happened. Is there a different way to capture the logs?

As per uptime, looking at history, usually it stops working at 40000 (average) but this I think reflects when I noticed and reset it. But I also see that I reset quite often at around 15000, so that may reflect better when it stops working.

**Comment by DTTerastar** [comment]
Seems related: https://github.com/espressif/arduino-esp32/issues/5860

**Comment by Bruhildo** [comment]
@DTTerastar I tried again looking at the logs and just drop directly from normal operation to "scan_evt timeout", no other messages (sorry, I was not able to quickly grab a screen shot before it disappeared). 

Besides the beacons reports (New, Left, Close, Del), the only different message on web terminal logs was:
Not updating from (sc=302): https://github.com/ESPresense/ESPresense/releases/download/v2.2.7/esp32.bin

**Comment by DTTerastar** [comment]
I think this is an issue when there's crazy amounts of advertisements.  Do you like somewhere high density with lots of BLE around you?

**Comment by Bruhildo** [comment]
I just enable "prerelease" on one of the base stations and left the other normal version (to compare if needed).

Thanks a lot for that.

**Comment by Bruhildo** [comment]
As feedback, I got prerelease version 2.2.8 yesterday and still stopping after a few hours and reporting "scan_evt timeout".

**Comment by DTTerastar** [comment]
OK.  I'm going to investigate a way to use watchdog to at least work around this until we can figure it out.

**Comment by Bruhildo** [comment]
After some digging this weekend and review of the configuration of the base stations, I noticed that “Request scan results” was turned on. After I turned off there was no more drops.

This was not an issue before latest updates (since it was likely checked on since I first installed without issues), but turning off seems to have resolved the issue. I am without issues for 2 days already.

**Comment by mwhdc** [comment]
No logs handy, but anecdotally I've been seeing this behavior too, on multiple M5Stack Atom Lites with both the vanilla and sensors builds of 2.2.7. After about a day of uptime, the ESP32s remain pingable and reachable via HTTP, and continue to report telemetry, but stop reporting devices. The issue isn't 100% reproducible, though - one of my ESP32s has been reporting like a champ for over 5 days.

**Comment by DTTerastar** [comment]
3.0b1 has a work around for this.  If the known devices drops to zero we reboot.  I'm pretty sure it's an issue in the Arduino framework and i am also testing the newest version to see if it fixes it.

**Comment by Bruhildo** [comment]
Thanks @DTTerastar . V3.0.0b0 was dropping about once a day (without “Request scan results” turned on). 

I have not seen a drop on V3.0b1 since you pre-released it.

**Comment by Buckeyes1995** [comment]
I am seeing something similar with the latest beta.  When I get up in the morning, the com port is locked and I have to restart the ESP32 to get it going again.  Any thoughts?  I left it connected to putty this morning so will report if I see anything prior to it happening again.

**Comment by DTTerastar** [comment]
Do you have request scan response turned on?

**Comment by Buckeyes1995** [comment]
I do not.  Woke up this morning and had to reboot.

**Comment by DTTerastar** [comment]
v3 is out and I think this is resolved, can you confirm?

**Comment by Buckeyes1995** [comment]
Oh sorry, I haven’t noticed this recently.  All good.

**Comment by sami1369** [comment]
> After some digging this weekend and review of the configuration of the base stations, I noticed that “Request scan results” was turned on. After I turned off there was no more drops.
> 
> This was not an issue before latest updates (since it was likely checked on since I first installed without issues), but turning off seems to have resolved the issue. I am without issues for 2 days already.

Hi Thank, 
I have same problem 

Where is “Request scan results” ? 

would you elaborate on more details?

**Comment by Bruhildo** [comment]
> > After some digging this weekend and review of the configuration of the base stations, I noticed that “Request scan results” was turned on. After I turned off there was no more drops.
> > This was not an issue before latest updates (since it was likely checked on since I first installed without issues), but turning off seems to have resolved the issue. I am without issues for 2 days already.
> 
> Hi, I have the same problem
> 
> Where is “Request scan results”?
> 
> would you elaborate on more details?

@sami1369 This was on an older version. As I see, this option is no longer available. Also, the issue I was facing was resolved after a new version was pushed. Maybe your issue is caused by something different than the one I had.

**Comment by sami1369** [comment]
> > > After some digging this weekend and review of the configuration of the base stations, I noticed that “Request scan results” was turned on. After I turned off there was no more drops.
> > > This was not an issue before latest updates (since it was likely checked on since I first installed without issues), but turning off seems to have resolved the issue. I am without issues for 2 days already.
> > 
> > 
> > Hi, I have the same problem
> > Where is “Request scan results”?
> > would you elaborate on more details?
> 
> @sami1369 This was on an older version. As I see, this option is no longer available. Also, the issue I was facing was resolved after a new version was pushed. Maybe your issue is caused by something different than the one I had.

What version did you use?
I still have this problem?
