### ISSUE TITLE
Problems connecting to Nest-Wifi netrork

### ISSUE THREAD

**Issue by bogorad** [ESPresense/ESPresense#551]
**Describe the bug**

I have a Nest-Wifi network, one Nest master, and two google-wifi slaves. By (Google's) design, they all have the same SSID. I have many m5stack-atom-lite devices in different rooms. I set them up in my office, then carry them to the destination room. Most work great, but some just won't connect to wifi. But when I return them to my office, they work fine. It looks like ESPresence stores the MAC address and not the SSID. Which is a problem in the case of Nest/Google-wifi. Can you at least show MAC addresses in the network setup drop-down?

UPD: Tasmota32 on these same units doesn't have this problem, so it's probably not hardware-related.

**Config**

- Version: v2.2.7
- Active scan enabled: no
- Include filter: yes
- Exclude filter: no
- Query filter: no

**Hardware**

- Firmware flavor: ??
- Device (be specific): M5stack Atom Lite

**Comment by onlyoneme** [comment]
I have access point and an extender with the same SSID and different BSSIDs derived from MACs. My espresense devices have no issue connecting any of them, so I guess there must be another reason for your wifi problems.

**Comment by DTTerastar** [comment]
I specifically don't store the BSS in nvs so the station shouldn't get sticky: https://github.com/ESPresense/ESPresense/blob/b298730daade3ee6d7de1ee053e3b5b42af41245/src/main.cpp#L137

If you used old firmware before I added that it's possible you still have an old value in your nvs.  If you check the "erase" option and reflash it should blow it away.

**Comment by jeffreyameyer** [comment]
I believe this may be an issue with the esp wifi drivers, but I'm having the same issue with Google Wifi. Info below & cross-posted at:

Hi - adding to this thread here with an additional use case: trying to get ESPresence working with a Google WiFi network (no control over 2.4GHz / 5GHz bands, multiple 2.4GHz BSSIDs). In this environment, if I successfully set up a device in my office and then try to move it to another room, there's a *very* small chance it will wake up and associate properly. If I instead go to a physical location where I plan to deploy an ESP32 sensor and then reset the wireless from there, I can improve those odds, but it would be nice to be able to just give an SSID and have the ESP32 manage across all the different BSSIDs associated with that SSID.

My ESP: AITRIP 5PCS ESP-WROOM-32 ESP32 ESP-32S Type-C USB

Here's a little more info on my network and my setup:
<img width="537" alt="esp32_boot" src="https://user-images.githubusercontent.com/1494546/183491814-ad2044c1-7d1b-45c7-afce-9d1db1065337.png">

<img width="163" alt="esp32 6 SSID list" src="https://user-images.githubusercontent.com/1494546/183491839-8536e234-d7ad-422b-9669-40d0ad488541.png">

<img width="476" alt="google_wifi_macs" src="https://user-images.githubusercontent.com/1494546/183491867-31b62f20-1ede-469d-bf6b-95328dddc800.png">

**Comment by Diddlik** [comment]
I have the same problem with Unifi Access point. it is trying to connect and break with this error message:
![grafik](https://user-images.githubusercontent.com/6010713/184234365-f6c8866e-a0b6-419b-816d-c4140ac70f70.png)
If I do the WiFi scan, than I have the same picture as [jeffreyameyer](https://github.com/jeffreyameyer)

**Comment by DTTerastar** [comment]
I have unifi and it's working for me.

**Comment by onlyoneme** [comment]
Maybe there are roaming issues there. Or esp device doesn't try to connect to another AP with the same SSID when the preferred (with strongest signal) one denies to connect on startup.

**Comment by Diddlik** [comment]
> I have unifi and it's working for me.

do you have multiple AP? I have 4 of them and under wifi scan epresence shows me 4 time my ssid

**Comment by DTTerastar** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#esp32-wi-fi-station-connecting-when-multiple-aps-are-found

I see mention of WIFI_ALL_CHANNEL_SCAN vs WIFI_FAST_SCAN.  Maybe that's the option we want?

**Comment by DTTerastar** [comment]
https://github.com/espressif/arduino-esp32/blob/cf01523ded6d40e6feaa92b9aa647e5553148b60/libraries/WiFi/src/WiFiSTA.cpp it looks to me like WIFI_ALL_CHANNEL_SCAN is the default already.

**Comment by DTTerastar** [comment]
Nm: https://github.com/espressif/arduino-esp32/blob/cf01523ded6d40e6feaa92b9aa647e5553148b60/libraries/WiFi/src/WiFiSTA.h#L69

**Comment by Diddlik** [comment]
@DTTerastar that means in the next release it should be fixed?

**Comment by jeffreyameyer** [comment]
@DTTerastar - thank you! Looking forward to the update.

**Comment by Diddlik** [comment]
@DTTerastar Just tested new beta (3.0b6), for me the problem still exist

**Comment by DTTerastar** [comment]
> @DTTerastar Just tested new beta (3.0b6), for me the problem still exist

I can only do what the apis provided by Esspressif allow.  Not sure what else I can do.

**Comment by Diddlik** [comment]
> > @DTTerastar Just tested new beta (3.0b6), for me the problem still exist
> 
> I can only do what the apis provided by Esspressif allow. Not sure what else I can do.

I found the problem. If I remove special charackters from WiFI password, for example _ or ! than I can connect to WiFi.

**Comment by DTTerastar** [comment]
A bug about exactly what char is causing issues would be awesome so at a minimum we have it documented

**Comment by Diddlik** [comment]
I will do in next days more tests and than create an issue
