### ISSUE TITLE
Adding Apple Watch Lock/Charging detection

### ISSUE THREAD

**Issue by GenericRyan** [ESPresense/ESPresense#558]
**Describe the solution you'd like**
The Apple Watch broadcasts whether it is Locked or Unlocked in the Nearby Info Message, detection of this in ESPresense would enable marking the watch as not_home (or locked) when it is charging or not being worn.

**Describe alternatives you've considered**
Currently I have implemented a basic form of this through a separate MQTT sensor that extracts the required section from the "disc" field. I then use this as a condition in my HA Automation for creating the device_tracker, so the Home state  isn't updated if the watch is locked. Similar conditions used for lights etc.

**Additional context**
This link is where I got the idea for this from: https://github.com/dalehumby/ESPHome-Apple-Watch-detection

My sensor tested working successfully with both Apple Watch Series 3 and Series 6.
```
mqtt:
  sensor:
    - name: "Apple Watch Series 3 Lock Status"
      state_topic: "espresense/devices/apple:1005:9-24/#"
      value_template: >-
        {% if value_json.disc[2:4] == '98' %} Unlocked
        {% elif value_json.disc[2:4] == '18' %} Locked
        {% else %} Away {% endif %}
```

![Apple Watch](https://user-images.githubusercontent.com/105532326/179657127-ea6acd98-815a-4d9d-b276-e2b0276b9102.jpg)

Having this dealt with upstream on the ESPresent device would be a better solution, possibly with a settings boolean to choose if it is active or not:
Off = Current setup, always tracked.
On = Marks it as not_home if locked.

Unfortunately I don't have the programming knowledge to do this myself, happy to provide any additional information or testing if I can however.

**Comment by DTTerastar** [comment]
Yeah, i've been thinking about doing this myself as well.

**Comment by krazos** [comment]
This is a great idea, and I have borrowed the MQTT lock/unlock sensor concept to make my room detection a little smarter.  I agree that this would be a nice feature to add to ESPresense.

**Comment by birdofhermes** [comment]
Is this only working with the non querried (e.g.:apple:1005:9-24) topics?
I have performed a reporting of my Watch6 overnight on the charger stand and during the day on my wrist and this is what i got 15962 reported disc addresses. The AW6 starts with a 2 than a random hexadecimal character and than 18 and the rest is also having all 16 available characters. It was not differentiating if the watch was on the charger or not, but i use the querry do translate the 9-24 to the apple:watch6-4.

**Comment by krazos** [comment]
To the extent this feature has not already been implemented, I would propose re-opening this issue/enhancement request.
