### ISSUE TITLE
Allow bluetooth pairing for espresence

### ISSUE THREAD

**Issue by thatnokiaguy** [ESPresense/ESPresense#562]
**Is your feature request related to a problem? Please describe.**
Wear os does not offer any beacon i know of. solution to this would be to allow people to pair a device directly to espresence. would also possibly help to make it more accurate as the device may be more ikely to respond
**Describe the solution you'd like**
allow us to pair bluetooth devices to the board
**Describe alternatives you've considered**
i sideloaded a beacon app onto my watch, which failed miseravly
**Additional context**

**Comment by DTTerastar** [comment]
The prerelease/beta has this.  Press Enroll and ESPresense looks like a Heart Rate Monitor long enough to pair with.

**Comment by thatnokiaguy** [comment]
Ah. Thanks for letting me know

**Comment by thatnokiaguy** [comment]
> The prerelease/beta has this. Press Enroll and ESPresense looks like a Heart Rate Monitor long enough to pair with.

im unable to even get it to update to beta

**Comment by thatnokiaguy** [comment]
> > The prerelease/beta has this. Press Enroll and ESPresense looks like a Heart Rate Monitor long enough to pair with.
> 
> im unable to even get it to update to beta

ok, managed to update it however cannot find enroll button, any idea?

**Comment by PuckStar** [comment]
I'm on version 2.2.8b2 but when scanning for BT devices on my phone I don't see anything that looks like Espresense.

**Comment by ASNNetworks** [comment]
> The prerelease/beta has this. Press Enroll and ESPresense looks like a Heart Rate Monitor long enough to pair with.

Can you explain how this works? I tried pairing (I could find the device) but after adding my phone says it needs an app in order to connect. Also, with having 4 base stations, should I pair to each of them?

**Comment by linglingpin** [comment]
If you're using Home Assistant, the Enroll button is on the ESPresense device page.

**Comment by ASNNetworks** [comment]
> If you're using Home Assistant, the Enroll button is on the ESPresense device page.

Not sure if your comment was towards me, but as I stated: I can see the device (so I know how to use enroll to pair). That's not my question. After pairing my phone popups a message saying I need a an app to connect.

**Comment by linglingpin** [comment]
> > If you're using Home Assistant, the Enroll button is on the ESPresense device page.
> 
> Not sure if your comment was towards me, but as I stated: I can see the device (so I know how to use enroll to pair). That's not my question. After pairing my phone popups a message saying I need a an app to connect.

After pairing, you should see the irk in the logs. You can use that to identify your iPhone from now on, and you can also unpair your phone with it.

**Comment by ASNNetworks** [comment]
> 

After pairing my phone popups a message saying I need a an app to connect.

**Comment by PuckStar** [comment]
> If you're using Home Assistant, the Enroll button is on the ESPresense device page.

Can we also add that button manually somehow?  Because [I couldn't get ESPresense device to automatically show](https://github.com/ESPresense/ESPresense/discussions/564) up in Home Assistant and had to do it manually.

**Comment by jasiowy** [comment]
I paird samsung note 10+ and everything is working fine. He sends continuous messages in MQTT topic. Unfortunately, samsung s20 fe after pairing sends messages only when I use bluetooth, e.g. by connecting the speakers. Doesn't send messages continuously.

**Comment by PuckStar** [comment]
I'll repeat myself just so my idea doesn't get lost: 
Wouldn't it be possible to just "see" bluetooth devices (on MAC address) just like [Monitor ](https://github.com/andrewjfreyer/monitor) does?

Then we don't need to pair anything and it works well.

**Comment by ASNNetworks** [comment]
> I'll repeat myself just so my idea doesn't get lost: Wouldn't it be possible to just "see" bluetooth devices (on MAC address) just like [Monitor ](https://github.com/andrewjfreyer/monitor) does?
> 
> Then we don't need to pair anything and it works well.

That's litterally the whole point of ESPresense, have you even looked at the readme and setup? The issue is that some devices (mainly iPhones and some Android phones) use random mac addresses, which makes other scanning options needed, like pairing or an app.

**Comment by PuckStar** [comment]
> > I'll repeat myself just so my idea doesn't get lost: Wouldn't it be possible to just "see" bluetooth devices (on MAC address) just like [Monitor ](https://github.com/andrewjfreyer/monitor) does?
> > Then we don't need to pair anything and it works well.
> 
> That's litterally the whole point of ESPresense, have you even looked at the readme and setup? The issue is that some devices (mainly iPhones and some Android phones) use random mac addresses, which makes other scanning options needed, like pairing or an app.

Yes I did read it and understand how it works. And yes I read that about random addresses. 
But what I was trying to say is that apparently the "Monitor" tool is able to track those kind of devices just fine. So without pairing or an additional application it apparently is "seeing" the fixed Bluetooth MAC address of the device just fine.

As example my Samsung A50 is perfectly tracked by "Monitor" however ESPresense seems to look at something else, namely the randomized ID. Perhaps the randomized ID's is part of the BLE broadcasting while my device already also can broadcast a fixed MAC address.

So that is why I am wondering if ESPresense could also not as well look at that fixed Bluetooth MAC address. I hope you understand what I'm saying.

**Comment by DanielBaulig** [comment]
The "heart rate monitor" name should include the set ESPresense room name, to easier identify and distinguish by different paired ESPresense sensors.

**Comment by DanielBaulig** [comment]
Note: when I try to enroll my Apple Watch with the ESP connected via serial bus, I get a "Encrypt connection failed conn" message. No `irk:<id>` or `settings/alias` entries show up in mqtt.

**Comment by DTTerastar** [comment]
The reason I don't add the room name is BLE has very tight limits on the number of characters and you really aren't pairing to a particular room, we send it to all devices via mqtt.

Apple watches refuse to bind securely.  I tried long and hard... But you can discover your watches IRK from the iCloud Keychain.  #580 has some info on how to do it.

**Comment by blacknell** [comment]
The enrol worked like a charm on my iPhone 13. But when I then went to so same on my wife's iPhone X I get nothing in MQTT `espresense/rooms` or `espresense/devices`.

I paired her phone to one of my espresense instances fine (just as with mine). But then nothing in MQTT `rooms` or `devices` showing a new `irk:` entry. I've tried a few times.

I do get a new entry under `espresense/settings` with an empty config (mine is there too, but with a config id equally my irk)

It's rather confusing. Is there some espresense documentation we can review and/or contribute to?

**Comment by blacknell** [comment]
also, is the irk entry on the device html config screen a list of known irks against which to filter? ie an allow list?

**Comment by DTTerastar** [comment]
yes, the whole thing is confusing atm.  I am working on making the GUI make enough sense that extensive documentation won't be needed.

**Comment by DTTerastar** [comment]
> also, is the irk entry on the device html config screen a list of known irks against which to filter? ie an allow list?

No it's just a way of putting in a known irk.  I may delete it because I plan on adding a whole gui to make it possible to add a known irk on the "devices" page.

**Comment by blacknell** [comment]
I now have a 3rd device (iphone 6s) added but not showing up on `espresense/devices`. It too published an empty document to `espresense/settings`

Once again the pairing was very straightforward.

I'm not clear on what the `espresense/settings` documents are used for

**Comment by blacknell** [comment]
> 

I can't explain why the document is empty but when I put the irk into the document (as I suspect it should be), and reboot the various ESP devices, then they start being shown up in rooms/devices

**Comment by blacknell** [comment]
On a related note, is there a way to reboot all ESPpresense devices in the network at once. Do all the devices subscribe to a group topic (such as they can do in tasmota) so I can broadcast a `/reboot` payload

**Comment by blacknell** [comment]
.

> 

@DTTerastar should i create a new issue to reflect this bug? I can't add the bug tag to this issue

**Comment by DTTerastar** [comment]
> On a related note, is there a way to reboot all ESPpresense devices in the network at once. Do all the devices subscribe to a group topic (such as they can do in tasmota) so I can broadcast a `/reboot` payload

Yes, use room as * and they'll all do it.
