### ISSUE TITLE
Allow explicit inclusion/exclusion of device ID prefixes

### ISSUE THREAD

**Issue by mwhdc** [ESPresense/ESPresense#58]
Thanks for the awesome work on this project. I just upgraded my deployment from a couple of random dev boards to a batch of Atom Lites.

Please consider adding the ability to specify the device ID prefixes that should not (or should) be reported to the MQTT server. This feature could be exposed to the user on the config page as an initially empty text field and radio buttons for exclude (default) and include. Prefix entries would be space- or comma-delimited.

I have two sets of Sonos speakers that are constantly spamming the MQTT stream with BLE pings that have no practical use and can't be disabled. I would love to be able to exclude "sonos" (i.e., sonos:*) devices from being reported. Others may want to allow only Apple devices, filter out Covid contact tracing pings, etc.

**Comment by ivanvach** [comment]
I second that. It would be a very useful feature if and when implemented.

**Comment by DTTerastar** [comment]
ok, so if I do this, should it be regexs or globs?

**Comment by ivanvach** [comment]
Regex would be more universal and powerful but for the task at hand I think that globs will do just fine plus easier to use for non programmers.

**Comment by ee02217** [comment]
This would be great. As this makes my headset change profile momentarily and thus generating a click noise :(

**Comment by corgan2222** [comment]
Created a PR to add this Feature based on basic ID Filtering before sensing the MQTT Message.
https://github.com/ESPresense/ESPresense/pull/152
