### ISSUE TITLE
Charateristics Query?

### ISSUE THREAD

**Issue by vekexasia** [ESPresense/ESPresense#581]
**Describe the bug**

I would like to know how the charateristics query exactly works. I added a device id which is a miflora device I know it's working. 

I get the device information from the device but i dont see any data in mqtt.

**Config**

- Version: 2.2.9
- Active scan enabled: no
- Include filter: no filter
- Exclude filter: no filter
- Query filter:  no filter

**Hardware**

- Firmware flavor:
- Device (be specific): m5stack stick

**Logs**

irrelevant?

**Screenshots**

![image](https://user-images.githubusercontent.com/200523/183375761-30da6275-a2e9-4258-98e0-23383e7e9d74.png)

**Comment by DTTerastar** [comment]
We ask for Name and Model number.  If we get a response we update the id.  It's not for miflora.  There is a separate issue for adding that support.  Home Assistant bluetooth also supports it out of the box now (That's how I have mine hooked up atm)
