### ISSUE TITLE
Support for Hidden WiFi

### ISSUE THREAD

**Issue by idaence-dfi** [ESPresense/ESPresense#593]
Hi, the current Version of ESPresence only supports named Wifis. I have different hidden Wifis in my Home and I want to see an Option to insert my Wifi Configuration manual. 

there was a Pull Request on ESP-Wifisettings but I think the WiFi engine has changed on the Version 3.
https://github.com/ESPresense/ESP-WiFiSettings/pull/1

Is their any option to add hidden wifis to the Configuration Page? 

I hope I would love to see this option on a future release, if there is any other way i can insert my wifi configuration i would test them in my network.

thanks and regards,
Daniel

**Comment by DTTerastar** [comment]
The latest beta allows you to select Wifi SSID manually after flashing via webtools.

**Comment by idaence-dfi** [comment]
Thanks, works like a charm! :) Tested on 6 Devices! :)

**Comment by jonny190** [comment]
> The latest beta allows you to select Wifi SSID manually after flashing via webtools.

Ive just tried this but on the ESP32 C3 when the device connects to windows it shows as a unknown device 
![image](https://github.com/ESPresense/ESPresense/assets/8059327/5fd311fc-a5d5-4d0d-a6e7-cc30d16d3fb0)

**Comment by emilianox** [comment]
Hi @idaence-dfi 

I saw your comment form connecting to a hidden SSDI. I’m trying to do the same but can’t find this option.

is there any chance that you please provide more details how to do it?

Thanks in advance!

**Comment by jonny190** [comment]
I managed via Matt commands ... However I ended up switching to esphome and Bermuda plugin in home assistant

**Comment by emilianox** [comment]
@jonny190  thanks man, really appreciated!
