### ISSUE TITLE
ESPresense not seeing beacon

### ISSUE THREAD

**Issue by emeybee** [ESPresense/ESPresense#597]
**Describe the bug**

I was using an iBeacon with ESPresense. I had it all set up and it worked fine. The beacon stopped working so I ordered another of the same model from the same company. This new one is seen by apps like nRF Connect, but it is not seen by ESPresense and does not appear in any MQTT messages. I didn't have to change any settings on the first one for it to be picked up, so I don't know why it isn't picking this new one up.

**Config**

- Version: Was 2.2.9 but tried downgrading one to 2.1.2 and that didn't work either.
- Active scan enabled: I normally have it off but I tried turning it on and it didn't help.
- Include filter: Empty
- Exclude filter: I normally have all my other non-iBeacon devices listed but also tried clearing that and it didn't help.
- Query filter: Empty

**Hardware**

- Firmware flavor: Standard
- Device (be specific): BC068TI iBeacon from Blue Charm Beacons

**Logs**

If possible, copy and paste any logs from the serial monitor from the time that you see the bug. 

**Screenshots**

**Comment by DTTerastar** [comment]
Can you post a screenshot of the advertisements in nRF Connect?  Super weird.

**Comment by DTTerastar** [comment]
Were you able to look into this at all?
