### ISSUE TITLE
Automatic downgrade?

### ISSUE THREAD

**Issue by wenjiavv** [ESPresense/ESPresense#601]
I upgrade the  EPS32 to the lastest pre-release version (3.0.0b6). The configuration page shows the version is 3.0.0b6 and i fiil the blank in Sacn section with my iphone IRK. it works perfectly after restart,.The mqtt is connected and HA shows the correct loaciotn.

After all set, i deplug the ESP32 and put it somewhere else in my livingroom and plug again, then i leave the room. When i return the room i find the status of iphone keep showing not_home. i check the configuration page and find the **version is v2.2.9**, and the IRK blank is missing. However in MQTT, it still shows v3.0.0b6.

i am not true if it's a bug or i just did something wrong. 

![image](https://user-images.githubusercontent.com/79917535/185784589-b4c8e304-bb92-4d19-a5e7-06491663edfe.png)

![image](https://user-images.githubusercontent.com/79917535/185784579-a035b6b2-2b41-4fa8-ba20-0254f826760e.png)

**Comment by DTTerastar** [comment]
Turn off auto update OR turn on allow prerelease.  That should fix it.

**Comment by wenjiavv** [comment]
> 

thanks a lot. it works perfectly now.
