### ISSUE TITLE
Add device name to all HTML pages for easy reference during enrolment, scanning, etc

### ISSUE THREAD

**Issue by RaoulSargent** [ESPresense/ESPresense#606]
**Is your feature request related to a problem? Please describe.**
When using the /devices and /devices/fingerprints screen it is easy to forget which device you are connected to as there is no indication of the device hostname on the display.
The <title> of these pages, thus the browser tab, has the static text "ESPresense: devices" and therefore does not help either when you have multiple devices open at the same time.

**Describe the solution you'd like**
Please add the device name, hostname, to the /devices and /devices/fingerprints screens.
Perhaps just in the left-hand pane, under the existing "ESPresense" logo.
It would also be handy to have the IP address, and version info displayed here as well.

**Describe alternatives you've considered**
Although the name could be part of the html <title> and hence displayed in the browser tab, it would be truncated and not always visible.

**Additional context**
I currently have 8x devices (more to be deployed shortly) and when making changes to several, or choosing one for an enrolment, it is easy to forget which tab is which device.
When viewing the fingerprints screen of multiple devices to triangulate beacons there is no indication of which screen is which esp device.

Whilst not a critical feature, just feel it would greatly ease usability whilst being a minor effort to implement.

**Comment by DTTerastar** [comment]
Yup, planned.  It's a SPA so I need to add it to the title once the json comes back.
