### ISSUE TITLE
"Known" devices filtering not working in 3.0.x betas

### ISSUE THREAD

**Issue by onlyoneme** [ESPresense/ESPresense#607]
I use "known" devices filtering in 2.2.9 to limit data published on MQTT. It looks like below:

Known BLE mac adresses: 0117c597ccd1 0117c5970775  (...)

Include only sending these ids: known:

Unfortunately it doesn't work at all with 3.0 betas.

**Comment by DTTerastar** [comment]
Crap, I definitely changed that area with the irks stuff so thanks for the bug report.

**Comment by DTTerastar** [comment]
If you remove the filtering does the id come across correctly?

**Comment by onlyoneme** [comment]
Problem is with "Known BLE mac adresses" section. My beacons are no longer detected by mac address.

**Comment by onlyoneme** [comment]
Confirmed.
