### ISSUE TITLE
PWM seems to be always PWM inverted in v3.0.0b9

### ISSUE THREAD

**Issue by antongiacomo** [ESPresense/ESPresense#609]
I have a led connected on the gpo13. The control of the led by home assistant works but is reversed. if I set the brightness to 0 I get it maximum and vice versa. The same happens by turning the LED off and on, if I turn it off it turns on (The led works well on Esphome wled Wled).

Changing the setting from PWM to PWM Inverted does not seem to have any effect.

The logged data are the correct ones.

**Hardware**

- Firmware flavor: Standard
- Device (be specific): ESP32-Cam (ESP32-D0WDQ5)

**Logs**
```
1 MQTT  | Set led_1: {"state":"ON","brightness":115}
1 MQTT  | Set led_1: {"state":"ON","brightness":135}
1 MQTT  | Set led_1: {"state":"ON","brightness":255}
1 MQTT  | Set led_1: {"state":"ON","brightness":3}
1 MQTT  | Set led_1: {"state":"OFF"}
```

**Screenshots**

![ScreenShot-20220825-065651](https://user-images.githubusercontent.com/28866587/186578428-cc8e6036-d42e-4f1d-aea0-83d04e3e7c7f.png)

**Comment by DTTerastar** [comment]
Yup, can confirm

**Comment by antongiacomo** [comment]
I've tried to spot the problem but what I saw seemed okay.

**Comment by DTTerastar** [comment]
I figured it out, it'll be in the next release.
