### ISSUE TITLE
Wifi connection failed when special character is used

### ISSUE THREAD

**Issue by Diddlik** [ESPresense/ESPresense#614]
I did several tests and found,

if I have a "!" character at the end of my WiFi password, then esp32 does not connect to WiFi. It is important that ! is at the end, if it is in the middle of the password, then everything works.
Does not work: abcdeF45!
Goes: abcd!eF45

**Comment by DTTerastar** [comment]
Man I have ! at the end of almost all my passwords.  That's got to work!

**Comment by DTTerastar** [comment]
I just made me a IOT wlan with a password that ends in ! and guess what, it worked perfectly!  I'm not sure what I can unless others experience it.

**Comment by janssenjones** [comment]
I just wanted to confirm that I have six of these running, and every single one connects to an SSID that has a password ending with an exclamation point.  There must be something else happening...

**Comment by DTTerastar** [comment]
Passwords with ! at the end are the best :)

**Comment by Diddlik** [comment]
I have an update to this bug. If I setup espresence WiFi with Web Tool (after Flashing, they ask me to setup WIFI), in this case WiFi with special character works fine. If I setup WiFi over Access Point from ESP32 (after flashing) than it does not work.
