### ISSUE TITLE
How do i find the Apple iPhone model when i want to set a filter. I have iPhone 10. Bur how Can i find about the model is 10-3 og 4 or 5 .......

### ISSUE THREAD

**Issue by Mindkey75** [ESPresense/ESPresense#617]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by janssenjones** [comment]
This answer is not ideal, and things are still a bit in flux and changing.  You can find out a bit more info here:
https://espresense.com/configuration/settings#querying 

But in short, you basically want to go the configuration page and enter that string into the text box that says:
"Query device ids for characteristics (eg. apple:1005:9-26):"

And then save and restart the devices.  It'll then start making a secondary query that reports a new name (e.g. apple:watch6-4).

You may still get overlap, depending on if there are multiple running instances of iPhones or iPads or watches or whatever in your house.  A new system is coming to uniquely capture each device (using irk), but that's in the beta versions, and is still a bit finnicky.

More docs should be on the way soon for some of those things.

**Comment by Mindkey75** [comment]
Thank you it works perfect now👍🏻


 Mvh Morten Henriksen

Den 30. aug. 2022 kl. 17.02 skrev Darrell ***@***.***>:

﻿

Docs are now released and refactored. v3 is out. You need to press the Enroll button and connect to it via the Bluetooth screen and we should be able to track it uniquely.
