### ISSUE TITLE
B10 no fresh install possible

### ISSUE THREAD

**Issue by theimo1221** [ESPresense/ESPresense#618]
**Describe the bug**

Using an of the shelve esp32 it is not possible to directly install b10.

**Hardware**

- Device (be specific): https://www.amazon.de/-/en/gp/product/B074RG86SR/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

Installing the latest v2.x works like a charm

**Comment by DTTerastar** [comment]
I am sometimes seeing the wifi setup getting stuck but the node still flashes correctly.  Can you screenshot exactly where things are going wrong?

**Comment by theimo1221** [comment]
Will try tomorrow and give you feedback 👍
