### ISSUE TITLE
[Enhancement] - improve config portal with device list 

### ISSUE THREAD

**Issue by ee02217** [ESPresense/ESPresense#62]
It would be great to have in the configuration portal a list of the seen devices as well as the ones being reported at the moment. 

This would allow to not have to use mqtt to check all devices, but see it in a convenient place. 

Tasmota has a similar feature:

![](https://tasmota.github.io/docs/_media/ibeacon_success.jpg)

**Comment by ee02217** [comment]
this would allow for easier addition of new devices, at least if we had the id and the time of “first seen”

**Comment by DTTerastar** [comment]
Yeah, I'm liking this idea.  It might be better than my other idea to "Join" when a device comes near.  We could instead just have a button to add to HASS Discovery.

**Comment by DTTerastar** [comment]
Some devices have special abilities like BlueCharm has buttons, and motion, so that would also make it easier to specify that when adding.
