### ISSUE TITLE
Firmware: v3.0.2 Radar Timeout values  not shown in HA.

### ISSUE THREAD

**Issue by webhostsg** [ESPresense/ESPresense#633]
**Describe the bug**
Radar Timeout  values  not shown in HA   

**Config**
- 
- Version: v3.0.2

**Hardware**

- Firmware flavor:
- Device (be specific):

**Logs**

If possible, copy and paste any logs from the serial monitor from the time that you see the bug.

**Screenshots**
![CleanShot 2022-08-31 at 04 05 45](https://user-images.githubusercontent.com/59085206/187533242-5942bbc0-6294-4dcb-ba75-eadd6d4d2345.png)

**Comment by DTTerastar** [comment]
Fix should be up at https://espresense.com/alpha in about 10 minute for you to test

**Comment by webhostsg** [comment]
@DTTerastar I don't see the fix in the alpha, v3.0.4 did not fix it.

**Comment by webhostsg** [comment]
@DTTerastar ok tested on a spare ESP32, seems that the fix worked. 
![CleanShot 2022-09-02 at 21 01 32](https://user-images.githubusercontent.com/59085206/188151680-c17ac90a-e05a-4a1e-a401-156fe835ed39.png)
