### ISSUE TITLE
incompatible Hardware?

### ISSUE THREAD

**Issue by AgentHawk** [ESPresense/ESPresense#637]
Hey

its not a bug i Guess but is my "Hardware" not compatible?

Im using ESP32 from AZDelivery (ESP32 NodeMCU Module WLAN WiFi Dev Kit C Development Board with CP2102)

Sometimes I move the room but HA stays in the odl room.

quick look at the logs - 0 Reconnecting to MQTT...    ///    0 Reconnect timer

**Comment by el97** [comment]
Looks like the same issue as #628

**Comment by DTTerastar** [comment]
Have you tried to reflash via serial?

**Comment by AgentHawk** [comment]
yeah - the new 3.0.3 fixed the issue

**Comment by DTTerastar** [comment]
So we can close?

**Comment by AgentHawk** [comment]
yes.
