### ISSUE TITLE
Apple Watch recognition stuck

### ISSUE THREAD

**Issue by AgentHawk** [ESPresense/ESPresense#640]
Hey

noticed the behavior in the beta aswell.

It works if you start the ESP for a couple of Minutes. Sometimes more. And if you leavin or turning the BT off and on its like he ignores the Watch completly. Nothing via WebTerminal same with mqtt.
Not a single ping from the Watch.

But if you restart espresence everything works as usual.

3.0.3
ESP32 WROOM-32

**Comment by AgentHawk** [comment]
Reproducible

Start ESPresence - Turn Off BT on your Watch - turn it back on - Blacklisted - restart fixed the issue

**Comment by DTTerastar** [comment]
How long do you need to turn off BT on the watch?

**Comment by AgentHawk** [comment]
IRK via Apple Keychain.

BT is off and on (maybe 1 or 2 sec)

**Comment by DTTerastar** [comment]
I found the issue. Please try updating to the alpha via http://espresense.com/alpha

**Comment by AgentHawk** [comment]
Yep! Nice Work.
