### ISSUE TITLE
ESPresense stop detecting iPhone after receiving the call or making the call

### ISSUE THREAD

**Issue by pk802** [ESPresense/ESPresense#641]
ESPresense stop detecting iPhone after receiving call or making the call. I have tested on iPhone 13 Pro and iPhone 11. To start detection again there are 2 ways. 
- I have to turn off and turn on again iPhone's bluetooth. 
- Restart ESP32. 

Detection was working perfect till V2.2.9. even when I receive or make the call. 
I have 4 ESP 32 and all are having the same problem. 

I have tested this using ID and IRK. Both stops updating in MQTT Explorer as soon as I receive or make call. It also delete device from web terminal. If I restart ESP32 or iPhone's Bluetooth, ID and IRK works as expected and devices comes back on MQTT and Web terminal.

I have 
- Version: 3.0.3
- Active scan enabled: No
- Include filter: No
- Exclude filter: No
- Query filter: No

- Device: ESP32-WROOM

**Comment by ziolelle** [comment]
In my case I found that the updates stop (looking in the MQTT explorer) when I load the Home Assistant Companion App on my iPhone.
I don't think it is something related to HA app, but something related to the sensors that the App uses to update the HA server (Localization Services?)

**Comment by DTTerastar** [comment]
I found the issue. Please try updating to the alpha via http://espresense.com/alpha

**Comment by ziolelle** [comment]
@DTTerastar as I already wrote on Discord, it works!
I tested on one of three devices: loaded the HA Companion App and also the Maps. On the device with this alpha updates are still coming, the other two (with old release fw) stopped updating.
Well done !
