### ISSUE TITLE
Auto-Update "stuck" at v3.0.0b3

### ISSUE THREAD

**Issue by DanielBaulig** [ESPresense/ESPresense#642]
**Describe the bug**

All my ESPresense devices are stuck on v3.0.0b3 even though auto-update and pre-release are checked. I will probably just manually flash a more recent version, assuming that this will resolve the issue going forward. Just wanted to report this in case this is something that needs to be investigated further.

**Config**

- Version: v3.0.0b3
- Active scan enabled: No
- Include filter: N/A
- Exclude filter: N/A
- Query filter: N/A

**Hardware**

- Firmware flavor: Standard?
- Device (be specific): ESP WROOM-32

**Logs**

N/A
<img width="404" alt="Screen Shot 2022-09-01 at 8 46 08 AM" src="https://user-images.githubusercontent.com/158797/187957448-5ab128c4-6659-453b-b260-7c0632896bbd.png">

**Screenshots**

**Comment by DTTerastar** [comment]
Yes, known issue, the release notes apologized once I realized.  Gotta hook up the serial and re-flash.  Sorry.  After about b9 or b10 it got all worked out and v3 auto updates like a champ.
