### ISSUE TITLE
PIR pin always pulled high

### ISSUE THREAD

**Issue by Zipties** [ESPresense/ESPresense#662]
I have a PIR sensor that while the out pin is disconnected from the ESP it is functioning correctly. As in I get 3.3 volts on the out pin when there is motion, and it is floating otherwise. 

But when I configure the PIR in settings and connect it to a GPIO pin (I have tried 19 22 and 23) the pin is always pulled high. 

I’m fairly new to microcontrollers but this seems to indicate the pin need a pull up resistor enabled

I feel like I’m doing something wrong but I’m not sure what..

edit:

I confirmed it’s not the device by swapping it out for another. I then loaded esphome with a PIR sketch and it worked as expected. 

It seems whenever a pin is assigned to PIR it outputs 3.3 volts instead of letting the PIR input

**Comment by DTTerastar** [comment]
https://github.com/ESPresense/ESPresense/pull/663 has a fix.  You can install it via https://espresense.com/alpha

**Comment by Zipties** [comment]
> #663 has a fix. You can install it via https://espresense.com/alpha

That did it, you're awesome

**Comment by DTTerastar** [comment]
Released in v3.1.0
