### ISSUE TITLE
Tabbed settings

### ISSUE THREAD

**Issue by Zipties** [ESPresense/ESPresense#665]
This project has really grown over the last year, and the settings have become a bit of a scroll. What do you guys think of implementing a tabbed interface for the different sections of configuration?

WiFi, Calibration, Sensors, enrollment, fingerprints etc

**Comment by DTTerastar** [comment]
I was thinking collapsable accordions, but yeah, it needs help.  We might just need to give up on https://github.com/ESPresense/AsyncWiFiSettings and do it all via custom svelte stuff.
