### ISSUE TITLE
AM2320 Temp/Humidity Sensor

### ISSUE THREAD

**Issue by Zipties** [ESPresense/ESPresense#674]
Would it be difficult to include support for this sensor?

https://github.com/adafruit/Adafruit_AM2320

https://github.com/EngDial/AM2320

**Comment by DTTerastar** [comment]
AM2320 is pin compatible with the DHT22 so you can try using that

**Comment by Zipties** [comment]
The AM2320 is i2c, that doesn't seem like it could work?

**Comment by Zipties** [comment]
I can confirm the DHT22 config does not work with the AM2320

**Comment by DTTerastar** [comment]
Yeah my bad, you're right, it just looks like a DHT.
