### ISSUE TITLE
Add sensor for status of iPhone and Apple Watch 

### ISSUE THREAD

**Issue by ggagnidze** [ESPresense/ESPresense#677]
Hi. Thank you a lot for this great solution. Have one feature request.

As far as I know iPhone, Apple Watch (and maybe others too) devices can announce different information depending are they locked or unlocked.

https://github.com/dalehumby/ESPHome-Apple-Watch-detection/issues/4

0x004C is for unlocked watch and 0x70 for iPhone.

I think it can be very handy to get this information (the fact that device is unlocked and near) for automatisation some secure things like alarm panel and so on.

**Comment by barcar** [comment]
I would also really like to see this capability if it is possible.
