### ISSUE TITLE
Calibration help

### ISSUE THREAD

**Issue by rjbutler** [ESPresense/ESPresense#692]
I have 6 espresense devices in a 3 story townhouse.  They are ustbasically stacked in rooms directly above one another with 3 on each end of the house.  I'd estimate they are 3 or so meters apart on each end (with a ceiling/floor in between.  The devices on on the same floor are about 4m apart and there are walls between them.

I have been trying to tweak RSSI@1M and absorption to get them to accurately report the correct room in HA but it frequently happens that the ESP32 in the same room reports a higher distance than the device a floor below and they get mapped to the wrong room.

I have the RSSI@1m set for my iPhone at 1M with no obstructions (-54).  I have been trying to adjust the absorption of the devices in the rooms that are above/below each other to report correctly but  even when I think I have it, the next day it ends up reporting incorrectly.  Sometimes my wife is in the room above me and mine reports in her room and hers reports in mine.   

Does anyone have any guidance here? 

They're all the same brand ESP32 D1 Mini devices.

**Comment by jerodjchastain** [comment]
Have you found any help on this?

**Comment by rjbutler** [comment]
> Have you found any help on this?

I was mostly able to work around it by tuning absorption and then tweaking my automation so occupancy has to change for more than a minute.  The devices briefly get assigned to the wrong room pretty regularly but not for long.

**Comment by jerodjchastain** [comment]
Yeah some of mine have been doing the same thing

**Comment by jerodjchastain** [comment]
Would I need to go up or down with the absorption if I don’t want the esps to see devices in other rooms?

**Comment by ethanholz** [comment]
I have also had issues with calibration. I would like to propose developing more documentation on calibration. Maybe a compilation of what people do to tweak this system to their needs?

**Comment by OptimusGREEN** [comment]
Yeah I've been having a headache with these kind of issues recently too. More tutorials/docs would be welcomed.

**Comment by ozett** [comment]
maybe a fresh issue is needed for more details on calibration?
no progess on this topic here in 6 month..

i placed today a ibeacon in **1m distance** to an ESPRESENCE device 
and got a **2m distance** reported.

what are the steps to correct this? 
i see changes in the RSSI and RSSI@1m value.

[and even after reading the docs ](https://espresense.com/calibration)i dont know exactly what to do for correction.
do i have to make changes for that beacon, or in general?
[does the buildin values](https://github.com/ESPresense/ESPresense/blob/master/lib/BleFingerprint/rssi.h) have to be checked as well for my indiviual location?

|sample, animated|
|:---:|
![esp-ibeacon](https://user-images.githubusercontent.com/5937811/210344612-7aece8c5-b7e7-40da-809c-a676f7a473fe.gif)

**Comment by DTTerastar** [comment]
The reason antennas are always put high up is they work much better up there.  I am trying to figure out how to correct for this in my espresense companion app.  I have a scenario per floor that gets calculated via just the nodes you want and comes up with a confidence value for the scenario and we use that to pick the most likely scenario.  But it is still a WIP.  I'm trying to make it easier to calibrate by having the gui show the distances graphically with a built in edit.  Device editing works node settings are next.  It runs as an add on in haos.

**Comment by ozett** [comment]
i am willing to experiment a bit,
but as far as i understand your post, there is no need for elaborate calibration, 
because it can not be extremly more accurate because of the hardware conditions anyway.

i read about the idea of zoning.
after rough triangulation, rely on only one device in that zone for distance values (RSSI). 
maybe adittionally use AI or a kalman Filter to smooth out the distance for RSSI
https://www.beaconzone.co.uk/blog/ibeacon-microlocation-accuracy/

but i looks thats all over my head, so i keep on following your efforts until i see a way to make use of it.
I planned espresence to help me open the front door if an ibeacon is closer than 50cm. but it doesn't seem all that easy to implement...

as for now, congratulations for all that has been achieved
