### ISSUE TITLE
One of three espresence device is not reliable

### ISSUE THREAD

**Issue by shakisha** [ESPresense/ESPresense#698]
**Describe the bug**

I have got two apple devices and three espresence devices around the house with v3.1.0 . 
My trouble is that bedroom device is unreliable and many times is not sending mqtt without any kinda of logs, so I don't know if wifi connection trouble, if some antena not reliable, nothing. 
What can I do to debug the issue?

**Comment by AlfredJKwack** [comment]
What happens if you move the ESPresense device to another room where you know there are no network issues and observe that for a while?
