### ISSUE TITLE
Spelling mistake in the project name - Should be "ESPresence"

### ISSUE THREAD

**Issue by ndbroadbent** [ESPresense/ESPresense#702]
Apologies if this has been brought up before, but I searched through the GitHub issues and didn't find anything for "typo" or "spelling".

It's been bugging me for a little while that there's a spelling mistake in the project name. As far as I'm aware, I don't think "presense" is a valid spelling of the word "presence".

#### https://wikidiff.com/presence/presense

<img width="1437" alt="Screen Shot 2022-10-05 at 1 47 27 PM" src="https://user-images.githubusercontent.com/139536/193955915-a8cdbbc1-b7d0-414e-991b-fb0bf8261140.png">

----------

You can see how many times people have spelled it as "espresence" in the GitHub issues: https://github.com/ESPresense/ESPresense/issues?page=1&q=espresence

<img width="853" alt="Screen Shot 2022-10-05 at 2 40 52 PM" src="https://user-images.githubusercontent.com/139536/193961138-aeda8b31-068f-416d-b941-812945ecc589.png">

----------

Another point - lots of results for "presence" in the Home Assistant Core codebase:

<img width="550" alt="Screen Shot 2022-10-05 at 1 33 23 PM" src="https://user-images.githubusercontent.com/139536/193954730-2199d712-5bf1-4d82-b504-a6ec2609d639.png">

Zero results for "presense":

<img width="541" alt="Screen Shot 2022-10-05 at 1 33 35 PM" src="https://user-images.githubusercontent.com/139536/193954744-9e860e30-fa8b-45e7-b160-a2a0f69fa23e.png">

So this can cause some confusion when setting up configuration for Home Assistant and MQTT.

--------

`espresence.com` is unavailable, but I'd be happy to pay for `espresence.io` or `espresence.org`, or some other TLD.

Perhaps this could be done for a version 3 major release.

Please feel free to close this issue if you feel that it's too late to change the name or if it will be too much work. I just thought it needed to be opened!

**Comment by ndbroadbent** [comment]
I forked the project and quickly renamed everything: https://github.com/ndbroadbent/ESPresence

**Comment by markmghali** [comment]
ESP Pre Sense

ESPresense

**Comment by ilium007** [comment]
Came here with the same query!! https://www.askdifference.com/presense-vs-presence/
