### ISSUE TITLE
Can't flash the M5Stamp-c3 device.

### ISSUE THREAD

**Issue by Korte68** [ESPresense/ESPresense#705]
Try to flash this device:

https://docs.m5stack.com/en/core/stamp_c3

Can connect to it, can see the current log.

After i press the install, start the preparing, then:

Failed to initialize. Try resetting your device or holding the BOOT button while clicking INSTALL.

Try the reset and hold every button it has, but no success. 

**Config**

- Version:
- Active scan enabled:
- Include filter:
- Exclude filter:
- Query filter:

**Hardware**

- Firmware flavor: Standard, verbose
- Device (be specific): M5Stamp-c3

**Logs**

Failed to initialize. Try resetting your device or holding the BOOT button while clicking INSTALL.

**Screenshots**

**Comment by oliverboermel** [comment]
why do you cloes it because it is not working same issues no firmware is working
