### ISSUE TITLE
Correct approach for multiple base stations in a room

### ISSUE THREAD

**Issue by davidcoulson** [ESPresense/ESPresense#717]
We have a large basement that needs 2-3 devices to provide coverage (or at least not get it mixed up with the room upstairs). Is there a recommended approach to have multiple devices in a single room? Presumably I can just set the room to the same thing and MQTT handles it, but since the device name is derived from the room name, does this create other problems?

**Comment by AlfredJKwack** [comment]
Discussion #600 ?
