### ISSUE TITLE
Can't install on ep32 D1 mini

### ISSUE THREAD

**Issue by nuk3man** [ESPresense/ESPresense#724]
**Describe the bug**

Installing epshome using esp web tools works fine. However, installing Espresense doesn't work. Tried different cables, browsers, and entire computers. Even tried different esp modules (same models though) without any luck.

Always getting the same error: "**_Failed to initialize. Try resetting your device or holding the BOOT button while clicking INSTALL._**"

Tried shorting the RST & GND pins to force flash mode:

`rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)`
`configsip: 0, SPIWP:0xee`
`clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00`
`mode:DIO, clock div:2`
`load:0x3fff0018,len:4`
`load:0x3fff001c,len:1044`
`load:0x40078000,len:10124`
`load:0x40080400,len:5828`
`entry 0x400806a8`

**Config**

- Version: Standard ver. 3.1.0 Espresnse

**Hardware**

- Device (be specific): [ESP32 D1 Mini](https://www.amazon.se/gp/product/B08BTLYSTM/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1)

**Logs**

Error message: Failed to initialize. Try resetting your device or holding the BOOT button while clicking INSTALL.

**Comment by webhostsg** [comment]
I have an ESP32 D1 Mini and have no issues installing ESPresence...
![IMG20221120115238](https://user-images.githubusercontent.com/59085206/202883874-3aa70f9f-2471-480e-bea9-68784ed19d0d.jpg)
![CleanShot 2022-11-20 at 11 55 23](https://user-images.githubusercontent.com/59085206/202884312-e4565cdc-e1c3-4c9d-bc38-89ad7bceecf7.png)
![CleanShot 2022-11-20 at 11 55 08](https://user-images.githubusercontent.com/59085206/202884325-a6e3c078-8304-4e3e-bb74-3715187f2ef2.png)
