### ISSUE TITLE
Base64 converter on Apple Watch beacon page not working

### ISSUE THREAD

**Issue by apateluk** [ESPresense/ESPresense#728]
When trying to generate the IRK using the online convertor, the output is "0000". 

Following the steps on the [page](https://espresense.com/beacons/apple), my output XML looks like below:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Local Encryption</key>
	<dict>
		<key>Encrypted Diversifier</key>
		<data>
		AAA=
		</data>
		<key>Long-term Key</key>
		<data>
		KEY1_HIDDEN
		</data>
		<key>Long-term Key Length</key>
		<data>
		EA==
		</data>
		<key>Long-term Key Type</key>
		<data>
		Aw==
		</data>
		<key>Random Number</key>
		<data>
		AAAAAAAAAAA=
		</data>
	</dict>
	<key>Remote Encryption</key>
	<dict>
		<key>Long-term Key</key>
		<data>
		KEY1_HIDDEN
		</data>
		<key>Long-term Key Length</key>
		<data>
		EA==
		</data>
		<key>Long-term Key Type</key>
		<data>
		Aw==
		</data>
	</dict>
	<key>Remote IRK</key>
	<data>
	KEY2_HIDDEN
	</data>
</dict>
</plist>
```
I have obfuscated the keys in this example with KEY1_HIDDEN and KEY2_HIDDEN.

Looking at the javascript on the page, it looks like it's attempting to use the first "data" entry it sees.

**Comment by AlfredJKwack** [comment]
Mhh.

Do you have any other bluetooth entries in your keychain? 
Do any of them have a structure like this?

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Remote IRK</key>
  <data>
    KEY1_HIDDEN
  </data>
</dict>
</plist>
```

That's the one that proved to be succesful for me.

**Comment by jlambert121** [comment]
I ran into this as well, looks like there are two entries in keychain with `Account: Public: <MAC>`.  Maybe just a doc update is all that's needed for this.

**Comment by DTTerastar** [comment]
I think I fixed this a couple of days ago.
