### ISSUE TITLE
ESP Cam

### ISSUE THREAD

**Issue by HennieLP** [ESPresense/ESPresense#730]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

ESP camera Stream for homeassistant

**Comment by gkrs** [comment]
Hi @HennieLP

I'm also interested in this and was working some time ago to bring back part of the change proposed in [this pull request](https://github.com/ESPresense/ESPresense/pull/83).
Currently I have a working solution which is not a "live" stream, but rather a webserver for still image from camera, that is queried by HA with some interval (1s im my case). That's sufficient for me at least.

If you would be interested in this solution I'd open a pull request for that.
It will be my first PR ever, I guess, so I have to learn how.
