### ISSUE TITLE
ESP32s lose connection with home assistant

### ISSUE THREAD

**Issue by halogen28372** [ESPresense/ESPresense#733]
My devices lose connection with Home Assistant.  I have different brands and some seem to lose connection more than others.  I thought this was due to poor build quality of the boards but now I suspect it is a bug.  What I saw yesterday was that all the devices were offline, and had been for many hours.  The MQTT broker said they were connected but HA said they weren't.  After rebooting each on, by going to the device's webpage, they showed up and worked within HA.

My question is shouldn't they have rebooted on their own?  And how could they not connect to HA but (apparently) be connected to the MQTT broker HA uses?

**Comment by hellcry37** [comment]
you have a lot of interference, this is not a general issue is just your wireless that drops, this is not a general issue else this would be known believe me
