### ISSUE TITLE
BH1750 update frequency

### ISSUE THREAD

**Issue by simonyel** [ESPresense/ESPresense#744]
I have BH1750 light sensors configured and working. However, the update frequency is over a minute. 

This throws off my light automations: light cuts off because no presence is detected, and the count is below 1. Less than a minute later, someone else walks in, and the lights fail to turn on because the light sensor is still showing plenty of light present.

Can the update frequency be set to something usable, similar to the DHT22, please?

**Comment by simonyel** [comment]
Wasn’t there an “update from URL” field? I’m thinking of using that to shift back to ESPhome as well.

**Comment by MiningPickaxe** [comment]
This is really annoying for me as well... may delay some actions by 60 seconds.
You can always just clone the repo yourself and revert https://github.com/ESPresense/ESPresense/pull/667 but that is not really the elegant and future proof way to do it.
I agree with the PR Author about reducing "spam" via MQTT, but I think a configurable delay would have been the wiser choice here (and also keep the old code that prevented it from sending a mqtt message if the value did not change).

**Comment by simonyel** [comment]
wontfix. Well, then, you can't use this solution for intelligent light control.
