### ISSUE TITLE
RCWL-0516 Doppler Microwave sensor False positives

### ISSUE THREAD

**Issue by Rahulsharma0810** [ESPresense/ESPresense#757]
### Describe the bug

I am trying to make the Microwave doppler sensor work with Espresense, But it gives many false positives every few seconds.

Although I tried it in another esp32 board with simple code to test it, it worked fine.  From some online forums, I tried Ferrite with GND and 3v3 it didn't help.

Has someone tried to test the Radar Sensor with the ESPresense? I hope using it with ambient and Lux sensors don't interfere with its working. 

### Version

3.1.0

### Active scan enabled

yes

### Include filter

N/A

### Exclude filter

N/A

### Query filter

N/A

### Device (be specific)

ESP32

### Screenshots

<img width="759" alt="image" src="https://user-images.githubusercontent.com/9934859/209019720-650b8eca-9f0b-4635-95b0-e1819dc474b3.png">

![IMG_1851](https://user-images.githubusercontent.com/9934859/209019910-5cdcadf2-8775-4c55-859e-bd1eb4b55823.JPG)

**Comment by DTTerastar** [comment]
Do you have a ceiling fan?

**Comment by sebastienvg** [comment]
> ### Describe the bug
> 
> I am trying to make the Microwave doppler sensor work with Espresense, But it gives many false positives every few seconds.
> 
> Although I tried it in another esp32 board with simple code to test it, it worked fine. From some online forums, I tried Ferrite with GND and 3v3 it didn't help.
> 
> Has someone tried to test the Radar Sensor with the ESPresense? I hope using it with ambient and Lux sensors don't interfere with its working.
> ### Version
> 
> 3.1.0
> ### Active scan enabled
> 
> yes
> ### Include filter
> 
> N/A
> ### Exclude filter
> 
> N/A
> ### Query filter
> 
> N/A
> ### Firmware flavor
> 
> _No response_
> ### Device (be specific)
> 
> ESP32
> ### Logs
> 
> _No response_
> ### Screenshots
> 
> <img alt="image" width="759" src="https://user-images.githubusercontent.com/9934859/209019720-650b8eca-9f0b-4635-95b0-e1819dc474b3.png">
> 
> ![IMG_1851](https://user-images.githubusercontent.com/9934859/209019910-5cdcadf2-8775-4c55-859e-bd1eb4b55823.JPG)

I am having the same issue, did you ever solve it?
