### ISSUE TITLE
Feedback v2.0 - Finally the Apple Watch is detected! 

### ISSUE THREAD

**Issue by corgan2222** [ESPresense/ESPresense#77]
The latest Update kills it! Now the Apple Watch looks different as the iPhone and reports even the name correct.
Looks pretty good!

![grafik](https://user-images.githubusercontent.com/12233951/136041433-75f85da0-2bf1-49ad-a48d-ab762ef15908.png)

- Are these extreme long room Assistant name intended? Is this what I have to enter the HA Config? 
- One thing I mentioned is, that the room assistant detection came really late. I would say after around 2-3 minutes.
- At first, I had weird error/debugs messages. But they are gone now after a few minutes.

> ld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
> E NimBLEClient: "Connection failed; status=574 "
> E NimBLEClient: "Connection failed; status=13 "
> lld_pdu_get_tx_flush_nb HCI packet count mismatch (1, 2)
> E NimBLEClient: "Connection failed; status=574 "
> E NimBLERemoteService: "characteristicDiscCB() rc=7 "
> E NimBLERemoteService: "Could not retrieve characteristics"
> E NimBLEClient: "Disconnected, could not retrieve services -aborting"
> E NimBLEClient: "Disconnected, could not retrieve services -aborting"

great Job, thanks!!

**Comment by DTTerastar** [comment]
1. Yes, the long room assistant name is intended, that is the id to put into the config
2. Yeah, something is still a bit wonky, working on making it more consistent
3. Yeah, those are the bowls of ESP32 saying it didn't understand where to route packets.  We need a bunch of retries to work around it atm
