### ISSUE TITLE
[RFC] ibeacon advertisement (#763)

### ISSUE THREAD

**Issue by lolorc** [ESPresense/ESPresense#778]
### Is your feature request related to a problem? Please describe.

looking at the commits I see the "ibeacon advertisement (#763)"  related changes.

I would say it's a very useful feature, I know it's WIP, I guess I would love it to be more configurable:
  - enable / disable
  - beacon frequency
  - ability to choose the beacon fixed address & name
  - even better: ability to give a secret key to derive the mac address from as the apple devices do
  
I haven't looked at the libraries,  I'm not even sure it's possible to broadcast a beacon with a "fake" source address but I wouldn't want somebody to fake my "espresence beacon" if I was to base my automation on it.

anyway, it's a "Thanks" issue, I've only been using ESPresense for ~10 days :-)

**Comment by DTTerastar** [comment]
The main reason I'm working on it is for ESPresense nodes to detect each other and help calibrate the ESPresense-companion app.
