### ISSUE TITLE
Make the GPIO pins configurable & dynamic, read: allow more PIR sensors

### ISSUE THREAD

**Issue by tazzytazzy** [ESPresense/ESPresense#788]
### Is your feature request related to a problem? Please describe.

Current version: ESPresense Version: v3.2.0b5

It's weird to be limited to only one input of each type, such as only one PIR sensor.

### Describe the solution you'd like

Instead of a long list of various sensors with only one possible instance for each type. Such as only one motion sensor.

What do you think of a more dynamic way of adding sensors? Users can click on "add sensor", they select the type, and choose from a list of possible sensors. This way I could add 4 motion detectors to one ESP32 device.

Or, for each sensor type, the user can click on "add new PIR sensor" with fields prompting for the sensor input fields.

### Describe alternatives you've considered

I like ESPHome, but i'm switching over to ESPresence. I only use PIR sensors and BME280, which you already support, but I now get room detection which is oddly lacking in ESPHome.

**Comment by filgr8** [comment]
would like this feature as well
