### ISSUE TITLE
iBeacon UUID not recognized (reported) when mac is unchanged 

### ISSUE THREAD

**Issue by gnome4711** [ESPresense/ESPresense#800]
### Describe the bug

I made an app for android smartphones. It changes the uuid of an iBeacon periodically. 

After changing the UUID the advertised mac is unchanged. in this case Espresense does not report the new uuid. But I can scan see the changing by scanning with another smartphone. The old uuid stops advertising and the new takes over. Espresense still reports the old uuid wich is not advertised anymore.
This came up, when I changed the code of the app. In previous versions the code stopped advertising - waited for 200ms and restarted advertising with new uuid. Android changes the mac address every start. Now I recoded the app and the uuid is altered without stopping advertising. In this case the mac address doesn't change with the new uuid. The device changes it (mac) every 5 minutes or so. The mac address can't be controlled programmatically.
So I'm pretty sure that the issue is the not changing mac address.

Just to avoid questions about why the uuid is changing:
The uuid has encrypted information of the android deviceID and a timestamp. My smarthome system decrypts the uuid and if deviceID and timestamp are valid it sets presence or opens the front door on proximity etc... So its not possible to copy the iBeacon to open the door.

### Version

3.1.1

### Active scan enabled

no

### Include filter

iBeacon:

### Exclude filter

a few

**Comment by gnome4711** [comment]
@dspen 
yes I tried that workaround   with "Forget beacon if not seen for (in milliseconds):" = 50. that works while my beacons dsends every 100ms. But that causes a lot of traffic with 8 sensors in my house.

**Comment by dspen** [comment]
Could you try it with a advertising period greater than 100ms and see if it works still? That would reduce load, and the keys to the linked list should still be generated properly.

**Comment by gnome4711** [comment]
@dspen 
No it doesn't. Thats why I went below the advertising intervall of my beacons wich is 100ms.

**Comment by gnome4711** [comment]
@dspen 
Sorry, I got your post wrong. 100ms is necessary. When increasing to 250ms, espresense isn't always detecting the beacon and I have to wait in front of the door a few seconds. I guess the beacon isn't recognized for a few scan cycles: i think they "miss" each other for few ms (scanning/advertising).

Reporting a  not longer advertised UUID:
I'm not quite sure if this isn't even a problem for the functionallity. The Sensor at the front door reports the current used UUID by walking towards the door and when it is in range the beacon will be reported. Even if the UUID changes during the approach (the rssi gets better), the infos inside the UUID should still be valid to open the door based on the konfiguration of my system in the background.
But I'd feel better knowing the sensor reports the right UUID.

Insinde the house it doesn't really matter because the beacon needs to be updated within 10 minutes to be recognized as present.
