### ISSUE TITLE
AZDelivery ESP32 D1 flash error

### ISSUE THREAD

**Issue by exitus27** [ESPresense/ESPresense#804]
### Describe the bug

 bought it when I erase and press install there is always an error .failed to initialize try resetting ....
I've tried it several times, it doesn't work, even pressing reset button didn't bring this board either.
https://www.amazon.de/dp/B08BTYCGVV?ref=ppx_yo2ov_dt_b_product_details&th=1

terminal log
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff

**Comment by oliverboermel** [comment]
same problem

**Comment by AlexanderGlogger** [comment]
+1
