### ISSUE TITLE
iPhone Draining Find my battery on idle

### ISSUE THREAD

**Issue by mahmoud-os93** [ESPresense/ESPresense#824]
### Describe the bug

Hello,
I have my Homeassistant setup with multiple ESPresense/IRK configured. Does this affect my iPhone battery life ? I am seeing 10-15% of idle battery drain each night that is caused by Find my. Any idea ?

**Comment by tenly2000** [comment]
If you are sharing your location with someone and they are actively tracking your location, your battery will drain faster.  Same is true if you're using the iCloud or iCloud3 integrations for Home Assistant - but it couldn't possibly be this integration as it doesn't interact with FindMy, nor does it cause your iPhone to send out any more bluetooth signals than normal.
