### ISSUE TITLE
"Trying to connect to WiFi" in Configure WiFi process

### ISSUE THREAD

**Issue by redlingg** [ESPresense/ESPresense#829]
### Describe the bug

FW install was ok, But it cannot connect to wifi in the configuration process. The wifi is ok, other devices can connect. 

### Version

3.1.1

**Comment by redlingg** [comment]
ESP32 Lite...( tried other boards but it is the same...)

**Comment by redlingg** [comment]
managed with esp flasher

**Comment by lostkoz4** [comment]
@redlingg I'm having this issue as well, how were you able to solve it?
