### ISSUE TITLE
Ability to control Servo motor

### ISSUE THREAD

**Issue by j3ffrw** [ESPresense/ESPresense#865]
### Is your feature request related to a problem? Please describe.

I see there's an option to use PWM on Leds but couldn't set duty cycle.

### Describe the solution you'd like

would it be possible to be able to set duty cycle so that I could use it to control a servo motor.

### Additional context

I have a toilet trained cat and I'm already tracking him when he enters restroom all I need now is able to flush the toilet after he's done via ESPresense. I plan to use a servo motor to do the flushing and connect it to the already existing ESPresense in that room.

**Comment by DTTerastar** [comment]
I have a fish feeder (basically just a servo) that would be nice to do double duty as well.
