### ISSUE TITLE
Make "adsorption" factor configurable

### ISSUE THREAD

**Issue by ivanvach** [ESPresense/ESPresense#87]
Here is a table of actual; vs reported distance for iPhone 11

actual  -  reported

0.5 m   -  0.5 m
1.0 m   -  1.0m
1.5m    -   1.5m
2.0m   -    2.5m  *
3.0m   -    3.0 m  *
4.0m  -     4.0 m  **
6.0m  -     4.0 m  **
8.0 m  -    4.0 m  **

/* value floats and approaches correct one asymptotically after 10-15 readings 1 sec. apart
/** unreliable readings averaging about 4.0 m but never getting close to real one on longer distances

**Comment by ivanvach** [comment]
I was wrong about my ability to compile the code with line 225 changed. While I have compiled and flashed ESP32 code before using Arduino IDE, I failed with this one as it requires libraries that are not available in Arduino IDE. Actually it is not a good idea to maintain a version that is off the official version(s) and updates.

**Comment by ivanvach** [comment]
To clarify, I'm on the same page. No open air or outdoors testing. All I said was "line of sight" . I just open the door between two rooms so that the iPhone can "see" the ESP32. This is to eliminate the effect of the wall in between. I noticed that others have the same issue. So it will be useful if you add the "absorption factor" adjustment in the settings.

**Comment by DTTerastar** [comment]
This was implemented.
