### ISSUE TITLE
GL-iNet S10 constantly drops POE connection

### ISSUE THREAD

**Issue by uspino2** [ESPresense/ESPresense#888]
### Describe the bug

Installed ESPresense in GL-iNet S10 (v2.1), connected to the AP portal and selected GL-iNET 2.1 POE power in drop-down menu. Reboot. Connected to POE, it gets an IP address and seems to start up, but drops connection every 2 seconds. Might be related to [this](https://github.com/gl-inet/gl-s10-idf-patch)?

### Version

3.2.4

### Firmware flavor

Standard

### Device (be specific)

GL-iNet S10 (v2.1)

**Comment by DTTerastar** [comment]
That link is the idf way to solve.  We need to find the Arduino way of solving it.

**Comment by Matsuo3rd** [comment]
Got this fixed on my setup.
See https://github.com/ESPresense/ESPresense/pull/905

**Comment by uspino2** [comment]
> Got this fixed on my setup.
> See #905

Great! Hoping a new release with the fix will come out soon...

**Comment by DTTerastar** [comment]
Released a beta now, please check!

**Comment by uspino2** [comment]
> Released a beta now, please check!

Thank you! I'm out of town for a week, but I'll check and report back.

**Comment by uspino2** [comment]
Just wanted to report that GL-iNet S10 has been working perfectly fine on v3.3.0b1. No disconnections whatsoever. Good range, runs cool, and POE turns it into a great little device.
