### ISSUE TITLE
ESPresense disconnects/reconnects from Mosquitto every 30 minutes.

### ISSUE THREAD

**Issue by uspino2** [ESPresense/ESPresense#891]
### Describe the bug

Espésense working fine installed in Olimex ESP32-POE, wired connection, UniFi network. 

MQTT integration in Home Assistant reports a disconnect/reconnect exactly every 30 minutes.

Tried tinkering with network settings in UniFi controller. 0% packet loss reported in a 24-hour period. 

Reinstalled Mosquito, MQTT integration, etc. The 30-minute disconnects reappears. 

### Version

3.2.4

### Active scan enabled

-

### Include filter

USB Beacon

### Exclude filter

None

### Query filter

None

### Firmware flavor

Standard

### Device (be specific)

Olimex ESP32-POE

### Logs

```text
2023-04-22 03:54:35: New connection from 10.10.10.55:53586 on port 1883.
2023-04-22 03:54:35: Client espresense-gate already connected, closing old connection.
2023-04-22 03:54:35: New client connected from 10.10.10.55:53586 as espresense-gate (p2, c1, k15, u'mqtt').
```

**Comment by Glacjozo** [comment]
Same issue here. The device is disconected every 30 minutes.
Tested at two different locations (garage and workshop) but..... it works ok at my home.
