### ISSUE TITLE
Getting disconnected, then immediately reconnected again 

### ISSUE THREAD

**Issue by theDontKnowGuy** [ESPresense/ESPresense#895]
### Describe the bug

Have four beacons of stations with 3.2.4 connected to MQTT and HA, all updated to the latest versions.
Monitor four iPhones with known IRKs.
It works well, except that in many cases, i have the exact following behavior: a device turns to not_home, then immediately (like 5 seconds or less) turns back into home. (or if looking into the stations' reporting, one station detects it again).

I sometimes get this behavior a few times an hour while the iPhone rests 10 meters from the station.

What can be done?

### Version

3.2.4

### Active scan enabled

yes

### Include filter

no

### Exclude filter

no

### Query filter

no

### Firmware flavor

normal

### Device (be specific)

ESP32 Devkit V1

**Comment by csw3190** [comment]
@theDontKnowGuy I was having the same issue... until today. Updated my Asus RT-AX88U from Merlin 388.2 to 388.2_2 this morning and am going on about 12 straight hours with no issues. Could be a coincidence but I was going nuts for about a week.
