### ISSUE TITLE
Support Request for ESP32s2

### ISSUE THREAD

**Issue by HeimdallMidgard** [ESPresense/ESPresense#896]
### Is your feature request related to a problem? Please describe.

ESP32S2 is not supported

### Describe the solution you'd like

Add support fpr ESP32S2

### Additional context

Hello, is it possible to add support for ESP32S2 ([lolin_s2_mini](https://docs.platformio.org/en/latest/boards/espressif32/lolin_s2_mini.html)). Theese boards are nicely small and I would like to use em. I tried to add it myself in Platform IO but Iam getting errors since Iam not familiar with changing variables etc. in Plattform IO.

**Comment by DTTerastar** [comment]
ESP32S2 has no bluetooth.

**Comment by HeimdallMidgard** [comment]
Ups. Sorry for this stupid question than. Thanks anyway.

**Comment by jt1971** [comment]
Sorry to re-open this, butI hope this isn't a stupid question.  Wemos S2 mini  and LD2410C seems like a perfect combo with bluetooth provided through the LD2410C. Unless I'm missing something?
