### ISSUE TITLE
Lost IRKs

### ISSUE THREAD

**Issue by derekoharrow** [ESPresense/ESPresense#903]
### Describe the bug

I had 4 iPhones registered and working fine. I made a config change to my ESP32's and I think I may have restarted them all concurrently - net effect - I lost all the registered IRKs and now have to re-pair them all again...

Would setting the irk: topics to retained prevent this?

Or could we have a feature to backup this config and restore it later?

### Version

3.2.4

### Device (be specific)

D1 Mini ESP-32

**Comment by DTTerastar** [comment]
The irks are retained in mqtt via the /espresense/settings/irk:{irk} if you use the ui setup and you can do it manually as well.

**Comment by derekoharrow** [comment]
> The irks are retained in mqtt via the /espresense/settings/irk:{irk} if you use the ui setup and you can do it manually as well.

Those are the keys that have disappeared! 😢
