### ISSUE TITLE
IRK security question

### ISSUE THREAD

**Issue by mahmoud-os93** [ESPresense/ESPresense#906]
Hello,
I was just wondering about the security of using the iphone irk method, can someone emulate having the same irk of my iphone (given that he has the key)? I am asking because I am using the detection of my iphone as a trigger to automate sensitive stuff in my house. Big thanks :)

**Comment by DTTerastar** [comment]
If someone knew your irk, then yes they could spoof it.  In order to get your irk you'd have to securely pair with them for them to get it.
