### ISSUE TITLE
What radar sensor

### ISSUE THREAD

**Issue by ivanvach** [ESPresense/ESPresense#94]
What radar sensor is supported ? I tried this one RCWL-0516 and it keeps reporting false on/off  quite frequently like every 2-3 seconds. I tried it on GPIO 4 and on GPIO 18 same results. I also added a pull up resistor but nothing changed.  Same sensor works well in another ESP based product  at zumungo.com

**Comment by corgan2222** [comment]
Radar Sensor (RCWL-0516) 

more infos here: https://github.com/ESPresense/ESPresense/pull/48

**Comment by corgan2222** [comment]
No, you can use different GPIO pins. 
I changed this after the PR.
