### ISSUE TITLE
value_json in not understood by HA and gives a error in the system logs

### ISSUE THREAD

**Issue by johnnykudahl** [ESPresense/ESPresense#976]
### Describe the bug

 The use of value_json.count makes HA log an error in the system.log
 
 ESPresense-master\src\main.cpp (3 hits)
       Line  35: value_json.count
        
I think HA expects  "payload_json"

**Comment by gadric** [comment]
I have the same problem here: 

![image](https://github.com/ESPresense/ESPresense/assets/19403905/6581f880-e5e2-43e5-95be-d88dd88f711c)

According to MQTT Explorer, espresnse is the only one sending value_json.count.
