### ISSUE TITLE
Multiple ibeacons but only one is published in mqtt

### ISSUE THREAD

**Issue by stlnick3** [ESPresense/ESPresense#994]
### Describe the bug

I have 3 holyiot ibeacons I can only get 1 to publish to mqtt.

All 3 are seen in the espresense log.

Ive tried changing the mac and uuid in the holyiot app. (Is there maybe some kind of checksum in the uuid?)
espresense recognizes the changes in the log but never publishes to mqtt. 
I'm not really sure what's going on. Thank you

### Version

3.2.4 / 3.2.0 / 3.3.03b

### Active scan enabled

i dont see an option

### Include filter

none

### Exclude filter

none

### Query filter

none

### Firmware flavor

standard

### Device (be specific)

ESP32-WROOM-32D DEVKITC V4 / Holyiot ibeacon nrf52810

**Comment by DTTerastar** [comment]
Look at the serial log and bring them close one at a time.  There are circumstances where ESPresense does roll up to a common id.
